Repository kyma-project/lifecycle-manager, pull requests merged in 2022-11, with the labels that each got.

#291 upgrade: module-manager@main and adjust implementation
  .gitignore
  operator/controllers/kyma_controller_remote_sync_test.go
  operator/controllers/kyma_controller_test.go
  operator/controllers/kyma_module_channel_test.go
  operator/controllers/kyma_moduleinfo_test.go
  operator/controllers/moduletemplate_test.go
  operator/controllers/watcher_controller_helper_test.go
  operator/controllers/watcher_controller_test.go
  operator/go.mod
  operator/go.sum
  operator/internal/deploy/webhook_chart.go
  operator/internal/deploy/webhook_config.go
  operator/internal/deploy/webhook_config_test.go
  operator/internal/testutils/utils.go
  samples/template-operator/go.mod
  samples/template-operator/go.sum
Labels: lgtm, size/XL

#295 Reconfig logger format to follow kyma community concept
  operator/controllers/kyma_controller.go
  operator/controllers/watcher_controller.go
  operator/main.go
  operator/pkg/watch/template_change.go
Labels: lgtm, size/M

#307 Remove interval flags
  operator/config/watcher/kustomization.yaml
  operator/controllers/kyma_controller.go
  operator/controllers/suite_test.go
  operator/controllers/watcher_controller.go
  operator/main.go
  samples/template-operator/Makefile
  samples/template-operator/controllers/suite_test.go
Labels: lgtm, size/M

#308 Fix catalog sync gen mismatch by always applying all ModuleTemplates irrespective of generation
  operator/api/v1alpha1/operator_annotations.go
  operator/controllers/kyma_controller_helper_test.go
  operator/controllers/kyma_controller_remote_sync_test.go
  operator/pkg/catalog/remote_catalog.go
Labels: lgtm, size/M

#305 fix: E2E dev documentation
  docs/developer/creating-test-environment.md
  docs/developer/prepare-gcr-registry.md
  docs/developer/provision-cluster-and-registry.md
Labels: lgtm, size/L

#277 Refactor watcher and kyma reconcilers to improve load test performance
  .gitignore
  operator/Dockerfile
  operator/api/v1alpha1/condition_builder.go
  operator/api/v1alpha1/kyma_types.go
  operator/api/v1alpha1/watcher_types.go
  operator/api/v1alpha1/zz_generated.deepcopy.go
  operator/charts/skr-webhook/.helmignore
  operator/charts/skr-webhook/Chart.yaml
  operator/charts/skr-webhook/templates/deployment.yaml
  operator/charts/skr-webhook/templates/rbac.yaml
  operator/charts/skr-webhook/templates/secret.yaml
  operator/charts/skr-webhook/values.yaml
  operator/config/crd/bases/operator.kyma-project.io_watchers.yaml
  operator/config/watcher/kustomization.yaml
  operator/controllers/kyma_controller.go
  operator/controllers/kyma_controller_helper_test.go
  operator/controllers/kyma_controller_remote_sync_test.go
  operator/controllers/kyma_controller_test.go
  operator/controllers/kyma_module_channel_test.go
  operator/controllers/kyma_moduleinfo_test.go
  operator/controllers/moduletemplate_test.go
  operator/controllers/setup.go
  operator/controllers/suite_helper_test.go
  operator/controllers/watcher_controller.go
  operator/controllers/watcher_controller_helper_test.go
  operator/controllers/watcher_controller_test.go
  operator/controllers/withwatcher/kyma_controller_test.go
  operator/controllers/withwatcher/suite_with_watcher_test.go
  operator/controllers/withwatcher/watcher_controller_helper_test.go
  operator/controllers/withwatcher/watcher_controller_test.go
  operator/go.mod
  operator/go.sum
  operator/internal/assets/istio-test-resources.yaml
  operator/internal/custom/istio_client.go
  operator/internal/deploy/chart_manager.go
  operator/internal/deploy/deploy_suite_test.go
  operator/internal/deploy/helm_client_cache.go
  operator/internal/deploy/webhook_chart.go
  operator/internal/deploy/webhook_config.go
  operator/internal/deploy/webhook_config_test.go
  operator/internal/testutils/utils.go
  operator/main.go
  operator/pkg/module/sync/runner_impl.go
  operator/pkg/remote/kyma_synchronization_context.go
Labels: lgtm, size/XXL

#309 Adjust GH Action regarding pipelines
  .github/workflows/test.yml
Labels: lgtm, size/XS

#316 Fix namespace sync by enforcing creation of the namespace and using this in catalog sync for module-templates
  api/v1alpha1/operator_labels.go
  api/v1alpha1/watcher_types.go
  controllers/kyma_controller.go
  controllers/kyma_controller_helper_test.go
  controllers/kyma_controller_remote_sync_test.go
  controllers/kyma_controller_test.go
  controllers/kyma_moduleinfo_test.go
  controllers/moduletemplate_test.go
  controllers/withwatcher/kyma_controller_test.go
  controllers/withwatcher/watcher_controller_helper_test.go
  pkg/catalog/remote_catalog.go
  pkg/remote/kyma_synchronization_context.go
  pkg/testutils/utils.go
  skr-webhook/templates/deployment.yaml
  skr-webhook/values.yaml
Labels: lgtm, size/L

#318 fix: make remote sync more resilient to missing resources and CRDs
  controllers/kyma_controller.go
  pkg/catalog/remote_catalog.go
  pkg/deploy/chart_manager.go
  pkg/remote/context.go
  pkg/remote/kyma_synchronization_context.go
Labels: lgtm, size/L

#323 chore: remove watcher crd from samples folder
  config/samples/component-integration-installed/operator.kyma-project.io_watchers.yaml
Labels: lgtm, size/M

#322 chore: update channels
  Makefile
  api/v1alpha1/kyma_types.go
  api/v1alpha1/webhook_crd_test.go
  config/crd/bases/operator.kyma-project.io_kcpmodules.yaml
  config/crd/bases/operator.kyma-project.io_kymas.yaml
  config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
  config/crd/bases/operator.kyma-project.io_skrmodule2s.yaml
  config/crd/bases/operator.kyma-project.io_skrmodules.yaml
  config/crd/bases/operator.kyma-project.io_watchers.yaml
  config/samples/component-integration-installed/moduletemplates/generate-module-template.sh
  config/samples/component-integration-installed/operator_v1alpha1_kyma.yaml
  config/samples/component-integration-installed/operator_v1alpha1_moduletemplate_kcp-module.yaml
  config/samples/component-integration-installed/operator_v1alpha1_moduletemplate_manifest_example-module-name_stable_production_empty_skr.yaml
  config/samples/component-integration-installed/operator_v1alpha1_moduletemplate_skr-module.yaml
  config/samples/component-integration-installed/operator_v1alpha1_moduletemplate_skr-module2.yaml
  controllers/kyma_controller_remote_sync_test.go
  controllers/kyma_controller_test.go
  controllers/kyma_module_channel_test.go
  controllers/kyma_moduleinfo_test.go
  controllers/moduletemplate_test.go
  docs/developer/creating-test-environment.md
  pkg/channel/lookup.go
Labels: lgtm, size/L

#327 chore: update module-manager deps
  .github/workflows/test.yml
  config/samples/README.md
  config/samples/component-integration-installed/crd/operator.kyma-project.io_kcpmodules.yaml
  config/samples/component-integration-installed/crd/operator.kyma-project.io_skrmodule2s.yaml
  config/samples/component-integration-installed/crd/operator.kyma-project.io_skrmodules.yaml
  controllers/kyma_controller.go
  controllers/kyma_controller_helper_test.go
  controllers/setup.go
  controllers/suite_test.go
  controllers/withwatcher/suite_with_watcher_test.go
  go.mod
  go.sum
  main.go
  pkg/deploy/chart_manager.go
  pkg/deploy/helm_client_cache.go
  pkg/deploy/webhook_chart.go
  pkg/module/common/module.go
  pkg/module/parse/template_to_module.go
  pkg/module/sync/runner_impl.go
  pkg/watch/restricted_enqueue_request_for_owner.go
Labels: lgtm, size/L
