Repository kyma-project/lifecycle-manager, pull requests merged in 2022-10, with the labels that each got.

#227 Cleanup Smoke Tests
  .github/workflows/test.yml
  tests/smoke/go.mod
  tests/smoke/go.sum
  tests/smoke/internal/kustomize.go
  tests/smoke/internal/kyma.go
  tests/smoke/internal/setup.go
  tests/smoke/smoke_test.go
Labels: lgtm, size/XL

#230 docs: Introduce overhauled Documentation for Lifecycle-Manager
  README.md
  docs/architecture-decisions.md
  docs/assets/kyma-operator-architecture.svg
Labels: lgtm, size/XL

#224 add KCP watcher controller and tests
  operator/Dockerfile
  operator/api/v1alpha1/groupversion_info.go
  operator/api/v1alpha1/kyma_types.go
  operator/api/v1alpha1/watcher_types.go
  operator/api/v1alpha1/zz_generated.deepcopy.go
  operator/config/crd/bases/operator.kyma-project.io_watchers.yaml
  operator/config/crd/kustomization.yaml
  operator/config/rbac/role.yaml
  operator/config/watcher/kustomization.yaml
  operator/config/watcher/watcher.yaml
  operator/config/watcher/watcher_service_patch.yaml
  operator/controllers/kyma_controller_helper_test.go
  operator/controllers/setup.go
  operator/controllers/suite_helper_test.go
  operator/controllers/suite_test.go
  operator/controllers/watcher_controller.go
  operator/controllers/watcher_controller_helper_test.go
  operator/controllers/watcher_controller_test.go
  operator/go.mod
  operator/go.sum
  operator/internal/assets/istio-test-resources.yaml
  operator/internal/charts/skr-webhook/.helmignore
  operator/internal/charts/skr-webhook/Chart.yaml
  operator/internal/charts/skr-webhook/templates/deployment.yaml
  operator/internal/charts/skr-webhook/templates/rbac.yaml
  operator/internal/charts/skr-webhook/templates/secret.yaml
  operator/internal/charts/skr-webhook/values.yaml
  operator/internal/custom/istio_client.go
  operator/internal/deploy/deploy_suite_test.go
  operator/internal/deploy/webhook_chart.go
  operator/internal/deploy/webhook_config.go
  operator/internal/deploy/webhook_config_test.go
  operator/main.go
Labels: size/XXL

#232 Refactor load_test as dedicate kustomize build instead of component
  operator/config/default/kustomization.yaml
  operator/config/load_test/kustomization.yaml
Labels: lgtm, size/M

#219 docs: refactor and improve environment setup
  README.md
  docs/architecture-decisions.md
  docs/creating-test-environment-singlecluster.md
  docs/creating-test-environment-twocluster.md
  docs/creating-test-environment.md
  docs/developer/creating-test-environment.md
  docs/developer/prepare-gcr-registry.md
  docs/developer/provision-cluster-and-registry.md
  docs/user/starting-operator-with-webhooks.md
  operator/Dockerfile
  samples/template-operator/README.md
Labels: lgtm, size/XL

#231 Dynamically create Virtual Service resource for watcher reconciler
  operator/controllers/setup.go
  operator/controllers/suite_test.go
  operator/controllers/watcher_controller.go
  operator/controllers/watcher_controller_helper_test.go
  operator/internal/assets/istio-test-resources.yaml
  operator/internal/custom/istio_client.go
  operator/internal/deploy/webhook_config.go
  operator/main.go
Labels: lgtm, size/L

#236 fix: e2e watcher integration
  README.md
  docs/architecture-decisions.md
  docs/creating-test-environment-singlecluster.md
  docs/creating-test-environment-twocluster.md
  docs/creating-test-environment.md
  docs/developer/creating-test-environment.md
  docs/developer/prepare-gcr-registry.md
  docs/developer/provision-cluster-and-registry.md
  docs/user/starting-operator-with-webhooks.md
  operator/config/default/kustomization.yaml
  operator/config/istio/gateway.yaml
  operator/config/load_test/kustomization.yaml
  operator/config/samples/component-integration-installed/operator.kyma-project.io_watchers.yaml
  operator/config/watcher/kustomization.yaml
  operator/config/watcher/operator_v1alpha1_watcher.yaml
  operator/controllers/setup.go
  operator/controllers/watcher_controller.go
  operator/internal/charts/skr-webhook/templates/deployment.yaml
  operator/internal/charts/skr-webhook/values.yaml
  operator/internal/deploy/webhook_chart.go
  operator/internal/deploy/webhook_config.go
  operator/internal/deploy/webhook_config_test.go
  operator/main.go
  samples/template-operator/README.md
Labels: lgtm, size/XL

#240 fix: secret gen for kyma
  operator/config/samples/secret/k3d-secret-gen.sh
Labels: lgtm, size/S

#244 Dynamic Informers watches manifest instead of all resources
  operator/config/istio/gateway.yaml
  operator/config/load_test/kustomization.yaml
  operator/config/load_test/patches/gateway_namespace_replace.yaml
  operator/controllers/setup.go
  operator/go.mod
  operator/internal/custom/istio_client.go
  operator/main.go
  operator/pkg/dynamic/informers.go
Labels: lgtm, size/L

#250 docs: add contents and other minor fixes
  README.md
  docs/developer/creating-test-environment.md
  docs/developer/prepare-gcr-registry.md
  docs/developer/provision-cluster-and-registry.md
Labels: lgtm, size/M

#246 Fix watcher bugs for load test
  .gitignore
  operator/config/rbac/role.yaml
  operator/controllers/kyma_controller.go
  operator/controllers/setup.go
  operator/controllers/util.go
  operator/controllers/watcher_controller.go
  operator/controllers/watcher_controller_helper_test.go
  operator/controllers/watcher_controller_test.go
  operator/internal/assets/istio-test-resources.yaml
  operator/internal/charts/skr-webhook/templates/deployment.yaml
  operator/internal/charts/skr-webhook/values.yaml
  operator/internal/custom/istio_client.go
  operator/internal/deploy/webhook_chart.go
  operator/internal/deploy/webhook_config.go
  operator/internal/deploy/webhook_config_test.go
  operator/main.go
Labels: lgtm, size/L

#252 fix: merge conflicts for add_watcher
  docs/developer/creating-test-environment.md
Labels: lgtm, size/M

#253 fix: merge conflicts for load_test
  README.md
  docs/developer/creating-test-environment.md
  docs/developer/prepare-gcr-registry.md
  docs/developer/provision-cluster-and-registry.md
  operator/config/default/kustomization.yaml
  operator/controllers/watcher_controller_helper_test.go
  operator/controllers/watcher_controller_test.go
  operator/internal/deploy/webhook_chart.go
  operator/internal/deploy/webhook_config_test.go
Labels: lgtm, size/L

#258 Adjust yamls for watcher enabled deployment
  operator/config/control-plane/patches/gateway_delete.yaml
  operator/config/istio/ap.yaml
  operator/config/istio/gataway.yaml
  operator/config/istio/kustomization.yaml
  operator/config/istio/patches/istio_namespace_labels.yaml
  operator/config/load_test/kustomization.yaml
  operator/config/load_test/patches/gateway_name_ns_replace.yaml
  operator/config/load_test/patches/gateway_namespace_replace.yaml
  operator/config/load_test/patches/inject_istio_sidecar_in_deployment.yaml
  operator/config/manager/metrics_service.yaml
  operator/config/watcher/operator_v1alpha1_watcher.yaml
  samples/template-operator/operator/config/rbac/auth_proxy_service.yaml
Labels: lgtm, size/M

#214 Introduce Rate-Limiter for template Operator
  samples/template-operator/operator/Makefile
  samples/template-operator/operator/api/v1alpha1/groupversion_info.go
  samples/template-operator/operator/api/v1alpha1/sample_types.go
  samples/template-operator/operator/controllers/sample_controller.go
  samples/template-operator/operator/controllers/sample_controller_test.go
  samples/template-operator/operator/controllers/suite_test.go
  samples/template-operator/operator/controllers/test/busybox/.helmignore
  samples/template-operator/operator/controllers/test/busybox/Chart.yaml
  samples/template-operator/operator/controllers/test/busybox/templates/deployment.yaml
  samples/template-operator/operator/controllers/test/busybox/templates/service.yaml
  samples/template-operator/operator/controllers/test/busybox/values.yaml
  samples/template-operator/operator/go.mod
  samples/template-operator/operator/main.go
Labels: lgtm, size/L

#259 fix: e2e and docs issues
  operator/config/control-plane/patches/gateway_delete.yaml
  operator/config/default/kustomization.yaml
  operator/config/default/patches/watcher_gateway_patch.yaml
  operator/config/default/patches/watcher_service_patch.yaml
  operator/config/istio/gataway.yaml
  operator/config/istio/kustomization.yaml
  operator/config/watcher/kustomization.yaml
  operator/config/watcher/operator_v1alpha1_watcher.yaml
  samples/template-operator/README.md
Labels: lgtm, size/M

#264 fix: not setting kyma to processing when module is being deleted
  operator/controllers/kyma_controller.go
  operator/controllers/setup.go
  operator/controllers/suite_test.go
  operator/controllers/watcher_controller.go
  operator/pkg/dynamic/informers.go
  operator/pkg/watch/restricted_enqueue_request_for_owner.go
Labels: lgtm, size/L

#265 Enhance patch
  operator/config/default/kustomization.yaml
  operator/config/default/patches/watcher_gateway_patch.yaml
  operator/config/default/patches/watcher_service_patch.yaml
  operator/config/load_test/kustomization.yaml
  operator/config/load_test/patches/gateway_name_ns_replace.yaml
  operator/config/load_test/patches/watcher_service_patch.yaml
Labels: lgtm, size/M

#260 Implement SKR chart removal for last watcher CR deletion
  .gitignore
  operator/controllers/watcher_controller.go
  operator/controllers/watcher_controller_test.go
  operator/go.mod
  operator/go.sum
  operator/internal/deploy/webhook_chart.go
  operator/internal/deploy/webhook_config.go
  operator/internal/deploy/webhook_config_test.go
Labels: lgtm, size/L

#256 chore: update smoke tests with new deploy
  .github/workflows/test.yml
  tests/smoke/smoke_test.go
Labels: lgtm, size/M

#270 feat: introduce (remote) client cache to reduce remote reconciliation latency
  operator/controllers/kyma_controller.go
  operator/controllers/module_catalog_controller.go
  operator/controllers/suite_test.go
  operator/main.go
  operator/pkg/catalog/sync.go
  operator/pkg/remote/client_cache.go
  operator/pkg/remote/kyma_synchronization_context.go
Labels: lgtm, size/L

#274 feat: add finalizer option for declarative lib
  operator/go.mod
  operator/go.sum
  samples/template-operator/README.md
  samples/template-operator/operator/controllers/sample_controller.go
  samples/template-operator/operator/go.mod
  samples/template-operator/operator/go.sum
Labels: lgtm, size/M

#273 feat: include pprof tracing into lifecycle-manager by flag
  operator/config/load_test/kustomization.yaml
  operator/controllers/kyma_controller.go
  operator/main.go
Labels: lgtm, size/M

#278 upgrade to latest declarative pkg
  samples/template-operator/operator/controllers/sample_controller.go
  samples/template-operator/operator/go.mod
  samples/template-operator/operator/go.sum
Labels: lgtm, size/M

#276 feat: refactor module catalog to sync into runtime
  operator/api/v1alpha1/kyma_types.go
  operator/api/v1alpha1/moduletemplate_types.go
  operator/api/v1alpha1/moduletemplate_webhook.go
  operator/api/v1alpha1/operator_annotations.go
  operator/api/v1alpha1/operator_labels.go
  operator/config/crd/bases/operator.kyma-project.io_kymas.yaml
  operator/config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
  operator/config/samples/component-integration-installed/operator_v1alpha1_kyma.yaml
  operator/controllers/kyma_controller.go
  operator/controllers/kyma_controller_helper_test.go
  operator/controllers/kyma_controller_remote_sync_test.go
  operator/controllers/kyma_controller_test.go
  operator/controllers/module_catalog_controller.go
  operator/controllers/setup.go
  operator/controllers/suite_test.go
  operator/go.mod
  operator/go.sum
  operator/main.go
  operator/pkg/catalog/catalog.go
  operator/pkg/catalog/remote_catalog.go
  operator/pkg/catalog/sync.go
  operator/pkg/module/parse/template_to_module.go
  operator/pkg/remote/client_cache.go
  operator/pkg/remote/kyma_synchronization_context.go
Labels: lgtm, size/XL

#282 chore: configurable rate limit adjustments and increased perf test limits for >10k Clusters
  operator/config/load_test/patches/adjust_resources_in_deployment.yaml
  operator/main.go
Labels: lgtm, size/S

#285 template-op: Add custom fields to declarative status subresource
  samples/template-operator/operator/api/v1alpha1/sample_types.go
  samples/template-operator/operator/api/v1alpha1/zz_generated.deepcopy.go
  samples/template-operator/operator/config/crd/bases/operator.kyma-project.io_samples.yaml
  samples/template-operator/operator/controllers/sample_controller.go
  samples/template-operator/operator/go.mod
  samples/template-operator/operator/go.sum
  samples/template-operator/operator/main.go
Labels: lgtm, size/L

#286 Fixed some small stuff
  samples/template-operator/README.md
Labels: lgtm, size/XS

#284 fix: enable typed caching for sync-runner
  operator/Makefile
  operator/config/load_test/kustomization.yaml
  operator/config/watcher/kustomization.yaml
  operator/controllers/kyma_controller.go
  operator/main.go
  operator/pkg/img/layer.go
  operator/pkg/module/common/module.go
  operator/pkg/module/parse/merger.go
  operator/pkg/module/parse/template_to_module.go
  operator/pkg/module/sync/runner_impl.go
Labels: lgtm, size/L

#283 fix: unsafe decoder for descriptor after webhook
  operator/api/v1alpha1/codec/unsafe/codec.go
  operator/api/v1alpha1/kyma_types.go
  operator/api/v1alpha1/moduletemplate_types.go
  operator/api/v1alpha1/webhook_crd_test.go
  operator/config/crd/bases/operator.kyma-project.io_kymas.yaml
  operator/config/load_test/kustomization.yaml
  operator/config/watcher/kustomization.yaml
  operator/controllers/kyma_controller_helper_test.go
  operator/go.mod
  operator/main.go
  operator/pkg/channel/lookup.go
  operator/pkg/module/common/module.go
  operator/pkg/module/parse/template_to_module.go
  operator/pkg/module/sync/runner_impl.go
Labels: lgtm, size/L
