Repository kyma-project/lifecycle-manager, pull requests merged in 2022-12, with the labels that each got.

#331 do ready check after status update
  controllers/kyma_controller.go
Labels: lgtm, size/S

#319 Lookup Istio gateway by label
  Dockerfile
  Makefile
  api/v1alpha1/watcher_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_watchers.yaml
  config/samples/tests/istio-test-resources.yaml
  controllers/setup.go
  controllers/watcher_controller.go
  controllers/withwatcher/suite_with_watcher_test.go
  controllers/withwatcher/watcher_controller_test.go
  flags.go
  main.go
  pkg/istio/client.go
Labels: lgtm, size/XL, area/reconciler

#321 Introduce Domain Name Pinning
  config/istio/gataway.yaml
  controllers/setup.go
  controllers/suite_test.go
  controllers/withwatcher/suite_with_watcher_test.go
  flags.go
  go.mod
  go.sum
  main.go
  pkg/deploy/chart_manager.go
  pkg/deploy/webhook_chart.go
  pkg/istio/client.go
  pkg/security/san_pinning.go
  pkg/security/san_pinning_helper_test.go
  pkg/security/san_pinning_suite_test.go
  pkg/security/san_pinning_test.go
Labels: lgtm, size/XL

#334 fix: add ci mode for smoke test
  .github/workflows/test.yml
Labels: lgtm, size/XS

#332 remove Channel type
  api/v1alpha1/kyma_types.go
  api/v1alpha1/moduletemplate_types.go
  api/v1alpha1/webhook_crd_test.go
  config/crd/bases/operator.kyma-project.io_kymas.yaml
  config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
  controllers/kyma_controller_helper_test.go
  controllers/kyma_controller_remote_sync_test.go
  controllers/kyma_controller_test.go
  controllers/kyma_module_channel_test.go
  controllers/kyma_moduleinfo_test.go
  controllers/moduletemplate_test.go
  controllers/withwatcher/kyma_controller_test.go
  pkg/channel/lookup.go
  pkg/index/template_channel.go
  pkg/module/common/module.go
  pkg/watch/template_change.go
Labels: lgtm, size/L

#337 fix: rate limit due to missing Github Token
  .github/workflows/test.yml
Labels: lgtm, size/XS

#335 Dynamically fetch virtual service hosts from gateway
  api/v1alpha1/watcher_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/control-plane/kustomization.yaml
  config/control-plane/patches/gateway_delete.yaml
  config/crd/bases/operator.kyma-project.io_watchers.yaml
  config/default/kustomization.yaml
  config/istio/gataway.yaml
  config/load_test/kustomization.yaml
  config/samples/tests/istio-test-resources.yaml
  config/watcher/kustomization.yaml
  controllers/watcher_controller.go
  controllers/withwatcher/suite_with_watcher_test.go
  controllers/withwatcher/watcher_controller_helper_test.go
  controllers/withwatcher/watcher_controller_test.go
  flags.go
  main.go
  pkg/istio/client.go
Labels: lgtm, size/XL
