Repository kyma-project/lifecycle-manager, pull requests merged in 2022-09, with the labels that each got.

#132 Make readme content more generic
  docs/creating-test-environment.md
Labels: lgtm, size/XS

#143 Upgrade listener dependency
  operator/controllers/setup.go
  operator/go.mod
  operator/go.sum
Labels: lgtm, size/M

#142 Refactor Module Sync out of Controller Loop
  operator/api/v1alpha1/kyma_types.go
  operator/controllers/kyma_controller.go
  operator/controllers/kyma_controller_helper_test.go
  operator/controllers/kyma_controller_test.go
  operator/pkg/module/common/module.go
  operator/pkg/module/parse/template_to_module.go
  operator/pkg/module/sync/errors.go
  operator/pkg/module/sync/runner.go
  operator/pkg/module/sync/runner_impl.go
  operator/pkg/status/kyma_handler.go
  operator/pkg/status/kyma_helper.go
Labels: lgtm, size/XL

#139 Change namespace and namePrefix
  operator/config/default/kustomization.yaml
  operator/config/istio/kustomization.yaml
  operator/config/istio/pa.yaml
  operator/config/samples/component-integration-installed/rbac/component_rbac.yaml
Labels: lgtm, size/M

#141 Add new test case for remote module sync
  operator/.golangci.yaml
  operator/api/v1alpha1/webhook_crd_test.go
  operator/controllers/kyma_controller_helper_test.go
  operator/controllers/kyma_controller_remote_sync_test.go
  operator/controllers/kyma_controller_test.go
  operator/go.mod
  operator/go.sum
  operator/pkg/test/util.go
Labels: lgtm, size/L

#155 Replaced 'operator' with 'lifecycle-manager' occurrence in docs
  README.md
Labels: lgtm, size/XS

#156 Refactor controller logic
  operator/controllers/kyma_controller.go
  operator/pkg/module/sync/runner_impl.go
Labels: lgtm, size/L

#159 Disable Istio and Prometheus default kustomization
  operator/config/default/kustomization.yaml
Labels: lgtm, size/XS

#160 fix istio resources not being in istio subfolder
  operator/config/istio/gateway.yaml
  operator/config/istio/kustomization.yaml
  operator/config/istio/virtual_service.yaml
  operator/config/manager/gateway.yaml
  operator/config/manager/kustomization.yaml
  operator/config/manager/manager.yaml
Labels: lgtm, size/L

#164 Update kustomization.yaml of istio for enabling virtual service
  operator/config/istio/kustomization.yaml
Labels: lgtm, size/XS

#152 Add kcp dashboard
  operator/Makefile
  operator/config/default/kustomization.yaml
  operator/config/grafana/controller-resources-metrics-configmap.yaml
  operator/config/grafana/controller-runtime-metrics-configmap.yaml
  operator/config/grafana/kcp-dashboard-configmap.yaml
  operator/config/grafana/kustomization.yaml
  operator/grafana/generate-configmap.sh
  operator/grafana/kcp-dashboard.json
Labels: lgtm, size/XXL

#163 Always use Manifest for Rendering instead of native Module CRs
  operator/.golangci.yaml
  operator/Makefile
  operator/config/samples/component-integration-installed/operator_v1alpha1_moduletemplate_kcp-module.yaml
  operator/controllers/kyma_controller_helper_test.go
  operator/controllers/kyma_controller_test.go
  operator/pkg/module/parse/merger.go
  operator/pkg/module/parse/template_to_module.go
  operator/pkg/test/util.go
Labels: lgtm, size/M

#166 Move Manager Resource to Kustomize Component and change default label for selectors
  operator/config/default/kustomization.yaml
  operator/config/manager/kustomization.yaml
  operator/config/manager/manager.yaml
  operator/config/prometheus/monitor.yaml
  operator/config/rbac/auth_proxy_service.yaml
Labels: lgtm, size/S

#168 Fix Kustomization API version
  operator/config/manager/kustomization.yaml
Labels: lgtm, size/XS

#169 Fix wrong namespace in istio virtual service for Kustomization replacement
  operator/config/istio/virtual_service.yaml
Labels: lgtm, size/XS

#170 Fix all pending selectors in kustomize
  operator/config/istio/pa.yaml
  operator/config/manager/manager.yaml
  operator/config/prometheus/monitor.yaml
  operator/config/rbac/auth_proxy_service.yaml
  operator/config/webhook/service.yaml
Labels: lgtm, size/S

#171 Add default `app.kubernetes.io/component` to common labels to fix peer auth and other selectors
  operator/config/default/kustomization.yaml
Labels: lgtm, size/XS

#172 add common label to template operator and adjust README.md
  samples/template-operator/README.md
  samples/template-operator/charts/template-operator/templates/v1_service_template-operator-controller-manager-metrics-service.yaml
  samples/template-operator/operator/config/default/kustomization.yaml
  samples/template-operator/operator/config/manager/manager.yaml
  samples/template-operator/operator/config/rbac/auth_proxy_service.yaml
Labels: lgtm, size/S

#173 fix configmap invalid value
  operator/config/grafana/controller-resources-metrics-configmap.yaml
  operator/config/grafana/controller-runtime-metrics-configmap.yaml
  operator/config/grafana/kcp-dashboard-configmap.yaml
  operator/grafana/generate-configmap.sh
Labels: lgtm, size/S

#174 Removes Virtual Service due to dynamic creation in Control Loop
  operator/config/istio/kustomization.yaml
  operator/config/istio/virtual_service.yaml
Labels: lgtm, size/S

#175 lifecycle-manager: WatcherCR initial setup
  operator/config/default/kustomization.yaml
  operator/config/manager/manager.yaml
  operator/config/watcher/kustomization.yaml
  operator/config/watcher/watcher.yaml
  operator/config/watcher/watcher_service_patch.yaml
  operator/go.mod
  operator/go.sum
Labels: lgtm, size/L

#178 upgrade ginkgo to v2.1.6
  operator/go.mod
  operator/go.sum
  samples/template-operator/operator/controllers/suite_test.go
  samples/template-operator/operator/go.mod
  samples/template-operator/operator/go.sum
Labels: lgtm, size/M

#180 modify template operator readme
  samples/template-operator/README.md
  samples/template-operator/operator/config/default/kustomization.yaml
Labels: lgtm, size/S

#176 Refactor commonlabels
  operator/config/default/commonlabels_override.yaml
  operator/config/default/kustomization.yaml
  samples/template-operator/README.md
  samples/template-operator/charts/template-operator/templates/apps_v1_deployment_template-operator-controller-manager.yaml
  samples/template-operator/charts/template-operator/templates/v1_namespace_template-operator-system.yaml
  samples/template-operator/charts/template-operator/templates/v1_service_template-operator-controller-manager-metrics-service.yaml
  samples/template-operator/operator/config/default/commonlabels_override.yaml
  samples/template-operator/operator/config/default/kustomization.yaml
  samples/template-operator/operator/config/manager/manager.yaml
  samples/template-operator/operator/config/prometheus/monitor.yaml
  samples/template-operator/operator/config/rbac/auth_proxy_service.yaml
Labels: lgtm, size/M

#181 upgrade: watcher resource and dependencies
  operator/config/watcher/watcher.yaml
  operator/controllers/setup.go
  operator/go.mod
  operator/go.sum
Labels: lgtm, size/M

#182 Add Labels which are needed by Watcher
  operator/api/v1alpha1/operator_labels.go
  operator/controllers/kyma_controller.go
  operator/controllers/setup.go
  operator/pkg/remote/kyma_synchronization_context.go
Labels: lgtm, size/S

#192 adjust port
  operator/main.go
Labels: lgtm, size/XS

#198 fix: remove ErrNoComponentSpecified to not error out when there are no modules in Kyma
  operator/api/v1alpha1/operator_labels.go
  operator/controllers/kyma_controller.go
  operator/controllers/kyma_controller_test.go
Labels: lgtm, size/S

#202 Relocate configuration overwrites yaml
  operator/config/default/kustomization.yaml
  operator/config/manager/commonlabels_override.yaml
  operator/config/manager/kustomization.yaml
Labels: lgtm, size/XS

#204 fix: disable grafana by default
  operator/config/default/kustomization.yaml
Labels: lgtm, size/XS

#203 Fix service monitor
  operator/config/manager/metrics_service.yaml
Labels: lgtm, size/XS

#133 Guide for single and two cluster dev setups
  docs/creating-test-environment-gcr.md
  docs/creating-test-environment-singlecluster.md
  docs/creating-test-environment-twocluster.md
  docs/creating-test-environment.md
  operator/config/samples/secret/k3d-secret-gen.sh
  samples/template-operator/hack/gen-kyma.sh
Labels: lgtm, size/XL

#191 Setup Smoke Tests
  operator/Makefile
  operator/config/manager/kustomization.yaml
  tests/smoke/.gitignore
  tests/smoke/Makefile
  tests/smoke/README.md
  tests/smoke/go.mod
  tests/smoke/go.sum
  tests/smoke/internal/common.go
  tests/smoke/internal/common_darwin.go
  tests/smoke/internal/common_linux.go
  tests/smoke/internal/common_windows.go
  tests/smoke/internal/download.go
  tests/smoke/internal/kustomize.go
  tests/smoke/internal/kyma.go
  tests/smoke/internal/kyma_test.go
  tests/smoke/internal/setup.go
  tests/smoke/smoke_test.go
Labels: lgtm, size/XXL

#206 Fix grafana dashboard
  operator/Makefile
  operator/config/default/kustomization.yaml
  operator/config/grafana/controller-resources-metrics-configmap.yaml
  operator/config/grafana/controller-resources-metrics.json
  operator/config/grafana/controller-runtime-metrics-configmap.yaml
  operator/config/grafana/controller-runtime-metrics.json
  operator/config/grafana/kustomization.yaml
  operator/config/grafana/manager-configmap.yaml
  operator/config/grafana/overview.json
  operator/config/istio/ap.yaml
  operator/config/istio/commonlabels_override.yaml
  operator/config/istio/kustomization.yaml
  operator/config/manager/kustomization.yaml
  operator/config/prometheus/commonlabels_override.yaml
  operator/config/prometheus/kustomization.yaml
  operator/config/rbac/role.yaml
  operator/grafana/generate-configmap.sh
Labels: lgtm, size/L

#207 fix: merge target into spec
  operator/pkg/module/parse/merger.go
Labels: lgtm, size/XS

#205 fix: add config map privileges for catalog sync
  operator/config/manager/kustomization.yaml
  operator/config/rbac/role.yaml
  operator/controllers/kyma_controller.go
Labels: lgtm, size/S

#210 add name and namespace before getModule
  operator/pkg/module/sync/runner_impl.go
Labels: lgtm, size/XS

#211 fix: e2e fixes for 2 cluster setup
  docs/creating-test-environment-gcr.md
  docs/creating-test-environment.md
  operator/config/manager/kustomization.yaml
  operator/config/manager/manager.yaml
  operator/config/rbac/role.yaml
  operator/config/samples/secret/k3d-secret-gen.sh
  operator/pkg/remote/client.go
  samples/template-operator/Makefile
  samples/template-operator/README.md
  samples/template-operator/hack/gen-mod-template.sh
  samples/template-operator/operator/Dockerfile
  samples/template-operator/operator/Makefile
  samples/template-operator/operator/config/default/kustomization.yaml
  samples/template-operator/operator/config/rbac/role.yaml
  samples/template-operator/operator/controllers/sample_controller.go
Labels: lgtm, size/L

#212 upgrade: module-operator dependencies
  operator/go.mod
  operator/go.sum
  samples/template-operator/Makefile
  samples/template-operator/operator/go.mod
  samples/template-operator/operator/go.sum
Labels: lgtm, size/S

#209 Create Github Action for Smoke Tests to work around DIND problem
  .github/workflows/test.yml
  .gitignore
  operator/.golangci.yaml
  operator/Makefile
  operator/config/manager/manager.yaml
  tests/smoke/go.mod
  tests/smoke/go.sum
  tests/smoke/internal/common.go
  tests/smoke/internal/common_darwin.go
  tests/smoke/internal/common_linux.go
  tests/smoke/internal/common_windows.go
  tests/smoke/internal/download.go
  tests/smoke/internal/kustomize.go
  tests/smoke/internal/kyma.go
  tests/smoke/internal/setup.go
  tests/smoke/smoke_test.go
Labels: lgtm, size/XL

#208 [proposal] New unit test pattern
  operator/controllers/kyma_controller_helper_test.go
  operator/controllers/kyma_controller_remote_sync_test.go
  operator/controllers/kyma_controller_test.go
  operator/controllers/kyma_moduleinfo_test.go
Labels: lgtm, size/L

#213 feat: setup control-plane compatible deployment
  .github/workflows/test.yml
  operator/Makefile
  operator/config/control-plane/kustomization.yaml
  operator/config/control-plane/patches/cainjection_in_kymas.yaml
  operator/config/control-plane/patches/cainjection_in_moduletemplates.yaml
  operator/config/control-plane/patches/ebable_webhook_in_moduletemplate_crd.yaml
  operator/config/control-plane/patches/enable_webhook_in_kyma_crd.yaml
  operator/config/control-plane/patches/enable_webhooks_in_deployment.yaml
  operator/config/control-plane/patches/gateway_delete.yaml
  operator/config/control-plane/patches/metrics_namespace_replace.yaml
  operator/config/control-plane/patches/namespace_delete.yaml
  operator/config/control-plane/patches/secured_manager_auth_proxy.yaml
  operator/config/control-plane/patches/service_monitor.yaml
  operator/config/control-plane/patches/unique_certificate_name.yaml
  operator/config/control-plane/patches/unique_manager_webhook_patch.yaml
  operator/config/control-plane/patches/webhook_configuration_cainjection.yaml
  operator/config/crd/bases/operator.kyma-project.io_kymas.yaml
  operator/config/manager/kustomization.yaml
  operator/go.mod
  operator/go.sum
  tests/smoke/internal/kyma_test.go
Labels: lgtm, size/XL

#217 chore: add kustomize dry-run targets
  .github/workflows/test.yml
Labels: lgtm, size/S

#218 add script to replace k3d port in module template
  samples/template-operator/Makefile
  samples/template-operator/hack/local-template.sh
Labels: lgtm, size/S

#220 chore: add kyma alpha deploy test
  .github/workflows/test.yml
Labels: lgtm, size/M

#222 Enhance docker push for GCR
  docs/creating-test-environment-gcr.md
  operator/Makefile
  samples/template-operator/operator/Makefile
Labels: lgtm, size/S

#221 Fix moduletemplate changes not propagated to manifest CR
  operator/config/rbac/role.yaml
  operator/controllers/kyma_controller.go
  operator/controllers/kyma_controller_helper_test.go
  operator/controllers/kyma_controller_remote_sync_test.go
  operator/controllers/kyma_controller_test.go
  operator/controllers/kyma_moduleinfo_test.go
  operator/controllers/module_catalog_controller.go
  operator/controllers/moduletemplate_test.go
  operator/pkg/module/sync/runner_impl.go
Labels: lgtm, size/L
