Repository kyma-project/lifecycle-manager, pull requests merged in 2022-08, with the labels that each got.

#100 feat: init template operator with basic README
  samples/template-operator/.dockerignore
  samples/template-operator/.gitignore
  samples/template-operator/Dockerfile
  samples/template-operator/Makefile
  samples/template-operator/PROJECT
  samples/template-operator/README.md
  samples/template-operator/api/v1alpha1/groupversion_info.go
  samples/template-operator/api/v1alpha1/mockup_types.go
  samples/template-operator/api/v1alpha1/zz_generated.deepcopy.go
  samples/template-operator/config/crd/bases/component.kyma-project.io_mockups.yaml
  samples/template-operator/config/crd/kustomization.yaml
  samples/template-operator/config/crd/kustomizeconfig.yaml
  samples/template-operator/config/crd/patches/cainjection_in_mockups.yaml
  samples/template-operator/config/crd/patches/webhook_in_mockups.yaml
  samples/template-operator/config/default/kustomization.yaml
  samples/template-operator/config/default/manager_auth_proxy_patch.yaml
  samples/template-operator/config/default/manager_config_patch.yaml
  samples/template-operator/config/manager/controller_manager_config.yaml
  samples/template-operator/config/manager/kustomization.yaml
  samples/template-operator/config/manager/manager.yaml
  samples/template-operator/config/prometheus/kustomization.yaml
  samples/template-operator/config/prometheus/monitor.yaml
  samples/template-operator/config/rbac/auth_proxy_client_clusterrole.yaml
  samples/template-operator/config/rbac/auth_proxy_role.yaml
  samples/template-operator/config/rbac/auth_proxy_role_binding.yaml
  samples/template-operator/config/rbac/auth_proxy_service.yaml
  samples/template-operator/config/rbac/kustomization.yaml
  samples/template-operator/config/rbac/leader_election_role.yaml
  samples/template-operator/config/rbac/leader_election_role_binding.yaml
  samples/template-operator/config/rbac/mockup_editor_role.yaml
  samples/template-operator/config/rbac/mockup_viewer_role.yaml
  samples/template-operator/config/rbac/role.yaml
  samples/template-operator/config/rbac/role_binding.yaml
  samples/template-operator/config/rbac/service_account.yaml
  samples/template-operator/config/samples/component_v1alpha1_mockup.yaml
  samples/template-operator/controllers/mockup_controller.go
  samples/template-operator/controllers/suite_test.go
  samples/template-operator/go.mod
  samples/template-operator/go.sum
  samples/template-operator/hack/boilerplate.go.txt
  samples/template-operator/main.go
Labels: lgtm, size/XXL

#98 Virtual Sync of KCP and SKR Modules
  .gitignore
  operator/Makefile
  operator/api/v1alpha1/kyma_types.go
  operator/api/v1alpha1/zz_generated.deepcopy.go
  operator/config/crd/bases/operator.kyma-project.io_kymas.yaml
  operator/config/samples/component-integration-installed/operator_v1alpha1_kyma.yaml
  operator/config/samples/component-integration-installed/operator_v1alpha1_moduletemplate_manifest_example-module-name_stable_production_empty_skr.yaml
  operator/controllers/kyma_controller.go
  operator/controllers/kyma_controller_helper_test.go
  operator/controllers/kyma_controller_test.go
  operator/controllers/suite_test.go
  operator/main.go
  operator/pkg/parsed/module.go
  operator/pkg/parsed/template_to_module.go
  operator/pkg/remote/client.go
  operator/pkg/remote/kyma_synchronization_context.go
  operator/pkg/status/kyma_handler.go
Labels: lgtm, size/XL

#103 Setup Sync of KCP ModuleTemplates into SKR ConfigMap
  operator/api/v1alpha1/groupversion_info.go
  operator/api/v1alpha1/kyma_types.go
  operator/api/v1alpha1/moduletemplate_types.go
  operator/api/v1alpha1/moduletemplate_webhook.go
  operator/api/v1alpha1/operator_labels.go
  operator/config/samples/README.md
  operator/config/samples/component-integration-installed/crd/v1/kcpmodule_types.go
  operator/config/samples/component-integration-installed/crd/v1alpha1/kcpmodule_types.go
  operator/config/samples/component-integration-installed/crd/v1alpha1/skrmodule2_types.go
  operator/config/samples/component-integration-installed/crd/v1alpha1/skrmodule_types.go
  operator/config/samples/component-integration-installed/crd/v1beta1/kcpmodule_types.go
  operator/config/samples/component-integration-installed/crd/v1beta1/skrmodule_types.go
  operator/config/samples/secret/k3d-secret-gen.sh
  operator/controllers/kyma_controller.go
  operator/controllers/kyma_controller_helper_test.go
  operator/controllers/kyma_controller_test.go
  operator/controllers/module_template_controller.go
  operator/controllers/setup.go
  operator/controllers/suite_test.go
  operator/main.go
  operator/pkg/client/clientset/versioned/fake/register.go
  operator/pkg/client/clientset/versioned/scheme/register.go
  operator/pkg/remote/kyma_synchronization_context.go
  operator/pkg/status/kyma_handler.go
Labels: lgtm, size/XL

#105 Refact module template info
  operator/.golangci.yaml
  operator/api/v1alpha1/kyma_types.go
  operator/api/v1alpha1/zz_generated.deepcopy.go
  operator/config/crd/bases/operator.kyma-project.io_kymas.yaml
  operator/controllers/kyma_controller.go
  operator/pkg/adapter/eventing_adapter.go
  operator/pkg/parsed/module.go
  operator/pkg/release/lookup.go
  operator/pkg/status/kyma_handler.go
Labels: lgtm, size/L

#110 rename custom resource - mockup -> sample
  samples/template-operator/README.md
  samples/template-operator/charts/template-operator/crds/apiextensions.k8s.io_v1_customresourcedefinition_samples.component.kyma-project.io.yaml
  samples/template-operator/charts/template-operator/templates/rbac.authorization.k8s.io_v1_clusterrole_template-operator-manager-role.yaml
  samples/template-operator/default.yaml
  samples/template-operator/operator/PROJECT
  samples/template-operator/operator/api/v1alpha1/sample_types.go
  samples/template-operator/operator/api/v1alpha1/zz_generated.deepcopy.go
  samples/template-operator/operator/config/crd/bases/component.kyma-project.io_samples.yaml
  samples/template-operator/operator/config/crd/kustomization.yaml
  samples/template-operator/operator/config/crd/patches/cainjection_in_samples.yaml
  samples/template-operator/operator/config/crd/patches/webhook_in_samples.yaml
  samples/template-operator/operator/config/rbac/role.yaml
  samples/template-operator/operator/config/rbac/sample_editor_role.yaml
  samples/template-operator/operator/config/rbac/sample_viewer_role.yaml
  samples/template-operator/operator/config/samples/default.yaml
  samples/template-operator/operator/controllers/sample_controller.go
  samples/template-operator/operator/main.go
  samples/template-operator/template.yaml
Labels: lgtm, size/L

#113 Adapt Makefile for Image build
  operator/Makefile
Labels: lgtm, size/XS

#111 feat (template-operator): init implementation for sample resource
  samples/template-operator/README.md
  samples/template-operator/operator/Dockerfile
  samples/template-operator/operator/api/v1alpha1/sample_types.go
  samples/template-operator/operator/config/crd/bases/component.kyma-project.io_samples.yaml
  samples/template-operator/operator/config/samples/default.yaml
  samples/template-operator/operator/controllers/sample_controller.go
  samples/template-operator/operator/go.mod
  samples/template-operator/operator/go.sum
  samples/template-operator/operator/module-chart/.helmignore
  samples/template-operator/operator/module-chart/Chart.yaml
  samples/template-operator/operator/module-chart/templates/configmap.yaml
  samples/template-operator/operator/module-chart/templates/deployment.yaml
  samples/template-operator/operator/module-chart/values.yaml
Labels: lgtm, size/XXL

#112 setup local module list sync
  operator/.golangci.yaml
  operator/Makefile
  operator/api/v1alpha1/kyma_types.go
  operator/api/v1alpha1/operator_labels.go
  operator/api/v1alpha1/webhook_crd_test.go
  operator/config/crd/bases/operator.kyma-project.io_kymas.yaml
  operator/controllers/kyma_controller_helper_test.go
  operator/controllers/kyma_controller_test.go
  operator/controllers/module_catalog_controller.go
  operator/controllers/setup.go
  operator/controllers/suite_test.go
  operator/go.mod
  operator/main.go
  operator/pkg/catalog/catalog.go
  operator/pkg/catalog/sync.go
  operator/pkg/parsed/module.go
  operator/pkg/parsed/template_to_module.go
  operator/pkg/release/lookup.go
  operator/pkg/remote/kyma_synchronization_context.go
  operator/pkg/signature/verifier.go
  operator/pkg/test/util.go
  operator/pkg/watch/restricted_enqueue_request_for_owner.go
Labels: lgtm, size/XL

#117 Refactor status.condition
  operator/api/v1alpha1/condition_builder.go
  operator/api/v1alpha1/kyma_types.go
  operator/api/v1alpha1/operator_labels.go
  operator/api/v1alpha1/zz_generated.deepcopy.go
  operator/config/crd/bases/operator.kyma-project.io_kymas.yaml
  operator/config/samples/component-integration-installed/operator_v1alpha1_kyma.yaml
  operator/controllers/kyma_controller.go
  operator/controllers/kyma_controller_helper_test.go
  operator/controllers/kyma_controller_test.go
  operator/pkg/status/kyma_handler.go
Labels: lgtm, size/XL

#124 upgrade: manifest library dependencies
  samples/template-operator/default.yaml
  samples/template-operator/operator/api/v1alpha1/sample_types.go
  samples/template-operator/operator/config/crd/bases/component.kyma-project.io_samples.yaml
  samples/template-operator/operator/config/samples/default.yaml
  samples/template-operator/operator/controllers/sample_controller.go
  samples/template-operator/operator/go.mod
  samples/template-operator/operator/go.sum
  samples/template-operator/operator/module-chart/templates/configmap.yaml
  samples/template-operator/operator/module-chart/templates/deployment.yaml
Labels: lgtm, size/L

#125 fix: rbac issues with kubebuilder generated image
  samples/template-operator/operator/Dockerfile
  samples/template-operator/operator/config/rbac/role.yaml
  samples/template-operator/operator/controllers/sample_controller.go
Labels: lgtm, size/M

#121 Add grafana plugin to generate default grafana dashboard file
  operator/Makefile
  operator/PROJECT
  operator/grafana/controller-resources-metrics.json
  operator/grafana/controller-runtime-metrics.json
  samples/template-operator/Makefile
  samples/template-operator/README.md
  samples/template-operator/operator/PROJECT
  samples/template-operator/operator/grafana/controller-resources-metrics.json
  samples/template-operator/operator/grafana/controller-runtime-metrics.json
Labels: lgtm, size/XXL

#122 Setup Kyma/Manifest Operator Test Guide
  docs/creating-test-environment.md
  operator/api/v1alpha1/kyma_types.go
  operator/api/v1alpha1/operator_labels.go
  operator/config/crd/bases/operator.kyma-project.io_kymas.yaml
  operator/config/default/kustomization.yaml
  operator/config/rbac/kustomization.yaml
  operator/config/rbac/manifest_role.yaml
  operator/config/samples/secret/k3d-secret-gen.sh
  operator/controllers/kyma_controller.go
  operator/controllers/kyma_controller_test.go
  operator/pkg/watch/template_change.go
  samples/template-operator/.gitignore
  samples/template-operator/Makefile
  samples/template-operator/charts/template-operator/Chart.yaml
  samples/template-operator/charts/template-operator/crds/apiextensions.k8s.io_v1_customresourcedefinition_samples.component.kyma-project.io.yaml
  samples/template-operator/charts/template-operator/templates/apps_v1_deployment_template-operator-controller-manager.yaml
  samples/template-operator/charts/template-operator/templates/rbac.authorization.k8s.io_v1_clusterrole_template-operator-manager-role.yaml
  samples/template-operator/config.yaml
  samples/template-operator/default.yaml
  samples/template-operator/hack/gen-kyma.sh
  samples/template-operator/mod/component-descriptor.yaml
  samples/template-operator/mod/remote-component-descriptor.yaml
  samples/template-operator/operator/Dockerfile
  samples/template-operator/operator/config/manager/kustomization.yaml
  samples/template-operator/operator/config/manager/manager.yaml
  samples/template-operator/operator/module-chart/templates/deployment.yaml
  samples/template-operator/template.yaml
Labels: lgtm, size/XL

#123 feat(template-operator): init declaritive pattern
  samples/template-operator/operator/api/v1alpha1/sample_types.go
  samples/template-operator/operator/api/v1alpha1/zz_generated.deepcopy.go
  samples/template-operator/operator/config/crd/bases/component.kyma-project.io_samples.yaml
  samples/template-operator/operator/controllers/sample_controller.go
  samples/template-operator/operator/go.mod
  samples/template-operator/operator/go.sum
Labels: lgtm, size/L

#128 rename kyma-watcher => runtime-watcher
  operator/controllers/setup.go
  operator/go.mod
  operator/go.sum
Labels: lgtm, size/M

#129 Update README.md after renaming
  README.md
Labels: lgtm, size/S

#134 refactor: rename dependency manifest-operator => module-manager
  docs/assets/kyma-operator-architecture.svg
  docs/creating-test-environment.md
  operator/config/rbac/manifest_role.yaml
  operator/config/samples/README.md
  operator/config/samples/component-integration-installed/operator_v1alpha1_moduletemplate_manifest_example-module-name_stable_production_empty_skr.yaml
  operator/config/samples/component-integration-installed/operator_v1alpha1_moduletemplate_skr-module.yaml
  operator/config/samples/component-integration-installed/operator_v1alpha1_moduletemplate_skr-module2.yaml
  operator/config/samples/component-integration-installed/rbac/component_rbac.yaml
  operator/controllers/kyma_controller_helper_test.go
  operator/controllers/suite_test.go
  operator/go.mod
  operator/go.sum
  samples/template-operator/operator/api/v1alpha1/sample_types.go
  samples/template-operator/operator/controllers/sample_controller.go
  samples/template-operator/operator/go.mod
  samples/template-operator/operator/go.sum
Labels: lgtm, size/M

#135 Rename group to operator.kyma-project.io
  .gitignore
  docs/creating-test-environment.md
  operator/api/v1alpha1/operator_labels.go
  operator/api/v1alpha1/webhook_crd_test.go
  operator/config/samples/component-integration-installed/crd/operator.kyma-project.io_kcpmodules.yaml
  operator/config/samples/component-integration-installed/crd/operator.kyma-project.io_skrmodule2s.yaml
  operator/config/samples/component-integration-installed/crd/operator.kyma-project.io_skrmodules.yaml
  operator/config/samples/component-integration-installed/crd/v1/kcpmodule_types.go
  operator/config/samples/component-integration-installed/crd/v1alpha1/kcpmodule_types.go
  operator/config/samples/component-integration-installed/crd/v1alpha1/skrmodule2_types.go
  operator/config/samples/component-integration-installed/crd/v1alpha1/skrmodule_types.go
  operator/config/samples/component-integration-installed/crd/v1beta1/kcpmodule_types.go
  operator/config/samples/component-integration-installed/crd/v1beta1/skrmodule_types.go
  operator/config/samples/component-integration-installed/moduletemplates/generate-module-template.sh
  operator/config/samples/component-integration-installed/operator_v1alpha1_moduletemplate_kcp-module.yaml
  operator/config/samples/tests/crds/operator.kyma-project.io_samplecrd-invalid.yaml
  operator/config/samples/tests/crds/operator.kyma-project.io_samplecrd.yaml
  operator/controllers/setup.go
  operator/controllers/suite_test.go
  samples/template-operator/charts/template-operator/crds/apiextensions.k8s.io_v1_customresourcedefinition_samples.component.kyma-project.io.yaml
  samples/template-operator/charts/template-operator/templates/rbac.authorization.k8s.io_v1_clusterrole_template-operator-manager-role.yaml
  samples/template-operator/default.yaml
  samples/template-operator/operator/api/v1alpha1/groupversion_info.go
  samples/template-operator/operator/config/crd/bases/component.kyma-project.io_samples.yaml
  samples/template-operator/operator/config/crd/kustomization.yaml
  samples/template-operator/operator/config/crd/patches/cainjection_in_samples.yaml
  samples/template-operator/operator/config/crd/patches/webhook_in_samples.yaml
  samples/template-operator/operator/config/rbac/role.yaml
  samples/template-operator/operator/config/rbac/sample_editor_role.yaml
  samples/template-operator/operator/config/rbac/sample_viewer_role.yaml
  samples/template-operator/operator/config/samples/default.yaml
  samples/template-operator/operator/controllers/sample_controller.go
  samples/template-operator/template.yaml
Labels: lgtm, size/L

#136 feat(template-operator): implement implicit chart handling + other features
  samples/template-operator/Makefile
  samples/template-operator/README.md
  samples/template-operator/charts/template-operator/Chart.yaml
  samples/template-operator/charts/template-operator/crds/apiextensions.k8s.io_v1_customresourcedefinition_samples.component.kyma-project.io.yaml
  samples/template-operator/config.yaml
  samples/template-operator/default.yaml
  samples/template-operator/hack/gen-chart.sh
  samples/template-operator/operator/api/v1alpha1/sample_types.go
  samples/template-operator/operator/api/v1alpha1/zz_generated.deepcopy.go
  samples/template-operator/operator/config/crd/bases/component.kyma-project.io_samples.yaml
  samples/template-operator/operator/config/manager/kustomization.yaml
  samples/template-operator/operator/config/samples/default.yaml
  samples/template-operator/operator/controllers/sample_controller.go
  samples/template-operator/operator/go.mod
  samples/template-operator/operator/go.sum
  samples/template-operator/operator/module-chart/templates/deployment.yaml
  samples/template-operator/operator/module-chart/values.yaml
Labels: lgtm, size/XL

#140 docs: Enhance template operator README.md
  samples/template-operator/README.md
Labels: lgtm, size/L

#138 Refactoring reconcile logic
  operator/controllers/kyma_controller.go
Labels: lgtm, size/M
