Repository kyma-project/lifecycle-manager, pull requests merged in 2022-07, with the labels that each got.

#63 Go1.18 upgrade
  operator/Makefile
  operator/api/v1alpha1/groupversion_info.go
  operator/api/v1alpha1/kyma_types.go
  operator/api/v1alpha1/zz_generated.deepcopy.go
  operator/config/crd/bases/operator.kyma-project.io_kymas.yaml
  operator/config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
  operator/config/samples/component-integration-installed/operator_v1alpha1_kyma.yaml
  operator/controllers/kyma_controller.go
  operator/go.mod
  operator/go.sum
  operator/pkg/remote/kyma_synchronization_context.go
Labels: lgtm

#65 Improve secret generate script
  operator/config/manager/manager.yaml
  operator/config/samples/secret/k3d-secret-gen.sh
  operator/controllers/kyma_controller_test.go
Labels: lgtm

#70 Change custom settings to unstructured object
  operator/api/v1alpha1/kyma_types.go
  operator/api/v1alpha1/zz_generated.deepcopy.go
  operator/config/crd/bases/operator.kyma-project.io_kymas.yaml
  operator/pkg/util/kyma_util.go
Labels: lgtm

#69 Setup module packaging
  operator/.golangci.yaml
  operator/Makefile
  operator/api/v1alpha1/kyma_types.go
  operator/api/v1alpha1/moduletemplate_types.go
  operator/api/v1alpha1/zz_generated.deepcopy.go
  operator/config/crd/bases/operator.kyma-project.io_kymas.yaml
  operator/config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
  operator/config/samples/component-integration-installed/moduletemplates/README.md
  operator/config/samples/component-integration-installed/moduletemplates/data/.gitignore
  operator/config/samples/component-integration-installed/moduletemplates/data/config.yaml
  operator/config/samples/component-integration-installed/moduletemplates/example/blobs/sha256:079e0eeb88187349a2dd2584bbce122b4319acb767e1c23a9c49beace26ceda0
  operator/config/samples/component-integration-installed/moduletemplates/example/blobs/sha256:9d37fb366e4371b44c94496f3db276bd6f3a1019c9d44077b689c68ec6486c1e
  operator/config/samples/component-integration-installed/moduletemplates/example/component-descriptor.yaml
  operator/config/samples/component-integration-installed/moduletemplates/generate-module-template.sh
  operator/config/samples/component-integration-installed/moduletemplates/generated-module-template.yaml
  operator/config/samples/component-integration-installed/moduletemplates/private-key.pem
  operator/config/samples/component-integration-installed/moduletemplates/public-key-secret.yaml
  operator/config/samples/component-integration-installed/moduletemplates/public-key.pem
  operator/config/samples/component-integration-installed/moduletemplates/remote-component-descriptor-signed.yaml
  operator/config/samples/component-integration-installed/moduletemplates/remote-component-descriptor.yaml
  operator/config/samples/component-integration-installed/moduletemplates/resources.yaml
  operator/config/samples/component-integration-installed/operator_v1alpha1_kyma.yaml
  operator/controllers/kyma_controller.go
  operator/go.mod
  operator/go.sum
  operator/main.go
  operator/pkg/img/img_utils.go
  operator/pkg/labels/operator_labels.go
  operator/pkg/signature/signature.go
  operator/pkg/status/kyma_handler.go
  operator/pkg/util/kyma_util.go
  operator/pkg/watch/component_change.go
Labels: lgtm

#72 fix: various lint fixes
  operator/controllers/kyma_controller.go
Labels: lgtm

#41 Implement listener component
  operator/config/manager/gateway.yaml
  operator/config/manager/kustomization.yaml
  operator/config/manager/manager.yaml
  operator/config/rbac/role.yaml
  operator/controllers/kyma_controller.go
  operator/controllers/suite_test.go
  operator/go.mod
  operator/go.sum
  operator/main.go
Labels: lgtm

#74 For load test
  operator/Dockerfile
  operator/config/crd/bases/operator.kyma-project.io_kymas.yaml
  operator/config/default/kustomization.yaml
  operator/config/default/manager_auth_proxy_patch.yaml
  operator/config/rbac/kustomization.yaml
  operator/config/rbac/metrics_cluster_role_binding.yaml
  operator/config/rbac/metrics_role.yaml
  operator/config/rbac/metrics_role_binding.yaml
  operator/controllers/kyma_controller.go
  operator/main.go
Labels: lgtm

#80 fix CheckLabelsAndFinalizers bug
  operator/controllers/kyma_controller.go
  operator/pkg/status/kyma_handler.go
Labels: lgtm

#81 Remove unnecessary test files
  operator/config/samples/.gitignore
  operator/config/samples/component-integration-installed/moduletemplates/example/blobs/sha256:079e0eeb88187349a2dd2584bbce122b4319acb767e1c23a9c49beace26ceda0
  operator/config/samples/component-integration-installed/moduletemplates/example/blobs/sha256:9d37fb366e4371b44c94496f3db276bd6f3a1019c9d44077b689c68ec6486c1e
  operator/config/samples/component-integration-installed/moduletemplates/example/component-descriptor.yaml
  operator/config/samples/component-integration-installed/moduletemplates/generated-module-template.yaml
  operator/config/samples/component-integration-installed/moduletemplates/private-key.pem
  operator/config/samples/component-integration-installed/moduletemplates/public-key-secret.yaml
  operator/config/samples/component-integration-installed/moduletemplates/public-key.pem
  operator/config/samples/component-integration-installed/moduletemplates/remote-component-descriptor-signed.yaml
  operator/config/samples/component-integration-installed/moduletemplates/remote-component-descriptor.yaml
Labels: lgtm, size/L

#75 feat: setup override configuration overrides on kyma level
  .gitignore
  operator/Makefile
  operator/api/v1alpha1/kyma_types.go
  operator/api/v1alpha1/moduletemplate_types.go
  operator/api/v1alpha1/operator_labels.go
  operator/api/v1alpha1/zz_generated.deepcopy.go
  operator/config/crd/bases/operator.kyma-project.io_kymas.yaml
  operator/config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
  operator/config/rbac/role.yaml
  operator/config/samples/component-integration-installed/moduletemplates/generate-module-template.sh
  operator/config/samples/component-integration-installed/operator_v1alpha1_kyma.yaml
  operator/config/samples/component-integration-installed/operator_v1alpha1_moduletemplate_manifest_example-module-name_stable_production_empty.yaml
  operator/config/samples/component-integration-installed/operator_v1alpha1_moduletemplate_manifest_rapid.yaml
  operator/config/samples/component-integration-installed/operator_v1alpha1_moduletemplate_manifest_stable.yaml
  operator/config/samples/component-integration-installed/v1_configmap_nginx_override.yaml
  operator/controllers/kyma_controller.go
  operator/controllers/kyma_controller_test.go
  operator/controllers/setup.go
  operator/controllers/suite_test.go
  operator/controllers/util.go
  operator/main.go
  operator/pkg/dynamic/informers.go
  operator/pkg/img/img_utils.go
  operator/pkg/img/layer.go
  operator/pkg/img/parse.go
  operator/pkg/labels/operator_labels.go
  operator/pkg/ocmextensions/HelmChartRepository.go
  operator/pkg/parsed/module.go
  operator/pkg/parsed/overrides.go
  operator/pkg/parsed/template_to_module.go
  operator/pkg/release/lookup.go
  operator/pkg/remote/client.go
  operator/pkg/remote/kyma_synchronization_context.go
  operator/pkg/signature/verifier.go
  operator/pkg/status/kyma_handler.go
  operator/pkg/util/kyma_util.go
  operator/pkg/watch/component_change.go
  operator/pkg/watch/template_change.go
Labels: lgtm, size/XXL

#73 feat: setup validating webhook for moduletemplate
  operator/PROJECT
  operator/api/v1alpha1/moduletemplate_webhook.go
  operator/api/v1alpha1/webhook_suite_test.go
  operator/config/certmanager/certificate.yaml
  operator/config/certmanager/kustomization.yaml
  operator/config/certmanager/kustomizeconfig.yaml
  operator/config/default/manager_webhook_patch.yaml
  operator/config/default/webhookcainjection_patch.yaml
  operator/config/webhook/kustomization.yaml
  operator/config/webhook/kustomizeconfig.yaml
  operator/config/webhook/manifests.yaml
  operator/config/webhook/service.yaml
  operator/main.go
Labels: lgtm

#82 tests: Upgrade to Gingko 2 and fix tests from Webhooks
  operator/api/v1alpha1/moduletemplate_webhook.go
  operator/api/v1alpha1/webhook_suite_test.go
  operator/controllers/kyma_controller_test.go
  operator/controllers/suite_test.go
  operator/go.mod
Labels: lgtm, size/L

#84 Fix deletion propagation
  operator/api/v1alpha1/operator_labels.go
  operator/config/samples/component-integration-installed/moduletemplates/data/.gitignore
  operator/config/samples/component-integration-installed/moduletemplates/data/config.yaml
  operator/config/samples/component-integration-installed/moduletemplates/generate-module-template.sh
  operator/config/samples/component-integration-installed/v1_configmap_nginx_override.yaml
  operator/config/samples/secret/k3d-secret-gen.sh
  operator/controllers/kyma_controller.go
  operator/controllers/setup.go
  operator/go.mod
  operator/go.sum
  operator/main.go
  operator/pkg/dynamic/informers.go
  operator/pkg/ocmextensions/HelmChartRepository.go
  operator/pkg/parsed/template_to_module.go
  operator/pkg/watch/component_change.go
  operator/pkg/watch/restricted_enqueue_request_for_owner.go
Labels: lgtm, size/XL

#85 Migrated listener dependency
  operator/controllers/setup.go
  operator/go.mod
  operator/go.sum
Labels: lgtm, size/M

#93 Remove Overrides from Kyma CR
  operator/api/v1alpha1/kyma_types.go
  operator/api/v1alpha1/zz_generated.deepcopy.go
  operator/config/crd/bases/operator.kyma-project.io_kymas.yaml
  operator/controllers/kyma_controller.go
  operator/pkg/parsed/overrides.go
Labels: lgtm, size/L

#92 Create CRD State Validation in Validation Webhook
  docs/starting-operator-with-webhooks.md
  operator/Makefile
  operator/api/v1alpha1/moduletemplate_webhook.go
  operator/api/v1alpha1/webhook_crd_test.go
  operator/api/v1alpha1/webhook_suite_test.go
  operator/config/samples/tests/crds/component.kyma-project.io_samplecrd-invalid.yaml
  operator/config/samples/tests/crds/component.kyma-project.io_samplecrd.yaml
  operator/config/samples/tests/moduletemplates/operator_v1alpha1_moduletemplate_manifest_example-module-name_stable_production_samplecrd.yaml
  operator/controllers/kyma_controller.go
  operator/pkg/status/kyma_handler.go
Labels: lgtm, size/L

#94 Poc kyma operator ii refactor module template management
  .gitignore
  operator/.golangci.yaml
  operator/Makefile
  operator/api/v1alpha1/groupversion_info.go
  operator/api/v1alpha1/moduletemplate_types.go
  operator/api/v1alpha1/operator_labels.go
  operator/api/v1alpha1/webhook_crd_test.go
  operator/config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
  operator/config/samples/component-integration-installed/crd/component.kyma-project.io_kcpmodules.yaml
  operator/config/samples/component-integration-installed/crd/component.kyma-project.io_skrmodules.yaml
  operator/config/samples/component-integration-installed/crd/v1/kcpmodule_types.go
  operator/config/samples/component-integration-installed/crd/v1alpha1/kcpmodule_types.go
  operator/config/samples/component-integration-installed/crd/v1alpha1/skrmodule_types.go
  operator/config/samples/component-integration-installed/crd/v1beta1/kcpmodule_types.go
  operator/config/samples/component-integration-installed/crd/v1beta1/skrmodule_types.go
  operator/config/samples/component-integration-installed/moduletemplates/generate-module-template.sh
  operator/config/samples/component-integration-installed/operator_v1alpha1_kyma.yaml
  operator/config/samples/component-integration-installed/operator_v1alpha1_moduletemplate_kcp-module.yaml
  operator/config/samples/component-integration-installed/operator_v1alpha1_moduletemplate_manifest_example-module-name_stable_production_empty.yaml
  operator/config/samples/component-integration-installed/operator_v1alpha1_moduletemplate_skr-module.yaml
  operator/config/samples/tests/moduletemplates/operator_v1alpha1_moduletemplate_manifest_example-module-name_stable_production_samplecrd.yaml
  operator/controllers/kyma_controller.go
  operator/controllers/kyma_controller_test.go
  operator/controllers/suite_test.go
  operator/controllers/util.go
  operator/go.mod
  operator/go.sum
  operator/main.go
  operator/pkg/adapter/eventing_adapter.go
  operator/pkg/client/clientset/versioned/typed/operator.kyma-project.io/v1alpha1/fake/fake_kyma.go
  operator/pkg/client/clientset/versioned/typed/operator.kyma-project.io/v1alpha1/fake/fake_moduletemplate.go
  operator/pkg/img/layer.go
  operator/pkg/parsed/module.go
  operator/pkg/parsed/template_to_module.go
  operator/pkg/release/lookup.go
  operator/pkg/test/util.go
  operator/pkg/watch/template_change.go
Labels: lgtm, size/XXL
