Repository kyma-project/lifecycle-manager, pull requests merged in 2023-06, with the labels that each got.

#637 Remove failing module from status after being deleted from spec.modules
  internal/declarative/v2/reconciler.go
Labels: lgtm, size/S

#648 Update architecture.md
  README.md
  controllers/README.md
  docs/README.md
  docs/assets/lifecycle-manager-architecture.svg
  docs/technical-reference/api/README.md
  docs/technical-reference/architecture.md
  docs/technical-reference/controllers.md
Labels: documentation, lgtm, size/L

#625 Normalize remote Kyma CR name
  api/v1beta2/operator_labels.go
  controllers/control-plane/kcp_controller_helper_test.go
  controllers/control-plane/kcp_controller_remote_sync_test.go
  pkg/remote/kyma_synchronization_context.go
Labels: lgtm, size/M

#646 moduletemplate_types: Add Custom State Check
  api/v1beta1/moduletemplate_conversion.go
  api/v1beta1/moduletemplate_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta2/kyma_types.go
  api/v1beta2/moduletemplate_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_kymas.yaml
  config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
  controllers/moduletemplate_test.go
  go.mod
  go.sum
  pkg/module/sync/runner_impl.go
Labels: lgtm, size/L

#659 Fix flaky tests
  controllers/control-plane/kcp_controller_helper_test.go
  controllers/control-plane/kcp_controller_remote_sync_test.go
  controllers/control-plane/kcp_suite_test.go
Labels: lgtm, size/XS

#661 Provision remote cluster envtest for each test
  controllers/control-plane/kcp_controller_helper_test.go
  controllers/control-plane/kcp_controller_remote_sync_test.go
  controllers/control-plane/kcp_controller_test.go
  controllers/control-plane/kcp_manifest_test.go
  controllers/control-plane/kcp_suite_test.go
Labels: lgtm, size/M

#667 Remove renaming old remote kymas
  controllers/control-plane/kcp_controller_helper_test.go
  controllers/control-plane/kcp_controller_remote_sync_test.go
  controllers/kyma_controller.go
  controllers/moduletemplate_test.go
  pkg/remote/kyma_synchronization_context.go
Labels: lgtm, size/L

#644 add warning state
  api/v1beta2/kyma_types.go
  api/v1beta2/kyma_types_test.go
  config/crd/bases/operator.kyma-project.io_kcpmodules.yaml
  config/crd/bases/operator.kyma-project.io_kymas.yaml
  config/crd/bases/operator.kyma-project.io_manifests.yaml
  config/crd/bases/test.declarative.kyma-project.io_testapis.yaml
  config/samples/component-integration-installed/crd/operator.kyma-project.io_kcpmodules.yaml
  config/samples/component-integration-installed/crd/v1beta1/kcpmodule_types.go
  config/samples/component-integration-installed/crd/v1beta2/kcpmodule_types.go
  config/samples/component-integration-installed/operator_v1beta2_kyma.yaml
  controllers/kyma_controller.go
  controllers/kyma_module_channel_test.go
  internal/declarative/v2/object.go
  internal/declarative/v2/ready_check.go
  internal/declarative/v2/reconciler.go
  internal/manifest/v1beta1/ready_check.go
  internal/manifest/v1beta1/ready_check_test.go
  pkg/module/sync/runner_impl.go
  pkg/status/kyma_helper.go
Labels: lgtm, size/L

#657 Add resourceVersion to moduletemplate cache Key
  api/v1beta2/moduletemplate_types.go
Labels: lgtm, size/XS

#664 api/scheme.go: Remove Unnecessary Conversion Functions
  api/scheme.go
Labels: lgtm, size/S

#670 Refactor parsing logic
  internal/declarative/v2/inmemory_rendered.go
  internal/declarative/v2/reconciler.go
  internal/declarative/v2/renderer.go
  internal/declarative/v2/ssa.go
  internal/manifest/v1beta1/parse.go
  internal/manifest/v1beta1/spec_resolver.go
  internal/manifest/v1beta1/spec_resolver_test.go
  internal/resources.go
  internal/util.go
  internal/util_test.go
  pkg/test_samples/oci/btp-operator-manifest.yaml
  pkg/test_samples/oci/invalid-yaml.yaml
  pkg/test_samples/oci/template-operator-manifest.yaml
  pkg/test_samples/oci/valid-yaml.yaml
  pkg/test_samples/test-config-files/empty-configs.yaml
  pkg/test_samples/test-config-files/empty.yaml
  pkg/test_samples/test-config-files/invalid-configs.yaml
  pkg/test_samples/test-config-files/non-empty-configs.yaml
Labels: lgtm, size/XXL

#651 Increase and add re-queue intervals
  config/control-plane/kustomization.yaml
  controllers/control-plane/kcp_suite_test.go
  controllers/kyma_controller.go
  controllers/moduletemplate_test.go
  controllers/suite_test.go
  flags.go
  main.go
  pkg/testutils/utils.go
Labels: lgtm, size/M

#673 Remove CRD after other resources
  controllers/manifest_controller.go
  internal/declarative/v2/options.go
  internal/declarative/v2/reconciler.go
  internal/declarative/v2/reconciler_test.go
  internal/declarative/v2/test/v1/declarative_test.go
  internal/manifest/v1beta1/custom_resource.go
  internal/manifest/v1beta1/suite_test.go
Labels: lgtm, size/M

#672 Manifest reconciliation Integration test
  internal/declarative/v2/test/v1/declarative_test.go
  internal/declarative/v2/test/v1/helper_test.go
  internal/declarative/v2/test/v1/suite_test.go
  pkg/test_samples/empty-file.yaml
  pkg/test_samples/raw-manifest.yaml
  pkg/test_samples/updated-raw-manifest.yaml
Labels: lgtm, size/XXL

#675 Fix parallel file cache access
  internal/manifest/v1beta1/parse.go
Labels: lgtm, size/S

#592 E2E Suite
  .github/workflows/watcher-e2e.yml
  Makefile
  config/watcher/certificate_setup.yaml
  config/watcher/operator_v1beta2_watcher.yaml
  config/watcher_local_test/kustomization.yaml
  config/watcher_local_test/patches/adjust_resources_for_local_setup.yaml
  config/watcher_local_test/patches/namespace_create.yaml
  config/watcher_local_test/patches/servicemonitor_delete.yaml
  pkg/remote/kyma_synchronization_context.go
  pkg/watcher/certificate.go
  pkg/watcher/certificate_test.go
  pkg/watcher/skr_webhook_manifest_manager.go
  tests/e2e_test/Makefile
  tests/e2e_test/README.md
  tests/e2e_test/suite_test.go
  tests/e2e_test/watcher_test.go
  tests/smoke_test/smoke_test.go
Labels: lgtm, size/XL

#548 Extend watcher CR to include the API Group of watched resource
  Makefile
  api/v1beta2/watcher_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_watchers.yaml
  config/watcher/operator_v1beta2_watcher.yaml
  controllers/setup.go
  controllers/withwatcher/kyma_controller_test.go
  controllers/withwatcher/watcher_controller_helper_test.go
  flags.go
  main.go
  pkg/watcher/skr_webhook_manifest_manager.go
  pkg/watcher/skr_webhook_resources.go
  pkg/watcher/webhook_chart.go
  skr-webhook/resources.yaml
Labels: lgtm, size/L

#676 Recreate Kyma and ModuleTemplate CRDs in SKR after their deletion
  controllers/control-plane/kcp_controller_remote_sync_test.go
  pkg/remote/crd_upgrade.go
  pkg/remote/kyma_synchronization_context.go
  pkg/remote/remote_catalog.go
Labels: lgtm, size/M

#674 Prevent diff resources to be deleted if oci ref not changed
  internal/declarative/v2/inmemory_rendered.go
  internal/declarative/v2/object.go
  internal/declarative/v2/reconciler.go
  internal/declarative/v2/spec.go
  internal/declarative/v2/test/v1/declarative_test.go
  internal/manifest/v1beta1/parse.go
  internal/manifest/v1beta1/paths.go
  internal/manifest/v1beta1/spec_resolver.go
Labels: lgtm, size/L

#655 Introduce cache for KCP CRDs
  controllers/control-plane/kcp_controller_helper_test.go
  controllers/withwatcher/suite_with_watcher_test.go
  internal/declarative/v2/test/v1/declarative_test.go
  main.go
  pkg/cache/crd_cache.go
  pkg/remote/crd_upgrade.go
Labels: lgtm, size/M

#678 Increase client qps and burst
  flags.go
Labels: lgtm, size/XS

#686 Improve integration tests
  api/v1beta2/webhook_moduletemplate_crd_validation_test.go
  controllers/control-plane/kcp_controller_helper_test.go
  controllers/control-plane/kcp_controller_test.go
  controllers/control-plane/kcp_manifest_test.go
  controllers/control-plane/kyma_remote_sync_test.go
  controllers/kyma_controller_helper_test.go
  controllers/kyma_module_channel_test.go
  controllers/kyma_moduleinfo_test.go
  controllers/kyma_test.go
  controllers/manifest_test.go
  controllers/moduletemplate_install_test.go
  controllers/moduletemplate_test.go
  controllers/withwatcher/kyma_controller_test.go
  internal/manifest/v1beta1/parse.go
  pkg/testutils/utils.go
Labels: lgtm, size/XL

#691 Revert #646
  api/v1beta2/kyma_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_kymas.yaml
  controllers/moduletemplate_test.go
  go.mod
  go.sum
  pkg/module/sync/runner_impl.go
Labels: lgtm, size/L

#642 Remove Kyma and Manifest finalizers if no access secret is found and they are being deleted
  controllers/kyma_controller.go
  internal/declarative/v2/reconciler.go
  internal/manifest/v1beta1/client.go
  internal/manifest/v1beta1/custom_resource.go
Labels: lgtm, size/M

#687 Review and update the technical reference documentation in the Lifecycle Manager repo
  docs/technical-reference/api/README.md
  docs/technical-reference/api/kyma-cr.md
  docs/technical-reference/api/manifest-cr.md
  docs/technical-reference/architecture.md
  docs/technical-reference/running-modes.md
Labels: documentation, lgtm, size/S, area/documentation

#697 Update Listener PKG to include latest Bug fix
  go.mod
  go.sum
Labels: lgtm, size/XS
