Repository kyma-project/lifecycle-manager, pull requests merged in 2023-08, with the labels that each got.

#755 Add missing ModuleTemplate test cases
  controllers/kyma_controller/moduletemplate_install_test.go
  internal/declarative/v2/test/v1/declarative_test.go
Labels: lgtm, size/M

#770 Remove flaky module upgrade integration test
  internal/declarative/v2/test/v1/declarative_test.go
  pkg/test_samples/raw-manifest.yaml
  pkg/test_samples/updated-raw-manifest.yaml
Labels: lgtm, size/XXL

#766 Enable type assertion linter
  .github/workflows/pull-lifecycle-mgr-lint.yml
  .golangci.yaml
  api/v1beta1/kyma_conversion.go
  api/v1beta1/manifest_conversion.go
  api/v1beta1/moduletemplate_conversion.go
  api/v1beta1/watcher_conversion.go
  api/v1beta2/error.go
  api/v1beta2/moduletemplate_types.go
  api/v1beta2/moduletemplate_webhook.go
  controllers/control-plane/kcp_controller_helper_test.go
  internal/declarative/v2/cleanup.go
  internal/declarative/v2/client_cache.go
  internal/declarative/v2/reconciler.go
  internal/declarative/v2/reconciler_test.go
  internal/declarative/v2/test/v1/declarative_test.go
  internal/manifest/client.go
  internal/manifest/custom_resource.go
  internal/manifest/parse.go
  internal/manifest/ready_check.go
  internal/manifest/skr_client_lookup.go
  pkg/adapter/eventing_adapter.go
  pkg/cache/crd_cache.go
  pkg/common/error.go
  pkg/img/parse.go
  pkg/istio/client.go
  pkg/module/sync/runner_impl.go
  pkg/remote/client_cache.go
Labels: lgtm, size/L

#777 Fix wrong naming of iterator
  .github/workflows/e2e-test.yml
Labels: lgtm, size/XS

#778 chore: bump cert-manager dependency
  go.mod
  go.sum
Labels: lgtm, size/M

#779 chore: bump more dependencies
  go.mod
  go.sum
Labels: lgtm, size/M

#783 Remove purge finalizer configs from control-plane
  config/control-plane/kustomization.yaml
Labels: lgtm, size/XS

#768 Fix Watcher Landscape Setup
  .github/workflows/e2e-test.yml
  config/watcher/gateway.yaml
  config/watcher/operator_v1beta2_watcher.yaml
  controllers/withwatcher/suite_with_watcher_test.go
  flags.go
  main.go
  pkg/watcher/skr_webhook_manifest_manager.go
  pkg/watcher/webhook_chart.go
Labels: lgtm, size/L

#782 introduce kyma delete to smoke test
  .github/workflows/smoke-test.yml
  tests/smoke_test/smoke_test.go
Labels: lgtm, size/L

#792 fix failed to create webhook chart manager
  controllers/withwatcher/suite_with_watcher_test.go
  main.go
  pkg/watcher/skr_webhook_manifest_manager.go
Labels: lgtm, size/S

#787 Fix ignored error and improper panic
  controllers/kyma_controller.go
  internal/manifest/parse.go
  pkg/channel/lookup.go
  pkg/module/parse/template_to_module.go
  pkg/remote/context.go
  pkg/remote/kyma_synchronization_context.go
  pkg/remote/remote_catalog.go
  pkg/watcher/skr_webhook_manifest_manager.go
Labels: lgtm, size/M

#788 Enable wrapcheck linter & code refactor if needed
  .github/workflows/pull-lifecycle-mgr-lint.yml
  .golangci.yaml
  Makefile
  api/scheme.go
  api/v1beta2/codec.go
  api/v1beta2/kyma_webhook.go
  api/v1beta2/manifest_webhook.go
  api/v1beta2/moduletemplate_types.go
  api/v1beta2/moduletemplate_webhook.go
  api/v1beta2/watcher_webhook.go
  controllers/kyma_controller.go
  controllers/kyma_controller/kyma_test.go
  controllers/manifest_controller.go
  controllers/purge_controller.go
  controllers/setup.go
  controllers/watcher_controller.go
  internal/declarative/v2/client_proxy.go
  internal/declarative/v2/factory.go
  internal/declarative/v2/inmemory_rendered.go
  internal/declarative/v2/kube_factory_proxy.go
  internal/declarative/v2/ready_check.go
  internal/declarative/v2/reconciler.go
  internal/declarative/v2/renderer_raw.go
  internal/declarative/v2/util.go
  internal/manifest/client.go
  internal/manifest/custom_resource.go
  internal/manifest/parse.go
  internal/manifest/ready_check.go
  internal/manifest/skr_client_lookup.go
  internal/manifest/spec_resolver.go
  internal/util.go
  pkg/channel/lookup.go
  pkg/img/layer.go
  pkg/img/parse.go
  pkg/istio/client.go
  pkg/metrics/metrics.go
  pkg/module/parse/template_to_module.go
  pkg/module/sync/runner_impl.go
  pkg/ocmextensions/cred.go
  pkg/remote/client_lookup.go
  pkg/remote/cluster_client.go
  pkg/remote/crd_upgrade.go
  pkg/remote/kyma_synchronization_context.go
  pkg/remote/remote_catalog.go
  pkg/security/san_pinning.go
  pkg/signature/verifier.go
  pkg/testutils/utils.go
  pkg/watch/restricted_enqueue_request_for_owner.go
  pkg/watcher/certificate.go
  pkg/watcher/skr_webhook_manifest_manager.go
  pkg/watcher/skr_webhook_resources.go
  pkg/watcher/webhook_chart.go
Labels: lgtm, size/XL

#797 Fix deployment ready error
  internal/manifest/ready_check.go
Labels: lgtm, size/S

#786 Remove Config Layer Code for Manifest
  api/v1beta2/moduletemplate_types.go
  controllers/kyma_controller/moduletemplate_test.go
  pkg/module/parse/template_to_module.go
Labels: lgtm, size/S

#796 Provide empty resource namespace for cluster scoped modules
  api/v1beta2/operator_annotations.go
  api/v1beta2/webhook_moduletemplate_crd_validation_test.go
  controllers/control-plane/kcp_controller_helper_test.go
  controllers/control-plane/kyma_remote_sync_test.go
  controllers/kyma_controller/kyma_controller_helper_test.go
  controllers/kyma_controller/kyma_module_channel_test.go
  controllers/kyma_controller/kyma_test.go
  controllers/kyma_controller/moduletemplate_install_test.go
  controllers/kyma_controller/moduletemplate_test.go
  pkg/module/sync/runner_impl.go
  pkg/testutils/utils.go
Labels: lgtm, size/L

#795 Feature/#714 watcher cr tests
  controllers/withwatcher/kyma_controller_test.go
  controllers/withwatcher/watcher_certificate_test.go
  controllers/withwatcher/watcher_controller_helper_test.go
  controllers/withwatcher/watcher_controller_test.go
Labels: lgtm, size/L

#808 fix/enhance error handling
  controllers/kyma_controller.go
  controllers/manifest_controller.go
  controllers/purge_controller.go
  controllers/watcher_controller.go
  internal/declarative/v2/reconciler.go
Labels: lgtm, size/S

#807 Fix: nil error during rest mapping
  internal/declarative/v2/util.go
  tests/e2e_test/kyma_deletion_test.go
Labels: lgtm, size/S

#812 revert remove config layer
  pkg/module/parse/template_to_module.go
Labels: lgtm, size/S

#784 new custom state check
  api/v1beta1/moduletemplate_conversion.go
  api/v1beta1/moduletemplate_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta2/moduletemplate_types.go
  api/v1beta2/operator_annotations.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
  controllers/manifest_controller/manifest_controller_helper_test.go
  controllers/manifest_controller/manifest_controller_test.go
  controllers/manifest_controller/ready_check_test.go
  internal/manifest/ready_check.go
  internal/manifest/ready_check_test.go
  pkg/module/parse/template_to_module.go
  pkg/testutils/utils.go
  tests/smoke_test/smoke_test.go
Labels: lgtm, size/XL

#806 Client cache invalidation when remote cluster is unreachable
  controllers/kyma_controller.go
  tests/e2e_test/kyma_deletion_test.go
Labels: lgtm, size/M

#819 Remove all Kyma finalizers when Kyma is under deletion and no secret found
  controllers/kyma_controller.go
Labels: lgtm, size/S

#824 Handle empty config
  api/v1beta2/manifest_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
  pkg/module/parse/template_to_module.go
Labels: lgtm, size/M

#825 Update md codeowners
  CODEOWNERS
Labels: lgtm, size/XS

#823 add customStateCheck into api doc
  docs/technical-reference/api/moduleTemplate-cr.md
  docs/user-tutorials/02-10-manage-module-with-custom-resource-policy.md
Labels: lgtm, size/M

#820 Allow namespace/name for remoteModuleTemplateRef
  pkg/channel/lookup.go
Labels: lgtm, size/XS

#826 upgrade dependency
  go.mod
  go.sum
Labels: lgtm, size/L

#817 Remove TLS config from deployed skr-webhook resources
  controllers/withwatcher/kyma_controller_test.go
  pkg/watcher/skr_webhook_manifest_manager.go
  pkg/watcher/skr_webhook_resources.go
  skr-webhook/resources.yaml
Labels: lgtm, size/M

#828 Expose Listener Metrics
  go.mod
  go.sum
  pkg/metrics/metrics.go
Labels: lgtm, size/XS

#827 Remove watcher cm config
  pkg/watcher/skr_webhook_resources.go
  skr-webhook/resources.yaml
Labels: lgtm, size/M

#835 chore: bump LM deps, linter & small cleanup
  .github/workflows/pull-lifecycle-mgr-lint.yml
  .golangci.yaml
  Makefile
  api/v1beta2/webhook_suite_test.go
  controllers/control-plane/kcp_suite_test.go
  controllers/kyma_controller/suite_test.go
  controllers/manifest_controller/suite_test.go
  controllers/withwatcher/suite_with_watcher_test.go
  go.mod
  go.sum
  pkg/metrics/metrics.go
  tests/e2e_test/suite_test.go
  tests/smoke_test/smoke_test.go
Labels: lgtm, size/L
