Repository kyma-project/lifecycle-manager, pull requests merged in 2023-04, with the labels that each got.

#503 Accepting valid yaml files for the config layer
  internal/manifest/v1beta1/spec_resolver.go
  internal/manifest/v1beta1/spec_resolver_test.go
  pkg/test_samples/test-config-files/empty-configs.yaml
  pkg/test_samples/test-config-files/empty.yaml
  pkg/test_samples/test-config-files/invalid-configs.yaml
  pkg/test_samples/test-config-files/non-empty-configs.yaml
Labels: lgtm, size/L

#494 Fix LM overview dashboard and delete generated ones
  Makefile
  config/grafana/controller-resources-metrics.json
  config/grafana/controller-runtime-metrics.json
  config/grafana/kustomization.yaml
  config/grafana/overview.json
Labels: lgtm, size/XXL

#510 Revisiting TODOs
  internal/declarative/v2/factory.go
Labels: lgtm, size/M

#489 Detect managed kyma
  api/v1beta1/operator_labels.go
  config/control-plane/kustomization.yaml
  controllers/control-plane/control_plane_suite_test.go
  controllers/control-plane/control_plane_test.go
  controllers/kyma_controller.go
  controllers/kyma_controller_test.go
  flags.go
  main.go
  pkg/status/kyma_helper.go
  pkg/testutils/utils.go
Labels: lgtm, size/L

#516 Increase workqueue workers for KCP
  config/control-plane/kustomization.yaml
  flags.go
  main.go
Labels: lgtm, size/M

#527 Update CODEOWNERS
  CODEOWNERS
Labels: lgtm, size/XS

#469 Remove helm chart packaging support for module installation
  config/samples/component-integration-installed/crd/v1beta1/skrmodule_types.go
  config/samples/component-integration-installed/kcp-template-module.yaml
  controllers/kyma_controller.go
  controllers/kyma_controller_helper_test.go
  controllers/kyma_controller_remote_sync_test.go
  controllers/kyma_controller_test.go
  internal/declarative/v2/renderer.go
  internal/declarative/v2/renderer_raw.go
  internal/declarative/v2/renderer_raw_test.go
  internal/manifest/v1beta1/manifest_controller_helper_test.go
  internal/manifest/v1beta1/manifest_controller_test.go
  internal/manifest/v1beta1/parse.go
  internal/manifest/v1beta1/ready_check_test.go
  internal/manifest/v1beta1/spec_resolver.go
  pkg/module/sync/runner_impl.go
  pkg/remote/remote_catalog.go
  pkg/test_samples/oci/rendered.yaml
  pkg/testutils/utils.go
  pkg/watch/restricted_enqueue_request_for_owner.go
  pkg/watcher/webhook_chart.go
Labels: lgtm, size/XXL

#529 Add issues and PR templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/documentation-improvement.md
  .github/ISSUE_TEMPLATE/epic.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/security-vulnerability.md
  .github/pull-request-template.md
Labels: lgtm, size/L

#536 Fix metric label & add status dashboard
  Makefile
  config/control-plane/kustomization.yaml
  config/grafana/kustomization.yaml
  config/grafana/status.json
  controllers/kyma_controller.go
  pkg/metrics/metrics.go
Labels: lgtm, size/L

#517 kyma_controller: Add Kyma CR Conditions Whitelist
  controllers/kyma_controller_test.go
  pkg/status/conditions.go
  pkg/status/conditions_test.go
Labels: lgtm, size/L

#533 Remove last sync annotation
  api/v1beta1/kyma_types.go
  api/v1beta1/moduletemplate_types.go
  api/v1beta1/operator_annotations.go
  pkg/remote/kyma_synchronization_context.go
  pkg/remote/remote_catalog.go
Labels: lgtm, size/M

#535 deploy template operator in smoke test
  .github/workflows/test.yml
  config/samples/component-integration-installed/operator_v1beta1_moduletemplate_kcp-module.yaml
Labels: lgtm, size/M

#549 Add panel for module status to Kyma status dashboard
  config/grafana/status.json
Labels: lgtm, size/L

#551 Fix broken tests
  config/samples/component-integration-installed/operator_v1beta1_moduletemplate_kcp-module.yaml
  controllers/kyma_controller_helper_test.go
  controllers/kyma_controller_remote_sync_test.go
  controllers/kyma_controller_test.go
  controllers/moduletemplate_test.go
  internal/declarative/v2/renderer_raw.go
  internal/manifest/v1beta1/manifest_controller_helper_test.go
  pkg/status/conditions_test.go
Labels: lgtm, size/L

#546 Remove moduletemplates directory
  config/samples/component-integration-installed/moduletemplates/README.md
  config/samples/component-integration-installed/moduletemplates/data/.gitignore
  config/samples/component-integration-installed/moduletemplates/data/config.yaml
  config/samples/component-integration-installed/moduletemplates/generate-module-template.sh
  config/samples/component-integration-installed/moduletemplates/resources.yaml
Labels: lgtm, size/L

#552 Move architecture to a separate doc
  README.md
  docs/README.md
  docs/modularization.md
  docs/technical-reference/api/README.md
  docs/technical-reference/api/kyma-cr.md
  docs/technical-reference/api/manifest-cr.md
  docs/technical-reference/api/moduleTemplate-cr.md
  docs/technical-reference/architecture.md
  docs/technical-reference/running-modes.md
Labels: lgtm, size/XL

#555 Remove admission webhook
  config/control-plane/kustomization.yaml
  config/default/kustomization.yaml
  config/webhook/kustomization.yaml
Labels: lgtm, size/XS

#554 Update registry references
  .github/workflows/test.yml
  config/control-plane/kustomization.yaml
  config/manager/kustomization.yaml
  docs/developer/local-test-setup.md
  skr-webhook/resources.yaml
Labels: lgtm, size/S
