Repository kyma-project/lifecycle-manager, pull requests merged in 2023-07, with the labels that each got.

#696 set sync steps ready conditions to false
  controllers/control-plane/kcp_controller_helper_test.go
  controllers/kyma_controller.go
  controllers/moduletemplate_test.go
  internal/declarative/v2/reconciler.go
  internal/declarative/v2/test/v1/declarative_test.go
  internal/declarative/v2/test/v1/helper_test.go
  main.go
  pkg/remote/crd_upgrade.go
Labels: lgtm, size/M

#705 Enqueue owner instead of watched Resource
  controllers/setup.go
  go.sum
Labels: lgtm, size/S

#710 Get credSecretSelector from install layer instead of optional config layer
  internal/manifest/v1beta1/spec_resolver.go
Labels: lgtm, size/S

#688 Support remote installation of modules in private registries
  api/v1beta2/operator_labels.go
  controllers/control-plane/kyma_remote_sync_test.go
  controllers/kyma_test.go
  controllers/purge/purge_controller_test.go
  docs/developer-tutorials/config-private-registry.md
  docs/technical-reference/api/kyma-cr.md
  internal/declarative/v2/reconciler.go
  internal/declarative/v2/spec.go
  internal/manifest/v1beta1/manifest_controller_test.go
  internal/manifest/v1beta1/spec_resolver.go
  pkg/module/common/module.go
  pkg/module/parse/template_to_module.go
  pkg/test_samples/oci/private-registry-manifest.yaml
  pkg/testutils/utils.go
Labels: lgtm, size/L

#711 Update config-priv-reg tutorial
  docs/developer-tutorials/config-private-registry.md
Labels: lgtm, size/XS

#716 introduce component descriptor cache
  api/v1beta2/moduletemplate_types.go
  api/v1beta2/moduletemplate_webhook.go
  api/v1beta2/webhook_moduletemplate_crd_validation_test.go
  config/load_test/kustomization.yaml
  config/load_test/manager_webhook_patch.yaml
  config/load_test/webhookcainjection_patch.yaml
  controllers/kyma_controller_helper_test.go
  controllers/setup.go
  internal/manifest/v1beta1/manifest_controller_test.go
  internal/manifest/v1beta1/spec_resolver.go
  pkg/channel/lookup.go
  pkg/module/parse/template_to_module.go
  pkg/testutils/utils.go
Labels: lgtm, size/L

#719 Remove control-plane patches to be moved to management-plane-config
  .github/workflows/test.yml
  config/control-plane/kustomization.yaml
Labels: lgtm, size/S

#721 Fix: skr-webhook sidecar alpine image from internal registry that is signed
  skr-webhook/resources.yaml
Labels: lgtm, size/XS

#698 User tutorials update
  docs/assets/kyma-module-template-structure.svg
  docs/modularization.md
  docs/user-tutorials/01-10-control-plane-quick-start.md
  docs/user-tutorials/02-10-manage-module-with-custom-resource-policy.md
  docs/user-tutorials/manage-module-with-custom-resource-policy.md
  docs/user-tutorials/quick-start.md
Labels: documentation, lgtm, size/L

#725 reduce kyma workers
  config/control-plane/kustomization.yaml
Labels: lgtm, size/XS

#728 Unregister histogram metrics with high cardinality
  pkg/metrics/metrics.go
Labels: lgtm, size/M

#727 Remove control plane max worker patch
  config/control-plane/kustomization.yaml
  config/default/kustomization.yaml
  flags.go
Labels: lgtm, size/S

#722 Update developer tutorials
  docs/README.md
  docs/developer-tutorials/config-private-registry.md
  docs/developer-tutorials/local-test-setup.md
  docs/developer-tutorials/prepare-gcr-registry.md
  docs/developer-tutorials/provision-cluster-and-registry.md
  docs/developer-tutorials/starting-operator-with-webhooks.md
Labels: lgtm, size/M

#718 Enable purge finalizer and adding CRDs to be skipped
  config/control-plane/kustomization.yaml
Labels: lgtm, size/XS

#723 Fix installation of a Module generated using `sha256` OCM Name Mapping
  flags.go
  pkg/img/parse.go
Labels: lgtm, size/S

#732 remove cpu limit
  config/control-plane/patches/adjust_resources_in_deployment.yaml
  config/load_test/patches/adjust_resources_in_deployment.yaml
  config/manager/manager.yaml
Labels: lgtm, size/XS

#731 Testing SKR Kyma recreation when it gets deleted
  controllers/control-plane/kcp_controller_helper_test.go
  controllers/control-plane/kyma_remote_sync_test.go
  flags.go
Labels: lgtm, size/M

#737 Introduce working e2e test for GH Actions [WATCHER]
  .github/workflows/e2e-test.yml
  .github/workflows/smoke-test.yml
  .github/workflows/watcher-e2e.yml
  config/watcher_local_test/kustomization.yaml
  docs/developer-tutorials/local-test-setup.md
  tests/e2e_test/Makefile
  tests/e2e_test/watcher_test.go
Labels: lgtm, size/L

#736 Add missing kyma tests
  controllers/control-plane/kyma_remote_sync_test.go
  controllers/kyma_controller_helper_test.go
  controllers/kyma_module_channel_test.go
  controllers/kyma_test.go
Labels: lgtm, size/L

#742 Disable Manifest Watcher
  config/watcher/operator_v1beta2_watcher.yaml
Labels: lgtm, size/M

#747 fix watcher e2e
  .github/workflows/e2e-test.yml
  config/watcher_local_test/kustomization.yaml
  controllers/kyma_test.go
  internal/util.go
  pkg/testutils/utils.go
  tests/e2e_test/Makefile
  tests/e2e_test/suite_test.go
  tests/e2e_test/watcher_test.go
Labels: lgtm, size/L

#749 linter fix: increase timeout and remove concurrency
  .golangci.yaml
Labels: lgtm, size/XS

#743 Make KCP-Gateway-HTTPS port configurable; incl minor changes
  config/watcher_local_test/kustomization.yaml
  controllers/withwatcher/kyma_controller_test.go
  controllers/withwatcher/suite_with_watcher_test.go
  controllers/withwatcher/watcher_controller_helper_test.go
  flags.go
  main.go
  pkg/testutils/utils.go
  pkg/watcher/skr_webhook_manifest_manager.go
  pkg/watcher/webhook_chart.go
  skr-webhook/resources.yaml
Labels: lgtm, size/L

#729 upgrade runtime controller to 0.15
  api/v1beta2/moduletemplate_webhook.go
  controllers/control-plane/kcp_controller_helper_test.go
  controllers/control-plane/kcp_suite_test.go
  controllers/control-plane/kyma_remote_sync_test.go
  controllers/kyma_controller.go
  controllers/kyma_controller_helper_test.go
  controllers/kyma_test.go
  controllers/manifest_controller.go
  controllers/purge/suite_test.go
  controllers/setup.go
  controllers/suite_test.go
  controllers/util.go
  controllers/watcher_controller.go
  controllers/withwatcher/kyma_controller_test.go
  controllers/withwatcher/suite_with_watcher_test.go
  controllers/withwatcher/watcher_controller_test.go
  go.mod
  go.sum
  internal/declarative/v2/cleanup.go
  internal/declarative/v2/client_proxy.go
  internal/declarative/v2/kube_factory_proxy.go
  internal/declarative/v2/test/v1/declarative_test.go
  internal/declarative/v2/test/v1/helper_test.go
  internal/manifest/v1beta1/custom_resource.go
  internal/manifest/v1beta1/manifest_controller_helper_test.go
  internal/manifest/v1beta1/suite_test.go
  internal/util.go
  main.go
  pkg/metrics/metrics.go
  pkg/module/sync/runner_impl.go
  pkg/remote/crd_upgrade.go
  pkg/remote/kyma_synchronization_context.go
  pkg/remote/remote_catalog.go
  pkg/testutils/utils.go
  pkg/util/error.go
  pkg/watch/restricted_enqueue_request_for_owner.go
  pkg/watch/template_change.go
  pkg/watcher/certificate.go
  pkg/watcher/skr_webhook_manifest_manager.go
  tests/e2e_test/watcher_test.go
Labels: lgtm, size/XL

#754 set default max worker to 1 and fix smoke test
  config/default/kustomization.yaml
  controllers/control-plane/kcp_controller_test.go
  controllers/control-plane/kcp_manifest_test.go
  controllers/kyma_moduleinfo_test.go
  controllers/manifest_test.go
  flags.go
  tests/smoke_test/module_upgrade/moduletemplate_template_operator_fast.yaml
Labels: lgtm, size/L

#757 increase wait for image build timeout
  .github/workflows/e2e-test.yml
  .github/workflows/smoke-test.yml
Labels: lgtm, size/XS

#758 stop upgrade ubuntu every time for e2e test
  .github/workflows/e2e-test.yml
Labels: lgtm, size/XS

#713 Refactoring ready check state handling and integeration test package
  api/v1beta2/manifest_types.go
  config/control-plane/kustomization.yaml
  config/crd/bases/operator.kyma-project.io_skrmodule2s.yaml
  config/crd/bases/operator.kyma-project.io_skrmodules.yaml
  controllers/control-plane/kcp_controller_helper_test.go
  controllers/control-plane/kyma_remote_sync_test.go
  controllers/kyma_controller/kyma_controller_helper_test.go
  controllers/kyma_controller/kyma_module_channel_test.go
  controllers/kyma_controller/kyma_moduleinfo_test.go
  controllers/kyma_controller/kyma_test.go
  controllers/kyma_controller/manifest_test.go
  controllers/kyma_controller/moduletemplate_install_test.go
  controllers/kyma_controller/moduletemplate_test.go
  controllers/kyma_controller/suite_test.go
  controllers/manifest_controller.go
  controllers/manifest_controller/keychain_test.go
  controllers/manifest_controller/manifest_controller_helper_test.go
  controllers/manifest_controller/manifest_controller_test.go
  controllers/manifest_controller/ready_check_test.go
  controllers/manifest_controller/suite_test.go
  internal/declarative/v2/object.go
  internal/declarative/v2/ready_check.go
  internal/declarative/v2/reconciler.go
  internal/declarative/v2/test/v1/declarative_test.go
  internal/manifest/client.go
  internal/manifest/custom_resource.go
  internal/manifest/parse.go
  internal/manifest/ready_check.go
  internal/manifest/skr_client_lookup.go
  internal/manifest/spec_resolver.go
  internal/manifest/v1beta1/manifest_controller_test.go
  internal/manifest/v1beta1/ready_check.go
  pkg/img/layer.go
  pkg/img/parse.go
  pkg/module/parse/template_to_module.go
  pkg/test_samples/oci/private-registry-manifest.yaml
  tests/e2e_test/suite_test.go
Labels: lgtm, size/XXL

#764 Add Github Actions lint workflow
  .github/workflows/pull-lifecycle-mgr-lint.yml
  .golangci.yaml
  Makefile
  controllers/control-plane/kcp_manifest_test.go
  controllers/kyma_controller.go
  controllers/kyma_controller/kyma_module_channel_test.go
  controllers/kyma_controller/manifest_test.go
  internal/declarative/v2/object.go
  internal/declarative/v2/reconciler.go
  internal/manifest/ready_check.go
  tests/e2e_test/watcher_test.go
Labels: lgtm, size/M
