Repository kyma-project/lifecycle-manager, pull requests merged in 2023-05, with the labels that each got.

#485 Cascade delete control loop
  api/v1beta1/operator_labels.go
  controllers/kyma_controller.go
  controllers/purge/purge_controller_helper_test.go
  controllers/purge/purge_controller_test.go
  controllers/purge/suite_test.go
  controllers/purge_controller.go
  controllers/setup.go
  flags.go
  main.go
Labels: lgtm, size/XL, area/installation

#568 Change v1beta to v1beta2 Watcher kustomize
  config/watcher_local_test/kustomization.yaml
Labels: lgtm, size/XS

#569 Change conversion webhook
  api/v1beta1/kyma_conversion.go
Labels: lgtm, size/XS

#572 add v1alpha1 to schema
  api/scheme.go
Labels: lgtm, size/M

#573 fix condition
  controllers/kyma_controller.go
  pkg/status/conditions.go
Labels: lgtm, size/M

#577 Fix remote kyma creating again after deleted
  config/control-plane/kustomization.yaml
  controllers/kyma_controller.go
  pkg/remote/kyma_synchronization_context.go
Labels: lgtm, size/S

#563 Filter out namespace kyma-system in declarative reconciler
  internal/declarative/v2/default_transforms_test.go
  internal/declarative/v2/reconciler.go
  internal/declarative/v2/reconciler_test.go
Labels: lgtm, size/M

#581 increase cpu limit to 4000 for control plane
  config/control-plane/patches/adjust_resources_in_deployment.yaml
Labels: lgtm, size/XS

#580 Add global flag for target sync namespace
  controllers/control-plane/control_plane_suite_test.go
  controllers/kyma_controller.go
  controllers/kyma_controller_helper_test.go
  controllers/kyma_controller_remote_sync_test.go
  controllers/kyma_controller_test.go
  controllers/suite_test.go
  controllers/withwatcher/suite_with_watcher_test.go
  flags.go
  main.go
  pkg/module/parse/template_to_module.go
  pkg/remote/context.go
  pkg/remote/kyma_synchronization_context.go
  pkg/remote/remote_catalog.go
  pkg/watcher/skr_webhook_manifest_manager.go
  pkg/watcher/webhook_chart.go
Labels: lgtm, size/L

#584 set deleted kyma log to debug level
  controllers/kyma_controller.go
Labels: lgtm, size/XS

#594 Fix overview dashboard panel
  config/grafana/overview.json
Labels: lgtm, size/XS

#593 add kyma module duplicate into validation webhook
  .golangci.yaml
  PROJECT
  api/v1beta2/kyma_webhook.go
  api/v1beta2/kyma_webhook_test.go
  api/v1beta2/moduletemplate_webhook.go
  api/v1beta2/moduletemplate_webhook_test.go
  api/v1beta2/webhook_kyma_crd_validation_test.go
  api/v1beta2/webhook_moduletemplate_crd_validation_test.go
  api/v1beta2/webhook_suite_test.go
  config/control-plane/kustomization.yaml
  config/webhook/manifests.yaml
  go.mod
  go.sum
Labels: lgtm, size/XL

#600 add rate limiter to manifest
  main.go
Labels: lgtm, size/XS

#588 fix module template update check
  api/v1beta2/moduletemplate_webhook.go
  api/v1beta2/moduletemplate_webhook_test.go
  controllers/kyma_module_channel_test.go
  pkg/channel/lookup.go
  pkg/module/parse/template_to_module.go
  pkg/module/sync/runner_impl.go
  pkg/testutils/utils.go
Labels: lgtm, size/L

#590 Remove v1alpha1 from stored versions
  main.go
Labels: lgtm, size/M

#602 Add more info logs for removing storedVersions
  main.go
Labels: lgtm, size/XS

#603 Add RBAC access to update CRD status
  config/rbac/role.yaml
  controllers/kyma_controller.go
  main.go
Labels: lgtm, size/S

#587 Remove module template managed-by label
  api/v1beta2/operator_labels.go
  config/samples/component-integration-installed/operator_v1beta2_moduletemplate_kcp-module-cred-label.yaml
  config/samples/component-integration-installed/operator_v1beta2_moduletemplate_kcp-module.yaml
  controllers/util.go
  go.mod
  go.sum
  main.go
  pkg/testutils/utils.go
  pkg/watch/template_change.go
Labels: lgtm, size/XL

#532 Allow each module template have it's own signature
  controllers/kyma_controller.go
  flags.go
  main.go
  pkg/module/parse/template_to_module.go
  pkg/signature/verifier.go
Labels: lgtm, size/L

#611 Validate unique modules in kyma spec
  api/v1beta2/kyma_types.go
  api/v1beta2/webhook_kyma_crd_validation_test.go
  config/crd/bases/operator.kyma-project.io_kymas.yaml
Labels: lgtm, size/M

#606 Update API version documentation
  docs/technical-reference/api/README.md
  docs/technical-reference/api/changelog.md
  docs/technical-reference/api/kyma-cr.md
  docs/technical-reference/api/moduleTemplate-cr.md
  docs/technical-reference/running-modes.md
Labels: documentation, lgtm, size/L, do-not-merge/missing-docs-review

#564 Detect differences between KCP and SKR CRDs if they have the same version
  controllers/kyma_controller.go
  pkg/remote/crd_upgrade.go
  pkg/remote/crd_upgrade_test.go
  pkg/remote/kyma_synchronization_context.go
Labels: lgtm, size/L

#628 Increase kyma worker
  config/control-plane/kustomization.yaml
Labels: lgtm, size/XS

#630 Remove metrics upon CR deletion
  controllers/kyma_controller.go
  controllers/purge_controller.go
  pkg/metrics/metrics.go
  pkg/module/sync/runner_impl.go
  pkg/status/kyma_helper.go
Labels: lgtm, size/L

#633 Integration test for CRDs Annotations Update in KCP Kyma CR
  controllers/control-plane/kcp_controller_helper_test.go
  controllers/control-plane/kcp_controller_remote_sync_test.go
Labels: lgtm, size/L

#621 Fix invalid remote kyma status sync
  config/watcher_local_test/kustomization.yaml
  controllers/control-plane/kcp_controller_helper_test.go
  controllers/control-plane/kcp_controller_remote_sync_test.go
  controllers/kyma_controller.go
  pkg/remote/kyma_synchronization_context.go
  pkg/remote/kyma_synchronization_context_test.go
Labels: kind/bug, lgtm, size/L, area/installation

#619 Reintroduce is-kyma-managed flag to detect managed Kyma
  config/control-plane/kustomization.yaml
  controllers/control-plane/kcp_suite_test.go
  controllers/kyma_controller.go
  flags.go
  main.go
Labels: lgtm, size/S

#635 Improve channel skew message
  pkg/channel/lookup.go
Labels: lgtm, size/XS
