Repository kyma-project/lifecycle-manager, pull requests merged in 2023-12, with the labels that each got.

#1099 chore: GH form for Q&A discussion category
  .github/DISCUSSION_TEMPLATE/q-a.yml
Labels: lgtm, size/M, cla: yes

#1103 chore: Save CA Certificate value instead of pointer in cache
  pkg/watcher/certificate.go
  pkg/watcher/certificate_cache.go
  pkg/watcher/skr_webhook_manifest_manager.go
Labels: lgtm, size/M, cla: yes

#1088 feat: Detect Watcher certificate not renew
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/workflows/test-e2e.yml
  cmd/flags.go
  cmd/main.go
  internal/controller/kyma_controller.go
  internal/controller/watcher_controller.go
  internal/pkg/metrics/common.go
  internal/pkg/metrics/kyma.go
  internal/pkg/metrics/purge.go
  internal/pkg/metrics/watcher.go
  pkg/testutils/deployment.go
  pkg/testutils/metrics.go
  pkg/watcher/ca_certificate_cache.go
  pkg/watcher/certificate_manager.go
  pkg/watcher/gateway.go
  pkg/watcher/skr_webhook_manifest_manager.go
  pkg/watcher/skr_webhook_resources.go
  pkg/watcher/webhook_chart.go
  tests/e2e_test/Makefile
  tests/e2e_test/self_signed_certificate_rotation_test.go
  tests/e2e_test/utils_test.go
  tests/integration/controller/controlplane/kyma_remote_sync_test.go
  tests/integration/controller/withwatcher/suite_with_watcher_test.go
  tests/integration/declarative/declarative_test.go
  tests/integration/security/san_pinning_test.go
  tests/integration/watcher/certificate_test.go
Labels: lgtm, size/XXL, cla: yes

#1094 chore(metrics, report): Add a GitHub Action to generate a go package metrics report
  .github/workflows/report-package-metrics.yml
Labels: lgtm, size/M, cla: yes

#1111 chore: Update the discussion template bool values
  .github/DISCUSSION_TEMPLATE/q-a.yml
Labels: lgtm, size/XS, cla: yes

#1121 chore(report): Fix the package metrics report GH Action
  .github/workflows/report-package-metrics.yml
Labels: lgtm, size/XS, cla: yes

#1122 feat: Introduce version to manifest CR
  api/v1beta2/manifest_types.go
  config/crd/bases/operator.kyma-project.io_manifests.yaml
  pkg/module/common/module.go
  pkg/module/parse/template_to_module.go
  pkg/module/sync/runner.go
  tests/integration/controller/kyma/kyma_test.go
  tests/integration/controller/kyma/manifest_test.go
Labels: lgtm, size/L, cla: yes

#1132 deps: Bump watcher image version to 0.0.2 release
  config/watcher/kustomization.yaml
Labels: lgtm, size/XS, cla: yes

#1135 fix: Module version annotation
  api/v1beta2/label_annotations_test.go
  api/v1beta2/operator_annotations.go
Labels: lgtm, size/M, cla: yes

#1128 chore: Make Lifecycle manager api a module
  .golangci.yaml
  Dockerfile
  api/go.mod
  api/go.sum
  go.mod
  internal/tests/api/kyma_types_test.go
  internal/tests/api/label_annotations_test.go
  internal/tests/api/modulesync_test.go
  internal/tests/api/moduletemplate_types_test.go
  internal/tests/api/moduletemplate_webhook_test.go
Labels: lgtm, size/XXL, cla: yes

#1139 chore: Adds an external dependency
  internal/pkg/metrics/common.go
Labels: lgtm, size/XS, cla: yes

#1149 chore: Reverts the unnecessary dependency used to test the package report
  internal/pkg/metrics/common.go
Labels: lgtm, size/XS, cla: yes

#1147 feat: Add dropStoredVersion flag
  cmd/flags.go
  cmd/main.go
Labels: lgtm, size/XS, cla: yes

#1157 fix: Pass drop version as arg to eliminate race condition
  cmd/main.go
Labels: lgtm, size/S, cla: yes

#1159 feat: Move EnableLabelValue and DisableLabelValue
  api/shared/operator_labels.go
  api/v1beta1/kyma_conversion.go
  api/v1beta2/kyma_types.go
  api/v1beta2/moduletemplate_types.go
  internal/manifest/spec_resolver.go
  pkg/module/sync/runner.go
  pkg/status/conditions_test.go
  pkg/testutils/kyma.go
  tests/integration/controller/controlplane/kcp_controller_test.go
  tests/integration/controller/controlplane/kcp_manifest_test.go
  tests/integration/controller/controlplane/kyma_remote_sync_test.go
  tests/integration/controller/kyma/kyma_test.go
  tests/integration/controller/kyma/moduletemplate_install_test.go
Labels: lgtm, size/M, cla: yes

#1162 chore: Set v1beta2 as storage version
  api/v1beta1/kyma_types.go
  api/v1beta1/manifest_types.go
  api/v1beta1/moduletemplate_types.go
  api/v1beta1/watcher_types.go
  api/v1beta2/kyma_types.go
  api/v1beta2/manifest_types.go
  api/v1beta2/moduletemplate_types.go
  api/v1beta2/watcher_types.go
  config/crd/bases/operator.kyma-project.io_kymas.yaml
  config/crd/bases/operator.kyma-project.io_manifests.yaml
  config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
  config/crd/bases/operator.kyma-project.io_watchers.yaml
Labels: lgtm, size/S, cla: yes

#1160 fix: Cache all secret instead of depends on label
  .github/workflows/lint-golangci.yml
  .github/workflows/test-e2e.yml
  .github/workflows/test-smoke.yml
  .github/workflows/test-unit.yml
  cmd/main.go
  internal/controller/util.go
  internal/util.go
  pkg/testutils/manifest.go
  tests/e2e_test/utils_test.go
  tests/integration/controller/controlplane/kcp_suite_test.go
  tests/integration/controller/eventfilters/suite_test.go
  tests/integration/controller/kyma/suite_test.go
  tests/integration/controller/manifest/custom_resource_check/suite_test.go
  tests/integration/controller/manifest/suite_test.go
  tests/integration/controller/purge/suite_test.go
  tests/integration/controller/withwatcher/suite_with_watcher_test.go
Labels: lgtm, size/M, cla: yes

#1172 fix: Delete SKR Certificate and Secret only if they exist
  pkg/watcher/certificate_manager.go
Labels: lgtm, size/S, cla: yes

#1176 chore: Bump watcher image to 0.0.4
  config/watcher/kustomization.yaml
Labels: lgtm, size/XS, cla: yes

#1174 fix: Make sure ssa not update resourceVersion
  .github/workflows/report-acceptance-criteria.yml
  .github/workflows/test-e2e.yml
  .golangci.yaml
  config/watcher_local_test/kustomization.yaml
  internal/declarative/v2/ssa.go
  pkg/testutils/deployment.go
  pkg/testutils/manifest.go
  pkg/testutils/modulecr.go
  pkg/testutils/unstructured.go
  pkg/testutils/utils.go
  tests/e2e/Makefile
  tests/e2e/README.md
  tests/e2e/ca_certificate_rotation_test.go
  tests/e2e/kyma_deletion_test.go
  tests/e2e/kyma_metrics_test.go
  tests/e2e/manifest_reconciliation_test.go
  tests/e2e/module_consistency_test.go
  tests/e2e/module_deletion_test.go
  tests/e2e/module_deletion_upgrade_test.go
  tests/e2e/module_upgrade_test.go
  tests/e2e/no_default_cr_test.go
  tests/e2e/purge_controller_test.go
  tests/e2e/purge_metrics_test.go
  tests/e2e/self_signed_certificate_rotation_test.go
  tests/e2e/suite_test.go
  tests/e2e/utils_test.go
  tests/e2e/warning_status_propagation_test.go
  tests/e2e/watcher_test.go
  tests/integration/controller/kyma/manifest_test.go
Labels: lgtm, size/L, cla: yes

#1179 feat: Add panels for new skr-webhook metrics
  config/grafana/overview.json
Labels: lgtm, size/XL, cla: yes

#1180 feat: Add certificate panel
  config/grafana/overview.json
Labels: lgtm, size/L, cla: yes

#1188 fix: Set watcher version to last known working
  config/watcher/kustomization.yaml
  config/watcher_local_test/kustomization.yaml
Labels: lgtm, size/XS, cla: yes

#1171 feat: Safe background Kyma deletion
  .github/workflows/test-e2e.yml
  internal/controller/kyma_controller.go
  pkg/remote/kyma_synchronization_context.go
  pkg/testutils/kyma.go
  pkg/testutils/manifest.go
  tests/e2e/Makefile
  tests/e2e/deletion_test.go
  tests/e2e/kyma_deletion_background_test.go
  tests/e2e/kyma_deletion_foreground_test.go
  tests/e2e/purge_controller_test.go
  tests/e2e/purge_metrics_test.go
Labels: lgtm, size/L, cla: yes

#1192 feat: Kyma requeue reason metrics
  internal/controller/kyma_controller.go
  internal/pkg/metrics/kyma.go
  pkg/testutils/metrics.go
  tests/e2e/kyma_metrics_test.go
Labels: lgtm, size/M, cla: yes

#1193 fix: Bump cli-runtime to 0.29.0
  go.mod
  go.sum
  internal/declarative/v2/factory.go
  internal/declarative/v2/kube_factory_proxy.go
Labels: lgtm, size/L, cla: yes

#1199 fix: Delete remote client cache not only due to limited connection error
  internal/controller/kyma_controller.go
  pkg/util/error.go
Labels: lgtm, size/S, cla: yes

#1197 feat: Add kyma requeue reasons metrics to panel
  config/grafana/overview.json
Labels: lgtm, size/L, cla: yes

#1190 chore(report): Adjusts the "Sprint Commits Test Suites" report to report E2E and Integration tests separately
  .github/workflows/report-sprint-commits.yml
Labels: lgtm, size/XS, cla: yes

#1201 chore: Give each controller a specific name
  cmd/main.go
  internal/controller/manifest_controller.go
  internal/controller/setup.go
  internal/pkg/metrics/kyma.go
Labels: lgtm, size/S, cla: yes

#1206 fix: Stop requeue kyma not deleted for purge controller
  internal/controller/purge_controller.go
Labels: lgtm, size/XS, cla: yes

#1204 chore: Update Lifecycle Manager Controller Runtime Reconcile Success panel
  config/grafana/overview.json
Labels: lgtm, size/M, cla: yes

#1195 feat: Add watcher img registry flag
  cmd/flags.go
  cmd/main.go
  config/watcher/kustomization.yaml
  pkg/watcher/skr_webhook_resources.go
Labels: lgtm, size/L, cla: yes

#1209 fix: Do eventual check before constistent in e2e test
  tests/e2e/module_deletion_test.go
Labels: lgtm, size/XS, cla: yes

#1173 feat: Mandatory modules
  .golangci.yaml
  cmd/flags.go
  cmd/main.go
  go.mod
  go.sum
  internal/controller/kyma_controller.go
  internal/controller/mandatory_modules_controller.go
  internal/controller/setup.go
  pkg/module/common/module.go
  pkg/module/parse/template_to_module.go
  pkg/module/sync/runner.go
  pkg/templatelookup/mandatory.go
  pkg/templatelookup/regular.go
  pkg/testutils/builder/moduletemplate.go
  pkg/testutils/moduletemplate.go
  pkg/watch/mandatory_template_change.go
  pkg/watch/template_change.go
  tests/integration/controller/controlplane/kyma_remote_sync_test.go
  tests/integration/controller/kyma/helper_test.go
  tests/integration/controller/kyma/kyma_test.go
  tests/integration/controller/mandatorymodules/mandatory_modules_controller_test.go
  tests/integration/controller/mandatorymodules/suite_test.go
Labels: lgtm, size/XXL, cla: yes

#1210 chore: bump github.com/open-component-model/ocm from 0.4.0 to 0.5.0
  go.mod
  go.sum
  pkg/testutils/builder/moduletemplate.go
  tests/integration/apiwebhook/webhook_moduletemplate_crd_validation_test.go
  tests/integration/controller/kyma/kyma_module_channel_test.go
  tests/integration/controller/kyma/manifest_test.go
Labels: lgtm, size/S, cla: yes
