Repository kyma-project/lifecycle-manager, pull requests merged in 2023-01, with the labels that each got.

#339 Istio overrides kcp gateway setup
  config/control-plane/certificate_for_watcher_gateway.yaml
  config/control-plane/kustomization.yaml
  config/control-plane/patches/enable_webhook_in_moduletemplate_crd.yaml
  config/control-plane/patches/watcher_gateway_patch.yaml
Labels: lgtm, size/M

#342 remove watcher related resources in control-plane config
  config/control-plane/kustomization.yaml
  config/control-plane/patches/watcher_gateway_patch.yaml
  config/istio/kustomization.yaml
  config/watcher/certificate_for_watcher_gateway.yaml
  config/watcher/gateway.yaml
  config/watcher/kustomization.yaml
Labels: lgtm, size/M

#329 enable watcher local testing using k3d
  Makefile
  config/samples/component-integration-installed/v1_secret_remote_cluster_access.yaml
  config/watcher/operator_v1alpha1_watcher.yaml
  config/watcher_local_test/kustomization.yaml
  config/watcher_local_test/patch.yaml
  controllers/withwatcher/kyma_controller_test.go
  controllers/withwatcher/suite_with_watcher_test.go
  controllers/withwatcher/watcher_controller_test.go
  docs/developer/watcher-local-test.md
  flags.go
  main.go
  pkg/deploy/chart_manager.go
  pkg/deploy/webhook_chart.go
  pkg/istio/client.go
  skr-webhook/templates/deployment.yaml
  skr-webhook/templates/secret.yaml
  skr-webhook/values.yaml
Labels: lgtm, size/L

#347 chore: concurrent Server Side Apply for catalog sync
  pkg/catalog/remote_catalog.go
Labels: lgtm, size/M

#349 chore: remove legacy lister/informer/client gen and files
  Makefile
  go.mod
  go.sum
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/operator.kyma-project.io/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/operator.kyma-project.io/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/operator.kyma-project.io/v1alpha1/fake/fake_kyma.go
  pkg/client/clientset/versioned/typed/operator.kyma-project.io/v1alpha1/fake/fake_moduletemplate.go
  pkg/client/clientset/versioned/typed/operator.kyma-project.io/v1alpha1/fake/fake_operator.kyma-project.io_client.go
  pkg/client/clientset/versioned/typed/operator.kyma-project.io/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/operator.kyma-project.io/v1alpha1/kyma.go
  pkg/client/clientset/versioned/typed/operator.kyma-project.io/v1alpha1/moduletemplate.go
  pkg/client/clientset/versioned/typed/operator.kyma-project.io/v1alpha1/operator.kyma-project.io_client.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/informers/externalversions/operator.kyma-project.io/interface.go
  pkg/client/informers/externalversions/operator.kyma-project.io/v1alpha1/interface.go
  pkg/client/informers/externalversions/operator.kyma-project.io/v1alpha1/kyma.go
  pkg/client/informers/externalversions/operator.kyma-project.io/v1alpha1/moduletemplate.go
  pkg/client/listers/operator.kyma-project.io/v1alpha1/expansion_generated.go
  pkg/client/listers/operator.kyma-project.io/v1alpha1/kyma.go
  pkg/client/listers/operator.kyma-project.io/v1alpha1/moduletemplate.go
Labels: lgtm, size/XXL

#348 parse OCIRegistryCredLabel from descriptor resources.
  api/v1alpha1/operator_labels.go
  config/load_test/kustomization.yaml
  config/samples/component-integration-installed/operator_v1alpha1_moduletemplate_skr-module.yaml
  config/samples/component-integration-installed/operator_v1alpha1_moduletemplate_skr-module2.yaml
  controllers/moduletemplate_test.go
  go.mod
  go.sum
  pkg/img/layer.go
  pkg/img/parse.go
  pkg/module/parse/template_to_module.go
  pkg/testutils/utils.go
Labels: lgtm, size/XL

#350 feat: introduce unified client and skr rate limit override
  controllers/kyma_controller.go
  controllers/suite_test.go
  controllers/withwatcher/suite_with_watcher_test.go
  pkg/deploy/chart_manager.go
  pkg/deploy/webhook_chart.go
  pkg/remote/client.go
  pkg/remote/client_cache.go
  pkg/remote/client_lookup.go
  pkg/remote/cluster_client.go
  pkg/remote/context.go
  pkg/remote/kyma_synchronization_context.go
Labels: lgtm, size/L

#351 fix: catalog accidental delete of runtime templates due to legacy diff calculation
  pkg/catalog/remote_catalog.go
Labels: lgtm, size/L

#354 config json annotation for OCI structs, omit empty field automatically.
  pkg/img/layer.go
  pkg/img/parse.go
  pkg/module/parse/template_to_module.go
Labels: lgtm, size/M

#355 Add removed files which is needed for two cluster setups
  config/samples/component-integration-installed/component-integration-installed/operator_v1alpha1_moduletemplate_skr-module.yaml
Labels: lgtm, size/M

#356 Implement a shared method to marchal oci and helm install content
  pkg/img/layer.go
  pkg/module/parse/template_to_module.go
Labels: lgtm, size/M

#357 Move SKR Template one dir up
  config/samples/component-integration-installed/operator_v1alpha1_moduletemplate_skr-module.yaml
Labels: lgtm, size/XS

#352 add Provide credential for private OCI registry authentication guide
  docs/user/config-private-registry.md
Labels: lgtm, size/M

#313 Refactor SKR watcher installation to use native Kubernetes client
  controllers/kyma_controller.go
  controllers/kyma_controller_remote_sync_test.go
  controllers/kyma_controller_test.go
  controllers/kyma_moduleinfo_test.go
  controllers/suite_test.go
  controllers/watcher_controller.go
  controllers/withwatcher/kyma_controller_test.go
  controllers/withwatcher/suite_with_watcher_test.go
  controllers/withwatcher/watcher_controller_helper_test.go
  controllers/withwatcher/watcher_controller_test.go
  docs/developer/watcher-local-test.md
  go.mod
  go.sum
  main.go
  pkg/catalog/remote_catalog.go
  pkg/deploy/chart_manager.go
  pkg/deploy/helm_client_cache.go
  pkg/deploy/template_chart_manager.go
  pkg/deploy/webhook_chart.go
  pkg/security/san_pinning_suite_test.go
  pkg/testutils/utils.go
  skr-webhook/.helmignore
  skr-webhook/Chart.yaml
  skr-webhook/templates/deployment.yaml
  skr-webhook/templates/rbac.yaml
  skr-webhook/templates/secret.yaml
  skr-webhook/values.yaml
Labels: lgtm, size/XXL

#358 update moduletemplate example
  config/samples/component-integration-installed/operator_v1alpha1_moduletemplate_kcp-module.yaml
  config/samples/component-integration-installed/operator_v1alpha1_moduletemplate_manifest_example-module-name_stable_production_empty_skr.yaml
  config/samples/component-integration-installed/operator_v1alpha1_moduletemplate_skr-module.yaml
  config/samples/component-integration-installed/v1_configmap_nginx_override.yaml
Labels: lgtm, size/L

#363 !feat: SSA for module apply / fix namespace handling / fix test data for credSecretSelector
  controllers/kyma_controller.go
  controllers/moduletemplate_test.go
  go.mod
  go.sum
  pkg/module/parse/template_to_module.go
  pkg/module/sync/runner_impl.go
Labels: lgtm, size/L

#365 Add support for sha256-digest name mapping
  pkg/img/parse.go
Labels: lgtm, size/M

#369 Add CODEOWNERS file
  CODEOWNERS
Labels: lgtm, size/XS

#367 docs: enhance watcher k3d setup
  docs/developer/creating-test-environment.md
  docs/developer/watcher-local-test.md
Labels: lgtm, size/L
