Repository kyma-project/lifecycle-manager, pull requests merged in 2023-03, with the labels that each got.

#438 Allow pullLayer to handle http and https oci repo
  config/watcher_local_test/kustomization.yaml
  controllers/manifest_controller.go
  docs/developer/local-test-setup.md
  flags.go
  internal/manifest/v1beta1/parse.go
  internal/manifest/v1beta1/spec_resolver.go
  internal/manifest/v1beta1/suite_test.go
  main.go
Labels: lgtm, size/M

#418 Introduce custom Kyma metrics
  api/v1beta1/kyma_types.go
  api/v1beta1/manenv_annotations.go
  api/v1beta1/manenv_labels.go
  controllers/kyma_controller.go
  main.go
  pkg/metrics/metrics.go
  pkg/status/kyma_helper.go
  pkg/watcher/certificate.go
Labels: lgtm, size/L

#419 Extend Manifest installation consistency check with deployment availability check
  Makefile
  internal/manifest/v1beta1/manifest_controller_test.go
  internal/manifest/v1beta1/ready_check.go
  internal/manifest/v1beta1/ready_check_test.go
  pkg/declarative/v2/ready_check.go
  pkg/declarative/v2/reconciler.go
  pkg/test_samples/helm/templates/deployment.yaml
  pkg/test_samples/helm/templates/sample_cr.yaml
  pkg/test_samples/oci/crd.tgz
  pkg/test_samples/oci/generate_oci_archives.sh
  pkg/test_samples/oci/helm_chart_with_crds.tgz
Labels: lgtm, size/L

#403 Istio smoke test setup
  .github/workflows/test.yml
  tests/smoke_test/smoke_test.go
Labels: lgtm, size/M

#442 fix: DNS1035 Label Key Compliance
  .github/workflows/test.yml
  api/v1alpha1/manifest_conversion.go
  api/v1alpha1/manifest_types.go
  api/v1beta1/manifest_types.go
  internal/manifest/v1beta1/ready_check.go
  pkg/declarative/v2/default_transforms.go
  pkg/declarative/v2/default_transforms_test.go
  pkg/declarative/v2/mock/object.go
  pkg/declarative/v2/object.go
  pkg/declarative/v2/spec.go
  pkg/declarative/v2/test/v1/declarative_test.go
  pkg/module/common/module.go
Labels: lgtm, size/M

#444 fix: change backoff max reconcile delay from 1000s to 5s
  flags.go
Labels: lgtm, size/XS

#446 manifest reconciler can't handle different target module managed by same kyma
  controllers/manifest_controller.go
  internal/manifest/v1beta1/client.go
  internal/manifest/v1beta1/manifest_controller_test.go
  internal/manifest/v1beta1/ready_check_test.go
  internal/manifest/v1beta1/suite_test.go
  internal/util.go
  pkg/declarative/v2/options.go
  pkg/declarative/v2/reconciler.go
  pkg/declarative/v2/test/v1/declarative_test.go
Labels: kind/bug, lgtm, size/L

#447 chore: bump k8s.io deps from 0.26.1 to 0.26.2
  go.mod
  go.sum
Labels: lgtm, size/M

#441 docs: updated v1beta1 documentation
  README.md
  docs/assets/kyma-module-template-structure.svg
  docs/assets/kyma-operator-architecture.svg
Labels: lgtm, size/M

#450 Fix Private OCI registry authentication crashed Lifecycle-Manager
  controllers/manifest_controller.go
  internal/manifest/v1beta1/client.go
  internal/manifest/v1beta1/manifest_controller_test.go
  internal/manifest/v1beta1/parse.go
  internal/manifest/v1beta1/ready_check.go
  internal/manifest/v1beta1/ready_check_test.go
  internal/manifest/v1beta1/spec_resolver.go
  internal/manifest/v1beta1/suite_test.go
Labels: kind/bug, lgtm, size/M

#449 Quick start documentation
  README.md
  config/samples/component-integration-installed/operator_v1beta1_kyma.yaml
  docs/user/quick-start.md
  hack/k3d-secret-gen.sh
Labels: lgtm, size/L

#460 /pkg/declarative: Move to /internal
  README.md
  api/v1alpha1/manifest_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1beta1/manifest_types.go
  api/v1beta1/zz_generated.deepcopy.go
  controllers/kyma_controller_helper_test.go
  controllers/manifest_controller.go
  internal/declarative/v2/cleanup.go
  internal/declarative/v2/client.go
  internal/declarative/v2/client_cache.go
  internal/declarative/v2/client_proxy.go
  internal/declarative/v2/cluster_info.go
  internal/declarative/v2/crds.go
  internal/declarative/v2/default_transforms.go
  internal/declarative/v2/default_transforms_test.go
  internal/declarative/v2/factory.go
  internal/declarative/v2/helm.go
  internal/declarative/v2/inmemory_rendered.go
  internal/declarative/v2/kube_factory_proxy.go
  internal/declarative/v2/kustomize.go
  internal/declarative/v2/mock/object.go
  internal/declarative/v2/object.go
  internal/declarative/v2/options.go
  internal/declarative/v2/raw_render.go
  internal/declarative/v2/raw_render_test.go
  internal/declarative/v2/ready_check.go
  internal/declarative/v2/reconciler.go
  internal/declarative/v2/renderer.go
  internal/declarative/v2/renderer_with_cache.go
  internal/declarative/v2/renderer_with_cache_test.go
  internal/declarative/v2/resource_converter.go
  internal/declarative/v2/rest_getter_proxy.go
  internal/declarative/v2/spec.go
  internal/declarative/v2/ssa.go
  internal/declarative/v2/ssa_test.go
  internal/declarative/v2/test/v1/api.go
  internal/declarative/v2/test/v1/declarative_test.go
  internal/declarative/v2/test/v1/helper_test.go
  internal/declarative/v2/test/v1/suite_test.go
  internal/declarative/v2/test/v1/zz_generated.deepcopy.go
  internal/declarative/v2/util.go
  internal/declarative/v2/zz_generated.deepcopy.go
  internal/manifest/v1beta1/client.go
  internal/manifest/v1beta1/custom_resource.go
  internal/manifest/v1beta1/manifest_controller_test.go
  internal/manifest/v1beta1/ready_check.go
  internal/manifest/v1beta1/ready_check_test.go
  internal/manifest/v1beta1/skr_client_lookup.go
  internal/manifest/v1beta1/spec_resolver.go
  internal/manifest/v1beta1/suite_test.go
Labels: lgtm, size/M

#448 Technical Reference Documentation
  README.md
  api/README.md
  config/crd/kustomization.yaml
  controllers/README.md
  docs/developer/reference-documentation.md
  internal/declarative/README.md
  internal/declarative/v2/reconciler.go
  internal/declarative/v2/renderer.go
  internal/declarative/v2/renderer_helm.go
  internal/declarative/v2/renderer_kustomize.go
  internal/declarative/v2/renderer_raw.go
  internal/declarative/v2/renderer_raw_test.go
  internal/declarative/v2/spec.go
  internal/manifest/README.md
Labels: lgtm, size/XL

#468 Makefile: Divide CRD Installation in Deploy Target
  Makefile
Labels: lgtm, size/XS

#473 Fix reference docu link
  docs/developer/reference-documentation.md
Labels: lgtm, size/XS

#474 Replace warning events when setting metrics by info log
  controllers/kyma_controller.go
  controllers/kyma_controller_helper_test.go
  internal/declarative/v2/renderer_raw_test.go
  internal/declarative/v2/renderer_with_cache_test.go
  internal/declarative/v2/ssa_test.go
  internal/declarative/v2/test/v1/api.go
  internal/declarative/v2/test/v1/declarative_test.go
  internal/declarative/v2/test/v1/helper_test.go
  internal/declarative/v2/test/v1/suite_test.go
  internal/manifest/v1beta1/client.go
  internal/manifest/v1beta1/custom_resource.go
  internal/manifest/v1beta1/manifest_controller_test.go
  internal/manifest/v1beta1/ready_check.go
  internal/manifest/v1beta1/ready_check_test.go
  internal/manifest/v1beta1/skr_client_lookup.go
  internal/manifest/v1beta1/spec_resolver.go
  internal/manifest/v1beta1/suite_test.go
  pkg/metrics/metrics.go
  pkg/status/kyma_helper.go
Labels: lgtm, size/M

#477 mention interactive tutorial in quick start
  docs/user/quick-start.md
Labels: lgtm, size/S

#482 validateVersion only compare major minor patch
  api/v1beta1/moduletemplate_webhook.go
  api/v1beta1/moduletemplate_webhook_test.go
  controllers/suite_test.go
Labels: lgtm, size/L

#486 Enable Grafana dashboards for control-plane target
  config/control-plane/kustomization.yaml
  config/control-plane/patches/dashboard_cm_patch.yaml
  config/control-plane/patches/metrics_namespace_replace.yaml
Labels: lgtm, size/S

#499 Make tests more stable
  config/samples/tests/crds/cert-manager-v1.10.1.crds.yaml
  config/samples/tests/crds/istio-v1.17.1.crds.yaml
  controllers/kyma_controller.go
  controllers/kyma_controller_helper_test.go
  controllers/kyma_controller_test.go
  controllers/kyma_module_channel_test.go
  controllers/suite_test.go
  controllers/withwatcher/suite_with_watcher_test.go
  internal/manifest/v1beta1/keychain_test.go
  pkg/testutils/utils.go
  pkg/watcher/certificate_suite_test.go
Labels: lgtm, size/XXL
