Repository kyma-project/lifecycle-manager, pull requests merged in 2023-09, with the labels that each got.

#837 Introduce ErrAccessSecretNotFound
  .golangci.yaml
  controllers/kyma_controller.go
  internal/declarative/v2/reconciler.go
  internal/declarative/v2/test/v1/declarative_test.go
  pkg/channel/lookup.go
  pkg/remote/cluster_client.go
  pkg/remote/context.go
  pkg/security/san_pinning_test.go
  pkg/status/conditions_test.go
Labels: lgtm, size/M

#849 config/grafana: Add Listener Metrics
  config/grafana/overview.json
Labels: lgtm, size/L

#852 chore: Add a Conventional Commits linter as a GitHub action
  .github/workflows/lint-conventional-prs.yml
Labels: lgtm, size/M

#854 chore: Unify GitHub actions names and titles
  .github/workflows/lint-conventional-prs.yml
  .github/workflows/lint-golangci.yml
  .github/workflows/test-e2e.yml
  .github/workflows/test-smoke.yml
Labels: lgtm, size/XS

#856 fix: Add YAML Struct Tags to CustomStateCheck
  api/v1beta2/moduletemplate_types.go
Labels: lgtm, size/XS

#857 chore: Add the Markdown Link Checker GitHub action
  .github/workflows/lint-markdown-links.yml
  .mlc.config.json
  README.md
  api/README.md
  controllers/README.md
  docs/README.md
  docs/developer-tutorials/local-test-setup.md
  docs/modularization.md
  docs/technical-reference/api/README.md
  docs/technical-reference/api/kyma-cr.md
  docs/technical-reference/api/manifest-cr.md
  docs/technical-reference/api/moduleTemplate-cr.md
  docs/technical-reference/architecture.md
  docs/technical-reference/controllers.md
  docs/technical-reference/running-modes.md
  docs/user-tutorials/01-10-control-plane-quick-start.md
  internal/declarative/README.md
  internal/manifest/README.md
  tests/e2e_test/README.md
Labels: lgtm, size/L

#842 chore: Use SKR Module List as single source of Truth
  controllers/control-plane/kcp_controller_helper_test.go
  controllers/control-plane/kyma_remote_sync_test.go
  controllers/kyma_controller.go
  docs/developer-tutorials/local-test-setup.md
  pkg/remote/kyma_synchronization_context.go
  pkg/remote/kyma_synchronization_context_test.go
  pkg/testutils/utils.go
  tests/e2e_test/status_propagation_test.go
Labels: lgtm, size/L

#848 test: Extend manifest CR tests
  controllers/manifest_controller/custom_resource_check/manifest_test.go
  controllers/manifest_controller/custom_resource_check/suite_test.go
  controllers/manifest_controller/keychain_test.go
  controllers/manifest_controller/manifest_controller_helper_test.go
  controllers/manifest_controller/manifest_controller_test.go
  controllers/manifest_controller/manifesttest/manifesttest.go
  controllers/manifest_controller/ready_check_test.go
  pkg/test_samples/oci/rendered.yaml
Labels: lgtm, size/XL, area/tests, area/installation

#843 chore!: Upgrade to ocm v0.3.0
  .golangci.yaml
  api/v1beta2/webhook_suite_test.go
  controllers/control-plane/kcp_suite_test.go
  controllers/kyma_controller/manifest_test.go
  controllers/kyma_controller/suite_test.go
  go.mod
  go.sum
  main.go
  pkg/img/parse.go
Labels: lgtm, size/XXL

#859 chore: Use GH-Action instead prow job for unit testing
  .github/workflows/lint-golangci.yml
  .github/workflows/test-e2e.yml
  .github/workflows/test-smoke.yml
  .github/workflows/test-unit.yml
Labels: lgtm, size/M

#863 chore: Allow yaml change trigger e2e test
  .github/workflows/test-e2e.yml
  .github/workflows/test-smoke.yml
  .github/workflows/test-unit.yml
Labels: lgtm, size/XS

#862 test: Introduce localblob for module upgrade test
  tests/smoke_test/module_upgrade/moduletemplate_template_operator_fast.yaml
Labels: lgtm, size/S

#861 feat: Drop request-sidecar container
  skr-webhook/resources.yaml
Labels: lgtm, size/S

#866 test: ModuleTemplate version update for Manifest CR suite
  controllers/kyma_controller/manifest_test.go
Labels: lgtm, kind/missing-test, size/L

#876 chore(infra): Configure dependabot to adhere to the Conventional Commits spec
  .github/dependabot.yml
  .github/workflows/lint-markdown-links.yml
Labels: lgtm, size/S

#878 chore: Make info level log to debug
  pkg/watcher/skr_webhook_manifest_manager.go
Labels: lgtm, size/XS

#839 chore: Remove unnecessary ctx pointer
  controllers/kyma_controller.go
  pkg/remote/context.go
Labels: lgtm, size/M

#877 chore: Add more log messages
  controllers/purge_controller.go
Labels: lgtm, size/XS

#881 fix: Avoid purge reconciliation on status sub resource update
  controllers/setup.go
Labels: lgtm, size/XS

#885 fix: CreateVirtualService always return error
  pkg/istio/client.go
Labels: lgtm, size/XS

#886 fix: Remove flaky watcher test condition
  controllers/withwatcher/kyma_controller_test.go
Labels: lgtm, size/XS

#891 deps: Bump k8s deps
  go.mod
  go.sum
Labels: lgtm, size/M

#892 fix: Change requeue interval detection
  .github/workflows/test-e2e.yml
  api/v1beta2/watcher_types.go
  config/crd/bases/operator.kyma-project.io_watchers.yaml
  controllers/control-plane/kcp_suite_test.go
  controllers/control-plane/kyma_remote_sync_test.go
  controllers/kyma_controller.go
  controllers/kyma_controller/suite_test.go
  controllers/purge_controller.go
  controllers/setup.go
  controllers/watcher_controller.go
  controllers/withwatcher/suite_with_watcher_test.go
  controllers/withwatcher/watcher_controller_test.go
  internal/declarative/v2/reconciler.go
  main.go
  pkg/queue/requeue_intervals.go
  pkg/testutils/utils.go
Labels: lgtm, size/L

#884 chore(github, sdlc): Replace the feature request issue template with a form
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: lgtm, size/M

#895 fix: Add metadata predicates
  controllers/setup.go
Labels: lgtm, size/S

#893 chore: bump github.com/open-component-model/ocm from v0.3.0 to v0.4.0
  .golangci.yaml
  go.mod
  go.sum
Labels: lgtm, size/L, area/dependency

#903 test(e2e): Add Acceptance Criteria report
  tests/e2e_test/Makefile
Labels: lgtm, size/M
