Repository kyma-project/lifecycle-manager, pull requests merged in 2023-02, with the labels that each got.

#372 Use errgroup for module update
  api/v1alpha1/webhook_crd_test.go
  api/v1alpha1/webhook_suite_test.go
  controllers/kyma_controller_helper_test.go
  controllers/kyma_controller_remote_sync_test.go
  controllers/kyma_controller_test.go
  go.mod
  go.sum
  pkg/module/sync/runner_impl.go
Labels: lgtm, size/L

#374 Error group revert
  controllers/suite_test.go
  pkg/catalog/remote_catalog.go
  pkg/module/sync/runner_impl.go
Labels: lgtm, size/L

#377 Provide a way to stop reconciliation for kyma clusters
  Makefile
  api/v1alpha1/kyma_types.go
  api/v1alpha1/operator_labels.go
  api/v1alpha1/webhook_crd_test.go
  controllers/kyma_controller.go
  controllers/kyma_controller_helper_test.go
  controllers/kyma_controller_test.go
  controllers/moduletemplate_test.go
  controllers/suite_test.go
  controllers/withwatcher/kyma_controller_test.go
  controllers/withwatcher/suite_with_watcher_test.go
  controllers/withwatcher/watcher_controller_test.go
  pkg/security/san_pinning_test.go
  tests/smoke_test/smoke_test.go
Labels: lgtm, size/L

#373 feat: allow nil manifests by passing resources based on policy
  api/v1alpha1/kyma_types.go
  config/crd/bases/operator.kyma-project.io_kymas.yaml
  go.mod
  go.sum
  pkg/module/parse/template_to_module.go
Labels: lgtm, size/L

#383 Add dependabot configuration
  .github/dependabot.yml
Labels: lgtm, size/S

#340 First Setup of dynamic PKI
  Makefile
  api/v1alpha1/operator_labels.go
  config/control-plane/kustomization.yaml
  config/default/kustomization.yaml
  config/load_test/kustomization.yaml
  config/rbac/role.yaml
  config/samples/component-integration-installed/operator_v1alpha1_moduletemplate_skr-module.yaml
  config/watcher/certificate_for_watcher_gateway.yaml
  config/watcher/certificate_setup.yaml
  config/watcher/gateway.yaml
  config/watcher/kustomization.yaml
  config/watcher/operator_v1alpha1_watcher.yaml
  config/watcher_local_test/kustomization.yaml
  config/watcher_local_test/patch.yaml
  controllers/kyma_controller.go
  controllers/setup.go
  controllers/suite_test.go
  controllers/watcher_controller.go
  controllers/withwatcher/kyma_controller_test.go
  controllers/withwatcher/suite_with_watcher_test.go
  controllers/withwatcher/watcher_controller_helper_test.go
  docs/developer/watcher-local-test.md
  flags.go
  go.mod
  go.sum
  main.go
  pkg/security/san_pinning.go
  pkg/testutils/utils.go
  pkg/watcher/certificate.go
  pkg/watcher/certificate_suite_test.go
  pkg/watcher/certificate_test.go
  pkg/watcher/skr_webhook_manager.go
  pkg/watcher/skr_webhook_manifest_manager.go
  pkg/watcher/skr_webhook_resources.go
  pkg/watcher/webhook_chart.go
Labels: lgtm, size/XXL

#393 fix: pin kustomize version in case of previously downloaded kustomizations being different
  .github/workflows/test.yml
Labels: lgtm, size/XS

#397 fix: add webhooks to lifecycle manager
  config/control-plane/kustomization.yaml
Labels: lgtm, size/XS

#398 fix: add ap paths for webhooks
  config/istio/ap.yaml
Labels: lgtm, size/XS

#399 fix: add star paths to ap options for webhooks
  config/istio/ap.yaml
Labels: size/XS

#400 fix: add exclusion of webhook port on istio so that webhook can be called by api server
  config/istio/kustomization.yaml
  config/istio/patches/exclude_webhook_port.yaml
Labels: size/S

#395 Fix module delete bug
  api/v1alpha1/kyma_types.go
  api/v1alpha1/manifest_conversion.go
  api/v1alpha1/manifest_types.go
  api/v1alpha1/manifest_webhook.go
  api/v1alpha1/moduletemplate_types.go
  api/v1alpha1/spoke.go
  api/v1alpha1/watcher_types.go
  api/v1beta1/kyma_types.go
  api/v1beta1/manifest_conversion.go
  api/v1beta1/manifest_webhook.go
  config/control-plane/kustomization.yaml
  config/control-plane/patches/adjust_resources_in_deployment.yaml
  config/crd/bases/operator.kyma-project.io_kymas.yaml
  config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
  config/crd/bases/operator.kyma-project.io_watchers.yaml
  config/default/kustomization.yaml
  controllers/kyma_controller.go
  pkg/module/sync/runner_impl.go
  pkg/remote/crd_upgrade.go
Labels: lgtm, size/L

#401 Bring enable webhook flag to config/webhook
  config/control-plane/kustomization.yaml
  config/default/kustomization.yaml
  config/webhook/kustomization.yaml
Labels: lgtm, size/S

#394 Introduce ociRegistry access support for module-templates
  config/samples/component-integration-installed/operator_v1beta1_moduletemplate_kcp-module.yaml
  controllers/kyma_controller_helper_test.go
  controllers/kyma_controller_remote_sync_test.go
  pkg/img/parse.go
Labels: lgtm, size/M

#407 fix: remove bad naming scheme from `operator.kyma-project.io/owned-by`
  api/v1beta1/operator_labels.go
  pkg/declarative/v2/default_transforms.go
  pkg/labels/component_labels.go
  pkg/remote/kyma_synchronization_context.go
Labels: lgtm, size/M

#413 Refactor labels pkg and add owned-by annotation
  api/v1beta1/operator_annotations.go
  api/v1beta1/operator_labels.go
  controllers/manifest_controller.go
  internal/manifest/v1beta1/client.go
  internal/manifest/v1beta1/manifest_controller_helper_test.go
  internal/manifest/v1beta1/manifest_controller_test.go
  internal/manifest/v1beta1/skr_client_lookup.go
  internal/manifest/v1beta1/suite_test.go
  internal/util.go
  pkg/declarative/v2/default_transforms.go
  pkg/labels/component_labels.go
  pkg/remote/kyma_synchronization_context.go
Labels: lgtm, size/L

#416 Fix v1alpha1 validation webhook get called unintentionally
  PROJECT
  api/v1alpha1/codec.go
  api/v1alpha1/manifest_conversion.go
  api/v1alpha1/manifest_types.go
  api/v1alpha1/manifest_webhook.go
  api/v1alpha1/moduletemplate_webhook.go
  api/v1alpha1/validate.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1beta1/webhook_suite_test.go
  config/crd/kustomization.yaml
  config/samples/operator_v1alpha1_manifest.yaml
  config/webhook/manifests.yaml
  main.go
  pkg/watcher/certificate_suite_test.go
Labels: lgtm, size/XL

#417 OCM migration
  api/v1beta1/codec/unsafe/codec.go
  api/v1beta1/groupversion_info.go
  api/v1beta1/moduletemplate_types.go
  api/v1beta1/moduletemplate_webhook.go
  api/v1beta1/webhook_crd_validation_test.go
  api/v1beta1/webhook_ocm_test.go
  api/v1beta1/webhook_suite_test.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
  config/samples/component-integration-installed/operator_v1beta1_moduletemplate_ocm.software.v3alpha1.yaml
  controllers/kyma_controller_helper_test.go
  controllers/kyma_controller_remote_sync_test.go
  controllers/moduletemplate_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
  pkg/channel/lookup.go
  pkg/img/parse.go
  pkg/module/parse/template_to_module.go
  pkg/ocmextensions/HelmChartRepository.go
  pkg/remote/kyma_synchronization_context.go
  pkg/signature/verifier.go
  pkg/testutils/utils.go
  pkg/watcher/certificate_suite_test.go
Labels: lgtm, size/XXL

#429 Fix local setup guide, update dependencies, set Watcher status as sub…
  README.md
  api/v1beta1/watcher_types.go
  config/crd/bases/operator.kyma-project.io_watchers.yaml
  config/default/kustomization.yaml
  config/watcher/certificate_setup.yaml
  config/watcher/gateway.yaml
  config/watcher/kustomization.yaml
  config/watcher/operator_v1alpha1_watcher.yaml
  config/watcher_local_test/kustomization.yaml
  docs/developer/creating-test-environment.md
  docs/developer/local-test-setup.md
Labels: lgtm, size/L
