Repository kyma-project/lifecycle-manager, pull requests merged in 2023-10, with the labels that each got.

#909 feat: Add metrics for purge-controller
  controllers/kyma_controller.go
  controllers/kyma_controller/kyma_test.go
  controllers/kyma_controller/manifest_test.go
  controllers/kyma_controller/moduletemplate_install_test.go
  controllers/kyma_controller/moduletemplate_test.go
  controllers/purge/suite_test.go
  controllers/purge_controller.go
  internal/controller/common/metrics/metrics.go
  internal/controller/kyma/metrics/metrics.go
  internal/controller/purge/metrics/metrics.go
  main.go
  pkg/matcher/matcher.go
  pkg/matcher/matcher_test.go
  pkg/module/sync/runner_impl.go
  pkg/status/conditions_test.go
  pkg/status/kyma_helper.go
  pkg/testutils/builder/crds.go
  pkg/testutils/builder/kyma.go
  pkg/testutils/utils.go
Labels: lgtm, size/XL

#869 deps(kubebuilder): Migration from go/v3 to go/v4
  Dockerfile
  Makefile
  PROJECT
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta2/webhook_suite_test.go
  api/v1beta2/zz_generated.deepcopy.go
  cmd/flags.go
  cmd/main.go
  config/crd/bases/operator.kyma-project.io_kcpmodules.yaml
  config/crd/bases/operator.kyma-project.io_kymas.yaml
  config/crd/bases/operator.kyma-project.io_manifests.yaml
  config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
  config/crd/bases/operator.kyma-project.io_watchers.yaml
  config/crd/bases/test.declarative.kyma-project.io_testapis.yaml
  config/rbac/role.yaml
  config/samples/component-integration-installed/crd/operator.kyma-project.io_kcpmodules.yaml
  config/webhook/manifests.yaml
  go.mod
  go.sum
  internal/controller/README.md
  internal/controller/control-plane/kcp_controller_helper_test.go
  internal/controller/control-plane/kcp_controller_test.go
  internal/controller/control-plane/kcp_manifest_test.go
  internal/controller/control-plane/kcp_suite_test.go
  internal/controller/control-plane/kyma_remote_sync_test.go
  internal/controller/kyma_controller.go
  internal/controller/kyma_controller/kyma_controller_helper_test.go
  internal/controller/kyma_controller/kyma_module_channel_test.go
  internal/controller/kyma_controller/kyma_moduleinfo_test.go
  internal/controller/kyma_controller/kyma_test.go
  internal/controller/kyma_controller/manifest_test.go
  internal/controller/kyma_controller/moduletemplate_install_test.go
  internal/controller/kyma_controller/moduletemplate_test.go
  internal/controller/kyma_controller/suite_test.go
  internal/controller/manifest_controller.go
  internal/controller/manifest_controller/custom_resource_check/manifest_test.go
  internal/controller/manifest_controller/custom_resource_check/suite_test.go
  internal/controller/manifest_controller/keychain_test.go
  internal/controller/manifest_controller/manifest_controller_test.go
  internal/controller/manifest_controller/manifesttest/manifesttest.go
  internal/controller/manifest_controller/ready_check_test.go
  internal/controller/manifest_controller/suite_test.go
  internal/controller/purge/purge_controller_helper_test.go
  internal/controller/purge/purge_controller_test.go
  internal/controller/purge/suite_test.go
  internal/controller/purge_controller.go
  internal/controller/setup.go
  internal/controller/util.go
  internal/controller/watcher_controller.go
  internal/controller/withwatcher/kyma_controller_test.go
  internal/controller/withwatcher/suite_with_watcher_test.go
  internal/controller/withwatcher/watcher_certificate_test.go
  internal/controller/withwatcher/watcher_controller_helper_test.go
  internal/controller/withwatcher/watcher_controller_test.go
  internal/declarative/v2/test/v1/declarative_test.go
  internal/declarative/v2/test/v1/zz_generated.deepcopy.go
  internal/declarative/v2/zz_generated.deepcopy.go
Labels: lgtm, size/L

#915 chore: Delete custom multi error
  api/v1beta2/codec.go
  internal/declarative/v2/cleanup.go
  internal/declarative/v2/resource_converter.go
  internal/declarative/v2/ssa.go
  pkg/module/sync/runner_impl.go
  pkg/remote/remote_catalog.go
  pkg/types/multi_error.go
Labels: lgtm, size/M

#920 chore(github): Remove unnecessary issue template
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: lgtm, size/S

#924 fix: Purge error metric
  internal/controller/purge/metrics/metrics.go
Labels: lgtm, size/S

#928 deps: Upgrade controller-runtime to 0.16.2
  api/v1beta2/webhook_suite_test.go
  cmd/main.go
  go.mod
  go.sum
  internal/controller/control-plane/kcp_suite_test.go
  internal/controller/kyma_controller/suite_test.go
  internal/controller/manifest_controller/custom_resource_check/suite_test.go
  internal/controller/manifest_controller/suite_test.go
  internal/controller/purge/suite_test.go
  internal/controller/withwatcher/suite_with_watcher_test.go
  internal/declarative/v2/test/v1/declarative_test.go
Labels: lgtm, size/L

#887 feat: Upgrade kustomize to v5
  Makefile
  config/control-plane/kustomization.yaml
  config/control-plane/patches/dashboard_cm_patch.yaml
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
  config/load_test/kustomization.yaml
  config/rbac/manifest_role.yaml
  config/rbac/metrics_clusterrole_binding.yaml
  config/watcher/kustomization.yaml
  config/watcher_local_test/kustomization.yaml
Labels: lgtm, size/L

#921 chore: Refactor unit/integration test to improve test resource creation
  api/v1beta2/webhook_moduletemplate_crd_validation_test.go
  api/v1beta2/webhook_ocm_test.go
  internal/controller/control-plane/helper_test.go
  internal/controller/control-plane/kcp_suite_test.go
  internal/controller/control-plane/kyma_remote_sync_test.go
  internal/controller/kyma_controller/helper_test.go
  internal/controller/kyma_controller/kyma_module_channel_test.go
  internal/controller/kyma_controller/kyma_moduleinfo_test.go
  internal/controller/kyma_controller/kyma_test.go
  internal/controller/kyma_controller/manifest_test.go
  internal/controller/kyma_controller/moduletemplate_install_test.go
  internal/controller/kyma_controller/moduletemplate_test.go
  internal/controller/kyma_controller/suite_test.go
  internal/controller/manifest_controller/manifest_controller_test.go
  internal/controller/purge/suite_test.go
  internal/controller/withwatcher/suite_with_watcher_test.go
  internal/manifest/ready_check_test.go
  pkg/status/conditions_test.go
  pkg/testutils/builder/crds.go
  pkg/testutils/builder/kyma.go
  pkg/testutils/builder/modulecr.go
  pkg/testutils/builder/moduletemplate.go
  pkg/testutils/kyma.go
  pkg/testutils/manifest.go
  pkg/testutils/moduletemplate.go
  pkg/testutils/utils.go
  pkg/watcher/certificate_suite_test.go
  tests/e2e_test/kyma_deletion_test.go
  tests/e2e_test/kyma_metrics_test.go
  tests/e2e_test/status_propagation_test.go
  tests/e2e_test/watcher_test.go
  tests/smoke_test/smoke_test.go
Labels: lgtm, size/XXL

#933 feat: Add panel for purge metrics & cleanup other panels
  config/grafana/overview.json
Labels: lgtm, size/L

#927 fix: Add module version to descriptor cache key
  api/v1beta2/moduletemplate_types.go
  api/v1beta2/moduletemplate_types_test.go
  api/v1beta2/operator_annotations.go
Labels: lgtm, size/M

#932 feat: Kustomize remove vars
  config/control-plane/kustomization.yaml
  config/default/kustomization.yaml
  config/default/webhookcainjection_patch.yaml
  config/load_test/kustomization.yaml
Labels: lgtm, size/L

#916 fix: Not caching descriptor for remote modules
  api/v1beta2/moduletemplate_types.go
  internal/controller/control-plane/kyma_remote_sync_test.go
  pkg/channel/lookup.go
  pkg/testutils/utils.go
Labels: lgtm, size/M

#931 test: Runtime watcher test for status subresource watching
  tests/e2e_test/watcher_test.go
Labels: lgtm, size/M

#941 chore: Update listener version
  go.mod
  go.sum
Labels: lgtm, size/XS

#944 test: Add integration test for testing the event filters behavior
  internal/controller/event-filters/eventfilter_test.go
  internal/controller/event-filters/helper_test.go
  internal/controller/event-filters/suite_test.go
Labels: lgtm, size/L

#911 fix: Make data as pointer to support module without default CR
  .github/workflows/test-e2e.yml
  Dockerfile
  api/v1beta1/moduletemplate_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta2/moduletemplate_types.go
  api/v1beta2/zz_generated.deepcopy.go
  internal/controller/control-plane/helper_test.go
  internal/controller/control-plane/kcp_manifest_test.go
  internal/controller/control-plane/kyma_remote_sync_test.go
  internal/controller/kyma_controller/helper_test.go
  internal/controller/kyma_controller/kyma_module_channel_test.go
  internal/controller/kyma_controller/kyma_test.go
  internal/controller/kyma_controller/manifest_test.go
  internal/controller/kyma_controller/moduletemplate_install_test.go
  internal/controller/kyma_controller/moduletemplate_test.go
  internal/controller/purge/purge_controller_helper_test.go
  internal/declarative/v2/mock/object.go
  pkg/module/parse/template_to_module.go
  pkg/testutils/builder/moduletemplate.go
  pkg/testutils/kyma.go
  pkg/testutils/manifest.go
  pkg/testutils/modulecr.go
  pkg/testutils/moduletemplate.go
  tests/e2e_test/Makefile
  tests/e2e_test/kyma_deletion_test.go
  tests/e2e_test/kyma_metrics_test.go
  tests/e2e_test/no_default_cr_test.go
  tests/e2e_test/status_propagation_test.go
  tests/e2e_test/suite_test.go
  tests/e2e_test/utils_test.go
  tests/e2e_test/watcher_test.go
Labels: kind/bug, lgtm, size/XL

#923 fix: Deleting State Overwrite in Manifest Reconciler
  .github/workflows/test-e2e.yml
  internal/declarative/v2/reconciler.go
  tests/e2e_test/Makefile
  tests/e2e_test/deletion_status_propagation_test.go
  tests/e2e_test/utils_test.go
Labels: lgtm, size/L

#950 fix: Manifest CR can't set deleting state
  .github/workflows/test-e2e.yml
  internal/declarative/v2/reconciler.go
  tests/e2e_test/Makefile
  tests/e2e_test/deletion_status_propagation_test.go
Labels: lgtm, size/L

#951 fix: Flaky watcher test
  internal/controller/withwatcher/kyma_controller_test.go
Labels: lgtm, size/S

#912 feat(newReconcileOption): Introduce ModuleCRDeletionCheck + Non-Blocking Deletion for Modules
  .github/workflows/test-e2e.yml
  go.mod
  internal/controller/event-filters/eventfilter_test.go
  internal/controller/kyma_controller/kyma_test.go
  internal/controller/manifest_controller.go
  internal/controller/purge/purge_controller_test.go
  internal/declarative/v2/moduleCR_deletion_check.go
  internal/declarative/v2/options.go
  internal/declarative/v2/reconciler.go
  internal/manifest/cr_deletion_check.go
  internal/manifest/custom_resource.go
  pkg/testutils/kyma.go
  pkg/testutils/modulecr.go
  pkg/testutils/utils.go
  tests/e2e_test/Makefile
  tests/e2e_test/kyma_deletion_test.go
  tests/e2e_test/module_deletion_test.go
  tests/e2e_test/no_default_cr_test.go
  tests/e2e_test/status_propagation_test.go
  tests/e2e_test/utils_test.go
Labels: lgtm, size/XL

#947 feat: Improve XFCC header parsing in SAN Verification code (Checkmarx)
  pkg/security/internal_test.go
  pkg/security/san_pinning.go
  pkg/security/san_pinning_test.go
Labels: lgtm, size/L

#955 chore: Increase timeout for e2e test
  tests/e2e_test/Makefile
Labels: lgtm, size/S

#960 chore: Put istio related dep in one import block
  go.mod
  go.sum
Labels: lgtm, size/S

#964 fix: Change download kubectl from apt
  .github/workflows/test-e2e.yml
  .github/workflows/test-smoke.yml
Labels: lgtm, size/S

#939 chore(sdlc, reporting): Adds a GitHub action to generate an ad hoc acceptance criteria report
  .github/workflows/report-acceptance-criteria.yml
  tests/e2e_test/Makefile
Labels: lgtm, size/M

#967 chore: Fix the indentation in the config file
  .github/workflows/report-acceptance-criteria.yml
Labels: lgtm, size/XS

#966 chore: Download go binary from github action
  .github/workflows/test-e2e.yml
  .github/workflows/test-smoke.yml
Labels: lgtm, size/S

#902 chore: Remove codec
  api/v1beta2/codec.go
  api/v1beta2/manifest_types.go
  go.mod
  go.sum
  internal/controller/manifest_controller.go
  internal/controller/manifest_controller/custom_resource_check/suite_test.go
  internal/controller/manifest_controller/suite_test.go
  internal/manifest/spec_resolver.go
Labels: lgtm, size/L

#971 fix: Fix skip reconciliation for Manifest
  api/v1beta2/kyma_types.go
  api/v1beta2/operator_labels.go
  internal/controller/kyma_controller/kyma_test.go
  internal/controller/kyma_controller/manifest_test.go
  internal/declarative/v2/options.go
  pkg/testutils/manifest.go
Labels: lgtm, size/M

#948 test: Purge Controller E2E tests
  .github/workflows/test-e2e.yml
  pkg/testutils/kyma.go
  pkg/testutils/modulecr.go
  tests/e2e_test/Makefile
  tests/e2e_test/no_default_cr_test.go
  tests/e2e_test/purge_controller_test.go
  tests/e2e_test/purge_metrics_test.go
  tests/e2e_test/utils_test.go
Labels: lgtm, size/L

#956 fix: State propagation during module CR deletion
  internal/controller/control-plane/helper_test.go
  internal/controller/control-plane/kcp_controller_test.go
  internal/controller/control-plane/kyma_remote_sync_test.go
  internal/controller/kyma_controller/helper_test.go
  internal/controller/kyma_controller/kyma_module_channel_test.go
  internal/controller/kyma_controller/kyma_moduleinfo_test.go
  internal/controller/kyma_controller/kyma_test.go
  internal/controller/kyma_controller/manifest_test.go
  internal/declarative/v2/reconciler.go
  internal/manifest/ready_check.go
  internal/manifest/ready_check_test.go
  pkg/testutils/kyma.go
  pkg/testutils/utils.go
  tests/e2e_test/module_deletion_test.go
  tests/e2e_test/no_default_cr_test.go
  tests/e2e_test/status_propagation_test.go
  tests/e2e_test/utils_test.go
Labels: lgtm, size/XL

#977 fix broken e2e test and disable gosumdb check
  .github/workflows/test-e2e.yml
  .github/workflows/test-smoke.yml
  .github/workflows/test-unit.yml
  pkg/testutils/utils.go
  tests/e2e_test/purge_controller_test.go
  tests/e2e_test/purge_metrics_test.go
  tests/e2e_test/utils_test.go
Labels: lgtm, size/S

#974 test: Enhance the deletion E2E test
  .github/workflows/test-e2e.yml
  internal/controller/event-filters/eventfilter_test.go
  internal/controller/kyma_controller/kyma_module_channel_test.go
  internal/controller/kyma_controller/kyma_test.go
  internal/controller/kyma_controller/manifest_test.go
  internal/controller/purge/purge_controller_test.go
  pkg/testutils/kyma.go
  pkg/testutils/modulecr.go
  tests/e2e_test/kyma_deletion_test.go
  tests/e2e_test/module_deletion_test.go
  tests/e2e_test/no_default_cr_test.go
  tests/e2e_test/purge_controller_test.go
  tests/e2e_test/purge_metrics_test.go
  tests/e2e_test/status_propagation_test.go
  tests/e2e_test/utils_test.go
Labels: lgtm, size/L

#979 feat: Adjust skr watcher image flag
  .github/workflows/test-e2e.yml
  .github/workflows/test-smoke.yml
  cmd/flags.go
  config/watcher_local_test/kustomization.yaml
  pkg/watcher/skr_webhook_resources.go
Labels: lgtm, size/S

#985 upgrade k8s.io dependencies
  go.mod
  go.sum
Labels: lgtm, size/M

#980 test: Refactor Smoke test
  .github/workflows/test-e2e.yml
  .github/workflows/test-smoke.yml
  go.mod
  go.sum
  pkg/testutils/modulecr.go
  tests/e2e_test/Makefile
  tests/e2e_test/module_upgrade_test.go
  tests/e2e_test/utils_test.go
  tests/moduletemplates/moduletemplate_template_operator_fast.yaml
  tests/moduletemplates/moduletemplate_template_operator_regular.yaml
  tests/smoke_test/.gitignore
  tests/smoke_test/Makefile
  tests/smoke_test/README.md
  tests/smoke_test/smoke_test.go
Labels: lgtm, size/XL
