Repository kyma-project/lifecycle-manager, pull requests merged in 2023-11, with the labels that each got.

#993 fix: cleanup metrics before kyma finalizer removed
  .github/workflows/test-e2e.yml
  internal/controller/kyma/metrics/metrics.go
  internal/controller/kyma_controller.go
  pkg/module/sync/runner_impl.go
  tests/e2e_test/kyma_deletion_test.go
  tests/e2e_test/kyma_metrics_test.go
  tests/e2e_test/module_deletion_test.go
  tests/e2e_test/utils_test.go
Labels: lgtm, size/L

#994 chore: Add validation for module version before using it as part of ComponentDescriptorCache Key
  api/v1beta2/moduletemplate_types.go
  api/v1beta2/moduletemplate_types_test.go
Labels: lgtm, size/S

#997 chore: Emit a warning event if metrics annotation or label are missing
  internal/controller/common/metrics/metrics.go
  internal/controller/kyma_controller.go
  pkg/status/kyma_helper.go
Labels: lgtm, size/M

#1001 docs: Add Manifest skip label documentation
  .github/workflows/lint-golangci.yml
  .github/workflows/test-e2e.yml
  .github/workflows/test-smoke.yml
  .github/workflows/test-unit.yml
  config/crd/bases/operator.kyma-project.io_manifests.yaml
  config/crd/bases/test.declarative.kyma-project.io_testapis.yaml
  docs/technical-reference/api/manifest-cr.md
Labels: lgtm, size/M

#1010 chore: Use the correct semver package
  api/v1beta2/moduletemplate_types.go
  api/v1beta2/moduletemplate_types_test.go
Labels: lgtm, size/XS

#1003 chore: Revisit TODOs
  internal/declarative/v2/reconciler.go
  internal/declarative/v2/ssa_test.go
  pkg/istio/client.go
  pkg/module/common/module.go
  pkg/module/parse/template_to_module.go
  pkg/module/sync/runner_impl.go
  pkg/signature/verifier.go
  pkg/watcher/skr_webhook_resources.go
  pkg/watcher/webhook_chart.go
Labels: lgtm, size/M

#996 test: Upgrade action-semantic-pull-request to latest version
  .github/workflows/lint-conventional-prs.yml
Labels: lgtm, size/XS

#1008 fix: Purge controller related metrics
  config/grafana/overview.json
Labels: lgtm, size/XS

#1016 Do not start Lifecycle Manager if no watcher image is specified
  cmd/flags.go
  cmd/main.go
  config/crd/bases/operator.kyma-project.io_manifests.yaml
  config/crd/bases/test.declarative.kyma-project.io_testapis.yaml
Labels: lgtm, size/M

#1023 chore(github): Adjust PR title linting config
  .github/workflows/lint-conventional-prs.yml
Labels: lgtm, size/XS

#1035 chore: Enable godox linter
  .golangci.yaml
Labels: lgtm, size/XS

#1041 fix: Purge metrics
  config/grafana/overview.json
Labels: lgtm, size/L

#1042 docs: Form for bug issue creation
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: lgtm, size/M

#1024 feat(watcher): Enable Watcher by default on control-plane
  cmd/flags.go
  config/control-plane/kustomization.yaml
  config/default/kustomization.yaml
  config/load_test/kustomization.yaml
  config/samples/tests/istio-test-resources.yaml
  config/watcher/certificate_setup.yaml
  config/watcher/gateway.yaml
  config/watcher/kustomization.yaml
  config/watcher_local_test/kustomization.yaml
  tests/e2e_test/watcher_test.go
  tests/integration/controller/withwatcher/suite_with_watcher_test.go
Labels: lgtm, size/M

#1064 fix(kustomize): Remove useless patches, introduce missing transformer
  config/control-plane/kustomization.yaml
  config/watcher/kustomization.yaml
  config/watcher_local_test/kustomization.yaml
Labels: lgtm, size/M

#1065 fix: Add missing watch permission for certificates
  config/rbac/role.yaml
  internal/controller/kyma_controller.go
Labels: lgtm, size/XS

#1068 chore: Add LICENCE file
  LICENCE
Labels: lgtm, size/L

#1074 feat(Mandatory Modules): Add Mandatory optional field to the ModuleTemplate Spec
  api/v1beta2/moduletemplate_types.go
  config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
  docs/technical-reference/api/manifest-cr.md
  docs/technical-reference/api/moduleTemplate-cr.md
Labels: lgtm, size/S

#1078 refactor: Change rate to increase
  config/grafana/overview.json
Labels: lgtm, size/S

#1077 fix: Fix markdown lint check
  .github/workflows/lint-markdown-links.yml
  docs/README.md
  docs/technical-reference/api/kyma-cr.md
  docs/technical-reference/architecture.md
  docs/technical-reference/controllers.md
  docs/user-tutorials/01-10-control-plane-quick-start.md
  internal/declarative/README.md
Labels: lgtm, size/M

#1076 fix: Use the Busy Interval for the Warning state
  pkg/queue/requeue_intervals.go
Labels: lgtm, size/XS

#1067 fix: Implement CA Cert Cache
  .github/workflows/test-e2e.yml
  cmd/flags.go
  cmd/main.go
  pkg/testutils/klm.go
  pkg/testutils/watcher.go
  pkg/watcher/certificate.go
  pkg/watcher/certificate_cache.go
  pkg/watcher/skr_webhook_manifest_manager.go
  tests/e2e_test/Makefile
  tests/e2e_test/certificate_rotation_test.go
  tests/e2e_test/suite_test.go
  tests/e2e_test/watcher_test.go
  tests/integration/controller/withwatcher/kyma_controller_test.go
  tests/integration/controller/withwatcher/suite_with_watcher_test.go
  tests/integration/controller/withwatcher/watcher_certificate_test.go
  tests/integration/controller/withwatcher/watcher_controller_helper_test.go
  tests/integration/watcher/certificate_test.go
Labels: lgtm, size/XL

#1084 refactor: Move metrics to internal package
  cmd/main.go
  internal/controller/kyma_controller.go
  internal/controller/purge_controller.go
  internal/pkg/metrics/common.go
  internal/pkg/metrics/kyma_metrics.go
  internal/pkg/metrics/purge_metrics.go
  pkg/module/sync/runner_impl.go
Labels: lgtm, size/L

#1081 fix: Update metrics function
  config/grafana/overview.json
Labels: lgtm, size/S

#1082 chore: Enable ireturn linter
  .golangci.yaml
  cmd/main.go
  internal/declarative/v2/cleanup.go
  internal/declarative/v2/factory.go
  internal/declarative/v2/kube_factory_proxy.go
  internal/declarative/v2/ready_check.go
  internal/declarative/v2/ssa.go
  pkg/status/kyma_helper.go
  pkg/watcher/skr_webhook_manifest_manager.go
  tests/integration/declarative/helper_test.go
Labels: lgtm, size/M

#1087 fix: Remove Secret only when the secret creation time is before the CA Certificate validity
  pkg/watcher/certificate.go
  pkg/watcher/skr_webhook_manifest_manager.go
Labels: lgtm, size/S, cla: yes

#1086 refactor: Change metrics to using struct instead of global value
  cmd/main.go
  go.mod
  internal/controller/kyma_controller.go
  internal/controller/purge_controller.go
  internal/pkg/metrics/common.go
  internal/pkg/metrics/kyma_metrics.go
  internal/pkg/metrics/purge_metrics.go
  pkg/module/sync/runner.go
  pkg/module/sync/runner_impl.go
  pkg/module/sync/runner_test.go
  tests/integration/controller/controlplane/kcp_suite_test.go
  tests/integration/controller/eventfilters/suite_test.go
  tests/integration/controller/kyma/suite_test.go
  tests/integration/controller/purge/suite_test.go
  tests/integration/controller/withwatcher/suite_with_watcher_test.go
Labels: lgtm, size/XL, cla: yes

#1096 feat: Configurable Requeue Interval for Warning State
  cmd/flags.go
  cmd/main.go
  pkg/queue/requeue_intervals.go
  tests/integration/controller/controlplane/kcp_suite_test.go
  tests/integration/controller/eventfilters/suite_test.go
  tests/integration/controller/kyma/suite_test.go
  tests/integration/controller/withwatcher/suite_with_watcher_test.go
Labels: lgtm, size/S, cla: yes

#1092 chore: Refactoring E2E test suite to align with the Glossary and the GWT naming
  .github/workflows/test-e2e.yml
  tests/e2e_test/Makefile
  tests/e2e_test/ca_certificate_rotation_test.go
  tests/e2e_test/kyma_deletion_test.go
  tests/e2e_test/kyma_metrics_test.go
  tests/e2e_test/module_deletion_test.go
  tests/e2e_test/module_upgrade_test.go
  tests/e2e_test/no_default_cr_test.go
  tests/e2e_test/purge_controller_test.go
  tests/e2e_test/purge_metrics_test.go
  tests/e2e_test/status_propagation_test.go
  tests/e2e_test/warning_status_propagation_test.go
  tests/e2e_test/watcher_test.go
Labels: lgtm, size/XL, cla: yes
