Repository kyma-project/lifecycle-manager, pull requests merged in 2024-05, with the labels that each got.

#1515 fix: Fix nil pointer exception in cache
  internal/declarative/v2/client_cache.go
  pkg/remote/client_cache.go
Labels: lgtm, size/S, cla: yes

#1508 chore: Remove useless event
  internal/controller/kyma_controller.go
  internal/declarative/v2/reconciler.go
  pkg/remote/kyma_synchronization_context.go
Labels: lgtm, size/M, cla: yes

#1514 chore: Upgrade controller-runtime version to v0.18.1
  api/go.mod
  api/go.sum
  config/crd/bases/operator.kyma-project.io_manifests.yaml
  config/crd/bases/operator.kyma-project.io_watchers.yaml
  go.mod
  go.sum
  internal/controller/manifest_controller.go
  internal/controller/setup.go
Labels: lgtm, size/L, cla: yes, confirm/helm-update

#1520 refactor: Deprecate kyma provision k3d command
  README.md
  docs/user-tutorials/01-10-control-plane-quick-start.md
Labels: lgtm, size/XS, cla: yes

#1522 chore(deps): Update api module dependencies
  api/go.mod
  api/go.sum
Labels: lgtm, size/L, cla: yes

#1523 chore: Configure Dependabot for api module
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes

#1533 chore(deps): Upgrade helm.sh/helm/v3 to fix vulnerability
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: lgtm, size/S, cla: yes

#1536 chore: Update skr watcher image
  config/watcher/kustomization.yaml
Labels: lgtm, size/XS, cla: yes, confirm/helm-update

#1537 deps: bump controller-runtime to v0.18.2
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: lgtm, size/S, cla: yes

#1539 deps: bump OCM to v0.9.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: lgtm, size/XL, cla: yes

#1532 fix: Copy SKR baseResources on each read to avoid concurrent map read and write
  pkg/watcher/skr_webhook_manifest_manager.go
Labels: lgtm, size/XS, cla: yes

#1540 fix: Use the wait for image action for smoke test pipeline
  .github/workflows/test-smoke.yml
Labels: lgtm, size/S, cla: yes

#1534 fix: Fix concurrent map read and write for ttl cache
  internal/declarative/v2/client_cache.go
  pkg/remote/client_cache.go
Labels: lgtm, size/XS, cla: yes

#1544 deps: bump `istio/api` and `istio/client-go` to `v1.22.0`
  go.mod
  go.sum
Labels: lgtm, size/S, cla: yes

#1546 fix: Filter panels for klm-metrics-service
  config/grafana/overview.json
Labels: lgtm, size/M, cla: yes, confirm/helm-update

#1553 deps: Bump k8s api dependencies to `v0.30.1`
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: lgtm, size/M, cla: yes

#1555 docs: Purge Controller
  docs/technical-reference/architecture.md
  docs/technical-reference/controllers.md
Labels: lgtm, size/S, cla: yes

#1558 chore: Deprecate kyma provision gardener
  docs/developer-tutorials/provision-cluster-and-registry.md
Labels: lgtm, size/M, cla: yes

#1562 fix: Kubebuilder links
  docs/developer-tutorials/starting-operator-with-webhooks.md
  docs/technical-reference/architecture.md
Labels: lgtm, size/XS, cla: yes

#1565 chore: Bump 'Wait for image build' `timeoutSeconds` default
  .github/actions/wait-for-image-build/action.yaml
Labels: lgtm, size/XS, cla: yes

#1569 fix: Remove link to deleted doc
  docs/user-tutorials/02-10-manage-module-with-custom-resource-policy.md
Labels: lgtm, size/XS, cla: yes

#1563 deps: Bump OCM to 0.10.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: lgtm, size/L, cla: yes

#1578 chore: Extend e2e test to include module downgrade test
  tests/e2e/module_upgrade_channel_switch_test.go
Labels: lgtm, size/M, cla: yes

#1583 chore: Refactoring requeue condition
  internal/declarative/v2/reconciler.go
  internal/pkg/metrics/manifest.go
  tests/e2e/kyma_metrics_test.go
Labels: lgtm, size/L, cla: yes
