Repository kyma-project/lifecycle-manager, pull requests merged in 2024-04, with the labels that each got.

#1438 chore: Remove storage version migrator scripts
  scripts/migrator_cleanup.sh
  scripts/storage_version_migrator.sh
Labels: lgtm, size/M, cla: yes

#1436 chore: Namespace transformer
  config/certmanager/certificate.yaml
  config/control-plane/kustomization.yaml
  config/control-plane/patches/adjust_resources_in_deployment.yaml
  config/control-plane/patches/secured_manager_auth_proxy.yaml
  config/control-plane/patches/service_monitor.yaml
  config/control-plane/patches/unique_certificate_name.yaml
  config/control-plane/patches/unique_manager_webhook_patch.yaml
  config/default/kustomization.yaml
  config/default/manager_config_patch.yaml
  config/default/manager_webhook_patch.yaml
  config/default/namespace_create.yaml
  config/istio/ap.yaml
  config/istio/patches/exclude_webhook_port.yaml
  config/load_test/manager_webhook_patch.yaml
  config/load_test/patches/adjust_resources_in_deployment.yaml
  config/manager/manager.yaml
  config/manager/metrics_service.yaml
  config/prometheus/monitor.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/manifest_role.yaml
  config/rbac/metrics_clusterrole_binding.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/watcher/gateway.yaml
  config/watcher/operator_v1beta2_watcher.yaml
  config/watcher_local_test/patches/adjust_resources_for_local_setup.yaml
  config/watcher_local_test/patches/servicemonitor_delete.yaml
  config/webhook/service.yaml
Labels: lgtm, size/L, cla: yes

#1441 fix: Race condition in drop stored versions
  cmd/main.go
  internal/crd/storage_version_dropper.go
  internal/crd/storage_version_dropper_test.go
Labels: lgtm, size/M, cla: yes

#1450 chore: Bump golang from `1.22.1` to `1.22.2`
  Dockerfile
  api/go.mod
  go.mod
  go.sum
Labels: lgtm, size/S, cla: yes

#1444 chore: Stop running tests for post main jobs
  .github/workflows/test-e2e.yml
  .github/workflows/test-smoke.yml
Labels: lgtm, size/XS, cla: yes

#1443 chore: Configure leader election timeout
  cmd/main.go
  internal/pkg/flags/flags.go
  internal/pkg/flags/flags_test.go
Labels: lgtm, size/M, cla: yes

#1445 feat: TTL client caches
  internal/controller/kyma_controller.go
  internal/declarative/v2/client_cache.go
  internal/declarative/v2/options.go
  internal/declarative/v2/reconciler.go
  internal/manifest/client.go
  pkg/remote/client_cache.go
  pkg/remote/client_cache_test.go
  pkg/remote/client_lookup.go
  unit-test-coverage.yaml
Labels: lgtm, size/L, cla: yes

#1423 fix: Remove some privileges from KLM
  .github/workflows/test-e2e.yml
  .golangci.yaml
  Makefile
  cmd/main.go
  config/control-plane/kustomization.yaml
  config/default/kustomization.yaml
  config/load_test/kustomization.yaml
  config/rbac/cluster_bindings/clusterrole_binding.yaml
  config/rbac/cluster_bindings/kustomization.yaml
  config/rbac/cluster_bindings/manifest_clusterrole_binding.yaml
  config/rbac/cluster_bindings/metrics_clusterrole_binding.yaml
  config/rbac/common/crd_clusterrole.yaml
  config/rbac/common/crd_clusterrole_binding.yaml
  config/rbac/common/kustomization.yaml
  config/rbac/common/leader_election_role.yaml
  config/rbac/common/leader_election_role_binding.yaml
  config/rbac/common/manifest_clusterrole.yaml
  config/rbac/common/metrics_clusterrole.yaml
  config/rbac/common/role.yaml
  config/rbac/common/service_account.yaml
  config/rbac/namespace_bindings/kustomization.yaml
  config/rbac/namespace_bindings/manifest_role_binding.yaml
  config/rbac/namespace_bindings/metrics_role_binding.yaml
  config/rbac/namespace_bindings/role_binding.yaml
  config/samples/tests/istio-test-resources.yaml
  internal/controller/kyma_controller.go
  internal/controller/watcher_controller.go
  internal/istio/client.go
  internal/pkg/flags/flags.go
  internal/util.go
  pkg/testutils/rbac.go
  tests/e2e/Makefile
  tests/e2e/rbac_privileges_test.go
  tests/integration/controller/controlplane/kcp_suite_test.go
  tests/integration/controller/eventfilters/suite_test.go
  tests/integration/controller/kyma/suite_test.go
  tests/integration/controller/mandatorymodule/deletion/suite_test.go
  tests/integration/controller/mandatorymodule/installation/suite_test.go
  tests/integration/controller/manifest/custom_resource_check/suite_test.go
  tests/integration/controller/manifest/suite_test.go
  tests/integration/controller/purge/suite_test.go
  tests/integration/controller/withwatcher/suite_with_watcher_test.go
  tests/integration/controller/withwatcher/watcher_controller_test.go
Labels: lgtm, size/XL, cla: yes, confirm/helm-update

#1446 docs: Fix local test setup scripts
  docs/developer-tutorials/local-test-setup.md
Labels: lgtm, size/S, cla: yes

#1454 chore: Enhance watcher dashboard
  config/grafana/watcher.json
Labels: lgtm, size/L, cla: yes, confirm/helm-update

#1459 deps: Upgrade controller-runtime to 0.17.3
  go.mod
  go.sum
Labels: lgtm, size/XS, cla: yes

#1461 chore: Remove manifest rolebinding in kyma-system and istio-system namespaces
  cmd/main.go
  config/control-plane/kustomization.yaml
  config/rbac/namespace_bindings/manifest_role_binding.yaml
  docs/technical-reference/api/moduleTemplate-cr.md
  internal/cache_options.go
  internal/pkg/flags/flags.go
  internal/util.go
  tests/e2e/rbac_privileges_test.go
  tests/integration/controller/controlplane/kcp_suite_test.go
  tests/integration/controller/eventfilters/suite_test.go
  tests/integration/controller/kyma/suite_test.go
  tests/integration/controller/mandatorymodule/deletion/suite_test.go
  tests/integration/controller/mandatorymodule/installation/suite_test.go
  tests/integration/controller/manifest/custom_resource_check/suite_test.go
  tests/integration/controller/manifest/suite_test.go
  tests/integration/controller/purge/suite_test.go
  tests/integration/controller/withwatcher/suite_with_watcher_test.go
Labels: lgtm, size/L, cla: yes, confirm/helm-update

#1458 fix: Update Manifest lastOperation when an error occurs
  internal/declarative/v2/reconciler.go
Labels: lgtm, size/S, cla: yes

#1451 chore: Introduce shared GitHub Actions
  .github/actions/configure-hosts/action.yaml
  .github/actions/create-k3d-cluster/action.yaml
  .github/actions/deploy-cert-manager/action.yaml
  .github/actions/deploy-istio/action.yaml
  .github/actions/deploy-lifecycle-manager-e2e/action.yaml
  .github/actions/deploy-lifecycle-manager/action.yaml
  .github/actions/deploy-template-operator/action.yaml
  .github/actions/export-kubeconfigs/action.yaml
  .github/actions/get-configuration/action.yaml
  .github/actions/install-cmctl/action.yaml
  .github/actions/install-istioctl/action.yaml
  .github/actions/install-k3d/action.yaml
  .github/actions/install-kubectl/action.yaml
  .github/actions/install-kyma-cli/action.yaml
  .github/actions/setup-test-clusters/action.yaml
  .github/actions/setup-tools/action.yaml
  .github/actions/switch-kubectl-context/action.yaml
  .github/actions/wait-for-image-build/action.yaml
  .github/workflows/test-e2e.yaml
  .github/workflows/test-e2e.yml
Labels: lgtm, size/XL, cla: yes

#1469 chore: Sum count to avoid having multiple gauges
  config/grafana/status.json
Labels: lgtm, size/XS, cla: yes, confirm/helm-update

#1475 chore: Add skr args input to setup test clusters action
  .github/actions/setup-test-clusters/action.yaml
Labels: lgtm, size/XS, cla: yes

#1476 chore: Remove deprecated ControllerManagerConfig
  config/default/kustomization.yaml
  config/default/manager_config_patch.yaml
  config/load_test/kustomization.yaml
  config/manager/controller_manager_config.yaml
  config/manager/kustomization.yaml
  docs/developer-tutorials/starting-operator-with-webhooks.md
  docs/technical-reference/api/moduleTemplate-cr.md
  internal/util_test.go
  pkg/test_samples/oci/template-operator-manifest.yaml
  pkg/test_samples/raw-manifest.yaml
Labels: lgtm, size/L, cla: yes, confirm/helm-update

#1474 fix: Update lastOperation.operation when manifest is back to ready
  internal/declarative/v2/reconciler.go
  pkg/testutils/manifest.go
  tests/integration/controller/manifest/manifest_controller_test.go
Labels: lgtm, size/M, cla: yes

#1465 test: Add check for module version in Kyma.Modules.Status in E2E test
  docs/technical-reference/api/moduleTemplate-cr.md
  pkg/testutils/kyma.go
  pkg/testutils/manifest.go
  pkg/testutils/moduletemplate.go
  tests/e2e/module_upgrade_new_version_test.go
Labels: lgtm, size/M, cla: yes

#1498 feat: Hardcode Istio Sidecar Injection Annotation
  pkg/remote/kyma_synchronization_context.go
Labels: lgtm, size/XS, cla: yes

#1499 fix: Inject istio annotation
  pkg/remote/kyma_synchronization_context.go
Labels: lgtm, size/XS, cla: yes

#1505 fix: Fix installing cmctl action
  .github/actions/install-cmctl/action.yaml
Labels: lgtm, size/XS, cla: yes

#1495 fix: Return error when doing ssa for diff in declarative library
  internal/declarative/v2/reconciler.go
Labels: lgtm, size/M, cla: yes

#1496 refactor: E2E suite test cluster configuration
  .github/actions/patch-skr-hostname-in-kcp/action.yaml
  .github/actions/setup-test-clusters/action.yaml
  config/watcher_local_test/kustomization.yaml
  scripts/tests/add_skr_host_to_coredns.sh
  scripts/tests/remove_skr_host_from_coredns.sh
  tests/e2e/deprovision_test.go
  tests/e2e/utils_test.go
Labels: lgtm, size/M, cla: yes
