Repository kyma-project/lifecycle-manager, pull requests merged in 2024-08, with the labels that each got.

#1721 refactor: Remove Redundancy and duplication, check for same naming pattern on Kustomize
  .github/actions/deploy-lifecycle-manager-e2e/action.yaml
  .github/workflows/test-smoke.yml
  Makefile
  config/certmanager/certificate.yaml
  config/control-plane/kustomization.yaml
  config/control-plane/patches/service_monitor.yaml
  config/control-plane/patches/unique_certificate_name.yaml
  config/control-plane/patches/unique_manager_webhook_patch.yaml
  config/default/kustomization.yaml
  config/default/manager_webhook_patch.yaml
  config/grafana/overview.json
  config/load_test/kustomization.yaml
  config/load_test/manager_webhook_patch.yaml
  config/manager/metrics_service.yaml
  config/prometheus/monitor.yaml
  config/rbac/cluster_bindings/clusterrole_binding.yaml
  config/rbac/cluster_bindings/kustomization.yaml
  config/rbac/cluster_bindings/manifest_clusterrole_binding.yaml
  config/rbac/cluster_bindings/metrics_clusterrole_binding.yaml
  config/rbac/common/crd_clusterrole.yaml
  config/rbac/common/crd_clusterrole_binding.yaml
  config/rbac/common/kustomization.yaml
  config/rbac/common/leader_election_role.yaml
  config/rbac/common/leader_election_role_binding.yaml
  config/rbac/common/manifest_clusterrole.yaml
  config/rbac/common/metrics_clusterrole.yaml
  config/rbac/common/role.yaml
  config/rbac/namespace_bindings/kustomization.yaml
  config/rbac/namespace_bindings/manifest_role_binding.yaml
  config/rbac/namespace_bindings/metrics_role_binding.yaml
  config/rbac/namespace_bindings/role_binding.yaml
  config/rbac/namespace_bindings/skr_role.yaml
  config/rbac/namespace_bindings/skr_role_binding.yaml
  config/rbac/namespace_bindings/watcher_certmanager_role.yaml
  config/rbac/namespace_bindings/watcher_certmanager_role_binding.yaml
  config/samples/tests/istio-test-resources.yaml
  config/watcher/certificate_setup.yaml
  config/watcher/gateway.yaml
  config/watcher/operator_v1beta2_watcher.yaml
  config/watcher_local_test/kustomization.yaml
  config/watcher_local_test/patches/servicemonitor_delete.yaml
  internal/controller/manifest/controller.go
  internal/pkg/flags/flags.go
  internal/pkg/flags/flags_test.go
  tests/e2e/ca_certificate_rotation_test.go
  tests/e2e/rbac_privileges_test.go
  tests/e2e/watcher_test.go
  tests/integration/controller/withwatcher/suite_test.go
  tests/integration/controller/withwatcher/watcher_controller_helper_test.go
  tests/integration/watcher/certificate_test.go
Labels: lgtm, size/L, cla: yes

#1747 chore: Disable prometheus config for control-plane profile
  .github/workflows/test-smoke.yml
  config/control-plane/kustomization.yaml
  config/control-plane/patches/service_monitor.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/metrics_clusterrole.yaml
  config/prometheus/metrics_role_binding.yaml
  config/rbac/common/kustomization.yaml
  config/rbac/namespace_bindings/kustomization.yaml
  config/watcher_local_test/kustomization.yaml
  config/watcher_local_test/patches/servicemonitor_delete.yaml
  tests/e2e/rbac_privileges_test.go
Labels: lgtm, size/M, cla: yes

#1746 chore: Drop load test config
  Makefile
  config/load_test/kustomization.yaml
  config/load_test/manager_webhook_patch.yaml
  config/load_test/metrics_cluster_role_binding.yaml
  config/load_test/metrics_role.yaml
  config/load_test/metrics_role_binding.yaml
  config/load_test/patches/adjust_resources_in_deployment.yaml
  config/load_test/webhookcainjection_patch.yaml
Labels: lgtm, size/L, cla: yes

#1757 fix: Ignore not found error for DeleteVirtualService
  internal/controller/watcher/controller.go
Labels: lgtm, size/XS, cla: yes

#1758 deps: bump golang.org/x/sync from 0.7.0 to 0.8.0
  go.mod
  go.sum
Labels: lgtm, size/XS, cla: yes

#1761 chore: Drop prometheus config
  config/prometheus/commonlabels_override.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/metrics_clusterrole.yaml
  config/prometheus/metrics_role_binding.yaml
  config/prometheus/monitor.yaml
Labels: lgtm, size/M, cla: yes

#1767 chore: Update sec scanner
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1773 chore(deps): Bump Controller runtime
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: lgtm, size/S, cla: yes

#1770 chore(deps): Bump OCM package to 0.13.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  pkg/img/parse.go
  tests/integration/controller/kyma/manifest_test.go
Labels: lgtm, size/XXL, cla: yes

#1698 feat: Support "application/x-tar" media type in the module template
  .github/actions/deploy-template-operator/action.yaml
  .github/workflows/test-e2e.yaml
  api/v1beta2/manifest_types.go
  docs/technical-reference/api/manifest-cr.md
  internal/controller/kyma/controller.go
  internal/controller/mandatorymodule/installation_controller.go
  internal/controller/manifest/controller.go
  internal/manifest/README.md
  internal/manifest/auth/keychain_lookup.go
  internal/manifest/img/layer.go
  internal/manifest/img/parse.go
  internal/manifest/img/parse_test.go
  internal/manifest/img/pathextractor.go
  internal/manifest/img/pathextractor_test.go
  internal/manifest/parse.go
  internal/manifest/parser/template_to_module.go
  internal/manifest/spec_resolver.go
  pkg/test_samples/oci/rendered.tar
  pkg/testutils/builder/moduletemplate.go
  pkg/testutils/manifest.go
  tests/e2e/Makefile
  tests/e2e/ocm_compatilble_module_template_test.go
  tests/integration/controller/kyma/manifest_test.go
  tests/integration/controller/mandatorymodule/deletion/controller_test.go
  tests/integration/controller/manifest/custom_resource_check/manifest_test.go
  tests/integration/controller/manifest/custom_resource_check/suite_test.go
  tests/integration/controller/manifest/manifest_controller_test.go
  tests/integration/controller/manifest/ready_check_test.go
  tests/integration/controller/manifest/suite_test.go
  tests/moduletemplates/moduletemplate_template_operator_regular_new_ocm.yaml
  tests/moduletemplates/operator_v1beta2_moduletemplate_kcp-module-cred-label.yaml
  tests/moduletemplates/operator_v1beta2_moduletemplate_kcp-module.yaml
  tests/moduletemplates/operator_v1beta2_moduletemplate_kcp-module_updated.yaml
  tests/moduletemplates/operator_v1beta2_moduletemplate_ocm.software.v3alpha1.yaml
Labels: lgtm, size/XL, cla: yes

#1782 chore: Bump K8s api and controller-runtime deps to 0.31.0 and 0.19.0
  api/go.mod
  api/go.sum
  cmd/main.go
  go.mod
  go.sum
  internal/controller/kyma/setup.go
  internal/controller/manifest/setup.go
  internal/rate_limiter.go
  pkg/watch/restricted_enqueue_request_for_owner.go
Labels: lgtm, size/L, cla: yes

#1789 chore: Improve document
  docs/technical-reference/api/changelog.md
  docs/technical-reference/api/manifest-cr.md
Labels: lgtm, size/XS, cla: yes

#1787 docs: Fix User Docs with outdated commands
  docs/user-tutorials/02-10-manage-module-with-custom-resource-policy.md
Labels: lgtm, size/XS, cla: yes

#1788 docs: Update technical reference documentation
  docs/technical-reference/controllers.md
  docs/technical-reference/running-modes.md
Labels: lgtm, size/S, cla: yes

#1794 chore: Increase cert key size to '4096'
  cmd/main.go
  config/manager/manager.yaml
  config/watcher/certificate_setup.yaml
  internal/pkg/flags/flags.go
  internal/pkg/flags/flags_test.go
  pkg/watcher/certificate_manager.go
Labels: lgtm, size/M, cla: yes

#1797 chore: Update security scanners config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1792 fix: Replace RestrictedEnqueueRequestForOwner with EnqueueRequestForOwner
  internal/controller/kyma/setup.go
  internal/controller/mandatorymodule/setup.go
  internal/controller/manifest/setup.go
  pkg/watch/restricted_enqueue_request_for_owner.go
Labels: lgtm, size/L, cla: yes

#1804 chore: Add check for test changes
  .github/workflows/check-test-changes.yaml
Labels: lgtm, size/M, cla: yes

#1806 chore: Only check for test changes if there are also code changes
  .github/workflows/check-test-changes.yaml
Labels: lgtm, size/XS, cla: yes

#1748 feat: Module catalog improvements implementation
  .github/actions/deploy-template-operator/action.yaml
  .github/workflows/test-e2e.yaml
  api/shared/channel.go
  api/v1beta2/kyma_types.go
  api/v1beta2/kyma_types_test.go
  api/v1beta2/moduletemplate_types.go
  api/v1beta2/moduletemplate_types_test.go
  api/v1beta2/zz_generated.deepcopy.go
  internal/controller/kyma/controller.go
  internal/pkg/metrics/kyma.go
  internal/remote/skr_context.go
  internal/remote/skr_context_test.go
  pkg/module/parse/template_to_module.go
  pkg/templatelookup/availableModules.go
  pkg/templatelookup/availableModules_test.go
  pkg/templatelookup/regular.go
  pkg/templatelookup/regular_test.go
  pkg/testutils/moduletemplate.go
  pkg/testutils/utils.go
  tests/e2e/Makefile
  tests/e2e/module_install_by_version_test.go
  tests/integration/controller/kyma/kyma_module_channel_test.go
  tests/moduletemplates/moduletemplate_template_operator_v2_direct_version.yaml
  unit-test-coverage.yaml
Labels: lgtm, size/XXL, cla: yes

#1801 chore: Bump golangci-lint action
  .github/workflows/lint-golangci.yml
  .golangci.yaml
  Makefile
  cmd/main.go
  internal/controller/mandatorymodule/deletion_controller.go
  internal/declarative/v2/default_transforms_test.go
  internal/declarative/v2/inmemory_rendered.go
  internal/declarative/v2/ssa.go
  internal/declarative/v2/ssa_test.go
  internal/descriptor/cache/key_test.go
  internal/istio/httproute.go
  internal/istio/httproute_test.go
  internal/istio/virtualservice_test.go
  internal/pkg/flags/flags_test.go
  internal/pkg/metrics/metrics_test.go
  internal/pkg/resources/cleanup.go
  internal/pkg/resources/cleanup_test.go
  internal/remote/crd_upgrade_test.go
  internal/remote/remote_catalog.go
  internal/remote/skr_context_test.go
  internal/tests/api/kyma_types_test.go
  internal/tests/api/moduletemplate_webhook_test.go
  internal/util_test.go
  pkg/templatelookup/mandatory.go
  pkg/templatelookup/regular.go
  pkg/testutils/manifest.go
  pkg/watcher/skr_webhook_manifest_manager.go
  pkg/watcher/skr_webhook_resources.go
  tests/integration/controller/mandatorymodule/deletion/controller_test.go
  tests/integration/controller/purge/controller_test.go
Labels: lgtm, size/L, cla: yes
