Repository kyma-project/lifecycle-manager, pull requests merged in 2024-02, with the labels that each got.

#1284 chore(SDLC, quality-gate): Adds a quality gate for a unit test coverage
  .github/workflows/verify-unit-test-coverage.yml
  unit-test-coverage.yaml
Labels: lgtm, size/M, cla: yes

#1279 chore: Add script for storage version migrator
  scripts/migrator_cleanup.sh
  scripts/storage_version_migrator.sh
Labels: lgtm, size/M, cla: yes

#1289 fix: Adjust script based on SREs comments
  scripts/migrator_cleanup.sh
  scripts/storage_version_migrator.sh
Labels: lgtm, size/S, cla: yes

#1273 fix: Introduce a Go routine to remove no longer existing Kymas from the metrics
  .github/workflows/test-e2e.yml
  .golangci.yaml
  cmd/main.go
  go.mod
  go.sum
  internal/pkg/flags/flags.go
  internal/pkg/metrics/kyma.go
  internal/pkg/metrics/kyma_test.go
  pkg/testutils/metrics.go
  tests/e2e/kyma_metrics_test.go
Labels: lgtm, size/L, cla: yes

#1291 fix: Fix storage version migrator script
  scripts/storage_version_migrator.sh
Labels: lgtm, size/XS, cla: yes

#1292 chore: Bump e2e CM version to align with prod
  .github/workflows/test-e2e.yml
Labels: lgtm, size/XS, cla: yes

#1294 chore: Add log message for the metrics cleanup job
  internal/pkg/metrics/kyma.go
Labels: lgtm, size/XS, cla: yes

#1297 feat: Introduce different requeue after interval to control the frequency of unexpected requeue events
  cmd/main.go
  internal/controller/kyma_controller.go
  internal/controller/manifest_controller.go
  internal/declarative/v2/options.go
  internal/declarative/v2/reconciler.go
  internal/pkg/metrics/common.go
  internal/pkg/metrics/kyma.go
  internal/pkg/metrics/manifest.go
  pkg/queue/requeue_intervals.go
  tests/e2e/kyma_metrics_test.go
  tests/integration/controller/manifest/custom_resource_check/suite_test.go
  tests/integration/controller/manifest/suite_test.go
  tests/integration/declarative/declarative_test.go
Labels: lgtm, size/L, cla: yes

#1301 feat: Set Kyma Module Status to `Warning` if ModuleTemplate is not found
  pkg/module/sync/runner.go
  tests/integration/controller/kyma/kyma_test.go
Labels: lgtm, size/L, cla: yes

#1298 chore: Improve detection of connection errors
  internal/declarative/v2/reconciler.go
  pkg/util/error.go
Labels: lgtm, size/S, cla: yes

#1302 fix: Fix flapping module state between Warning and Deleting
  .github/workflows/test-e2e.yml
  internal/declarative/v2/reconciler.go
  tests/e2e/warning_status_propagation_test.go
Labels: lgtm, size/M, cla: yes

#1313 chore: Unwrap `apierrors.IsUnauthorized`
  internal/controller/kyma_controller.go
  pkg/util/error.go
Labels: lgtm, size/S, cla: yes

#1314 feat: Add k8s version option to e2e
  .github/workflows/test-e2e.yml
Labels: lgtm, size/S, cla: yes

#1311 feat: Explicit versioning
  Dockerfile
  Makefile
  cmd/main.go
Labels: lgtm, size/S, cla: yes

#1331 deps: Bump controller runtime to v0.17.2
  go.mod
  go.sum
  internal/declarative/v2/ssa_test.go
Labels: lgtm, size/L, cla: yes

#1309 docs: Use cert-manager 1.13.3 in local test setup script
  docs/developer-tutorials/local-test-setup.md
Labels: lgtm, size/XS, cla: yes

#1312 feat: Deprecation of RemoteTargetRef in v1beta2
  api/shared/operator_labels.go
  api/v1beta2/kyma_types.go
  config/crd/bases/operator.kyma-project.io_kymas.yaml
  docs/technical-reference/api/kyma-cr.md
  internal/controller/kyma_controller.go
  internal/declarative/v2/reconciler.go
  internal/declarative/v2/spec.go
  internal/manifest/spec_resolver.go
  pkg/module/common/module.go
  pkg/templatelookup/regular.go
  pkg/testutils/moduletemplate.go
  tests/integration/controller/controlplane/kyma_remote_sync_test.go
Labels: lgtm, size/L, cla: yes

#1324 feat: Add release workflow
  .github/workflows/create-release.yaml
  scripts/release/create_changelog.sh
  scripts/release/create_draft_release.sh
  scripts/release/get_last_release.sh
  scripts/release/get_release_by_tag.sh
  scripts/release/publish_release.sh
  scripts/release/validate_release_tag.sh
  scripts/release/wait_for_image.sh
Labels: lgtm, size/L, cla: yes

#1334 chore: Mark v1beta1 version as unserved
  api/v1beta1/kyma_types.go
  api/v1beta1/manifest_types.go
  api/v1beta1/moduletemplate_types.go
  api/v1beta1/watcher_types.go
  config/crd/bases/operator.kyma-project.io_kymas.yaml
  config/crd/bases/operator.kyma-project.io_manifests.yaml
  config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
  config/crd/bases/operator.kyma-project.io_watchers.yaml
Labels: lgtm, size/S, cla: yes

#1340 fix: Fix E2E test
  tests/e2e/warning_status_propagation_test.go
Labels: lgtm, size/S, cla: yes

#1345 chore: Extract and test CRD caching
  cmd/main.go
  internal/controller/kyma_controller.go
  internal/crd/cache.go
  internal/crd/cache_test.go
  pkg/cache/crd_cache.go
  pkg/remote/crd_upgrade.go
  tests/integration/controller/controlplane/helper_test.go
  tests/integration/controller/controlplane/kcp_suite_test.go
  tests/integration/controller/eventfilters/suite_test.go
  tests/integration/controller/kyma/suite_test.go
  tests/integration/controller/withwatcher/suite_with_watcher_test.go
  unit-test-coverage.yaml
Labels: lgtm, size/L, cla: yes

#1342 chore: Refactor `istio` pkg
  internal/controller/setup.go
  internal/controller/watcher_controller.go
  internal/istio/client.go
  internal/istio/errors.go
  internal/istio/httproute.go
  internal/istio/httproute_test.go
  internal/istio/virtualservice.go
  internal/istio/virtualservice_test.go
  pkg/istio/client.go
  tests/integration/controller/withwatcher/watcher_controller_helper_test.go
  tests/integration/controller/withwatcher/watcher_controller_test.go
  unit-test-coverage.yaml
Labels: lgtm, size/XXL, cla: yes
