Repository kyma-project/lifecycle-manager, pull requests merged in 2024-01, with the labels that each got.

#1215 refactor: Use logger from context instead
  internal/controller/purge_controller.go
  internal/pkg/metrics/purge.go
Labels: lgtm, size/S, cla: yes

#1220 feat: Add E2E Test For Module Upgrade through New Version
  .github/workflows/test-e2e.yml
  pkg/testutils/utils.go
  tests/e2e/Makefile
  tests/e2e/module_upgrade_channel_switch_test.go
  tests/e2e/module_upgrade_new_version_test.go
Labels: lgtm, size/L, cla: yes

#1212 fix: Increase baseDelay for ExponentialFailureRateLimiter
  config/control-plane/kustomization.yaml
Labels: lgtm, size/XS, cla: yes

#1222 feat: Suppress "Unauthorized" errors
  internal/declarative/v2/ssa.go
Labels: lgtm, size/M, cla: yes

#1219 feat(metrics_test.go): Add Metrics Name Unit Test
  internal/pkg/metrics/metrics_test.go
  internal/pkg/metrics/purge.go
Labels: lgtm, size/M, cla: yes

#1234 feat: Invalidate manifest client cache
  internal/declarative/v2/client_cache.go
  internal/declarative/v2/reconciler.go
  internal/manifest/client.go
Labels: lgtm, size/S, cla: yes

#1233 deps: Bump watcher image to latest build
  config/watcher/kustomization.yaml
Labels: lgtm, size/XS, cla: yes

#1231 docs: Mandatory module controller documentation
  docs/technical-reference/controllers.md
Labels: lgtm, size/XS, cla: yes

#1235 feat: Split overview and watcher dashboards
  config/grafana/overview.json
  config/grafana/watcher.json
Labels: lgtm, size/XXL, cla: yes

#1237 fix: Create CM for watcher dashboard
  config/grafana/kustomization.yaml
Labels: lgtm, size/XS, cla: yes

#1248 chore: Move flags.go to internal/pkg
  Dockerfile
  Makefile
  cmd/flags.go
  cmd/main.go
  internal/controller/kyma_controller.go
  internal/pkg/flags/flags.go
  internal/pkg/flags/flags_test.go
  tests/integration/controller/controlplane/kcp_suite_test.go
  tests/integration/controller/controlplane/kyma_remote_sync_test.go
  tests/integration/controller/eventfilters/suite_test.go
  tests/integration/controller/kyma/manifest_test.go
  tests/integration/controller/kyma/suite_test.go
  tests/integration/controller/mandatorymodules/suite_test.go
  tests/integration/controller/withwatcher/suite_with_watcher_test.go
  tests/integration/controller/withwatcher/watcher_certificate_test.go
Labels: lgtm, size/XL, cla: yes

#1251 feat: Dont sync Deps if moduletemplate is mandatory
  api/v1beta2/moduletemplate_types.go
  internal/tests/api/modulesync_test.go
  tests/e2e/mandatory_module_test.go
Labels: lgtm, size/M, cla: yes

#1255 feat: Add Warning state to dashboard
  config/grafana/status.json
Labels: lgtm, size/S, cla: yes

#1257 fix: No such host in purge reconciler
  internal/controller/purge_controller.go
  pkg/util/error.go
Labels: lgtm, size/M, cla: yes

#1258 chore: Add more logs to debug the no such host error on dev
  pkg/remote/client_lookup.go
  pkg/remote/cluster_client.go
Labels: lgtm, size/S, cla: yes

#1263 fix: Adjust log messages
  internal/controller/kyma_controller.go
  internal/controller/purge_controller.go
  pkg/remote/client_lookup.go
Labels: lgtm, size/XS, cla: yes

#1264 fix: Display debug messages as Info level
  pkg/remote/client_lookup.go
  pkg/remote/cluster_client.go
Labels: lgtm, size/S, cla: yes

#1265 chore: Debug logging for Purge Reconciler
  internal/controller/purge_controller.go
Labels: lgtm, size/S, cla: yes

#1261 chore: Remove descriptor signing verification
  cmd/main.go
  internal/controller/kyma_controller.go
  internal/controller/mandatory_modules_installation_controller.go
  internal/pkg/flags/flags.go
  pkg/module/parse/template_to_module.go
  pkg/signature/verifier.go
  tests/integration/controller/controlplane/kcp_suite_test.go
  tests/integration/controller/eventfilters/suite_test.go
  tests/integration/controller/kyma/suite_test.go
  tests/integration/controller/withwatcher/suite_with_watcher_test.go
Labels: lgtm, size/L, cla: yes

#1260 chore: Remove Manifest finalizers when access secret is gone and it's under deletion
  docs/user-tutorials/02-10-manage-module-with-custom-resource-policy.md
  internal/declarative/v2/reconciler.go
  internal/manifest/client.go
  tests/e2e/deletion_test.go
Labels: lgtm, size/S, cla: yes

#1270 chore: Invalidate client cache when connection is refused or unauthorized
  internal/declarative/v2/reconciler.go
  pkg/util/error.go
Labels: lgtm, size/M, cla: yes

#1267 chore: Remove logs that were added for debugging
  internal/controller/kyma_controller.go
  internal/controller/purge_controller.go
  pkg/remote/client_lookup.go
  pkg/remote/cluster_client.go
  pkg/util/error.go
Labels: lgtm, size/M, cla: yes

#1250 docs: Update CLI Enable Module Command
  .github/workflows/test-smoke.yml
  README.md
  docs/modularization.md
  docs/user-tutorials/02-10-manage-module-with-custom-resource-policy.md
Labels: lgtm, size/S, cla: yes

#1272 fix: Add container name to metrics to exclude metrics which are not related
  config/grafana/overview.json
Labels: lgtm, size/M, cla: yes

#1271 chore: Add Explaination For Exhaustruct LInter Disabling
  .golangci.yaml
Labels: lgtm, size/XS, cla: yes
