Repository kyma-project/lifecycle-manager, pull requests merged in 2024-06, with the labels that each got.

#1592 feat: add api changes checker pipeline
  .github/workflows/check-api-changes.yaml
Labels: size/M, cla: yes

#1594 Feature/#1492 api changes GitHub actions
  .github/workflows/check-api-changes.yaml
Labels: size/M, cla: yes

#1597 Feature/#1492 api changes GitHub actions
  .github/workflows/check-api-changes.yaml
Labels: size/XS, cla: yes

#1584 feat: Wrap event recorder
  .golangci.yaml
  cmd/main.go
  docs/technical-reference/architecture.md
  docs/technical-reference/controllers.md
  internal/controller/kyma/controller.go
  internal/controller/kyma/setup.go
  internal/controller/mandatorymodule/deletion_controller.go
  internal/controller/mandatorymodule/installation_controller.go
  internal/controller/mandatorymodule/setup.go
  internal/controller/manifest/controller.go
  internal/controller/manifest/setup.go
  internal/controller/purge/controller.go
  internal/controller/purge/setup.go
  internal/controller/setup.go
  internal/controller/watcher/controller.go
  internal/controller/watcher/setup.go
  internal/event/event.go
  internal/event/event_test.go
  internal/istio/client.go
  internal/remote/skr_context.go
  internal/remote/skr_context_provider.go
  pkg/adapter/eventing_adapter.go
  pkg/testutils/skrcontextimpl/dual_cluster.go
  pkg/testutils/skrcontextimpl/single_cluster.go
  pkg/watch/change_handler_client.go
  pkg/watch/mandatory_template_change.go
  pkg/watch/template_change.go
  tests/integration/apiwebhook/moduletemplate_crd_validation_test.go
  tests/integration/apiwebhook/ocm_test.go
  tests/integration/apiwebhook/suite_test.go
  tests/integration/controller/eventfilters/suite_test.go
  tests/integration/controller/kcp/suite_test.go
  tests/integration/controller/kyma/suite_test.go
  tests/integration/controller/mandatorymodule/deletion/controller_test.go
  tests/integration/controller/mandatorymodule/deletion/suite_test.go
  tests/integration/controller/mandatorymodule/installation/controller_test.go
  tests/integration/controller/mandatorymodule/installation/suite_test.go
  tests/integration/controller/manifest/custom_resource_check/manifest_test.go
  tests/integration/controller/manifest/custom_resource_check/suite_test.go
  tests/integration/controller/manifest/keychain_test.go
  tests/integration/controller/manifest/manifest_controller_test.go
  tests/integration/controller/manifest/ready_check_test.go
  tests/integration/controller/manifest/suite_test.go
  tests/integration/controller/purge/controller_test.go
  tests/integration/controller/purge/suite_test.go
  tests/integration/controller/withwatcher/controller_test.go
  tests/integration/controller/withwatcher/suite_test.go
  tests/integration/controller/withwatcher/watcher_certificate_test.go
  tests/integration/controller/withwatcher/watcher_controller_helper_test.go
  tests/integration/controller/withwatcher/watcher_controller_test.go
  unit-test-coverage.yaml
Labels: lgtm, size/XXL, cla: yes

#1603 docs: Apply Markdown linting in Lifecycle Manager
  .markdownlint.yaml
  docs/README.md
  docs/developer-tutorials/README.md
  docs/developer-tutorials/config-private-registry.md
  docs/developer-tutorials/local-test-setup.md
  docs/developer-tutorials/prepare-gcr-registry.md
  docs/developer-tutorials/provision-cluster-and-registry.md
  docs/developer-tutorials/starting-operator-with-webhooks.md
  docs/technical-reference/api/README.md
  docs/technical-reference/api/changelog.md
  docs/technical-reference/api/kyma-cr.md
  docs/technical-reference/api/moduleTemplate-cr.md
  docs/technical-reference/architecture.md
  docs/technical-reference/controllers.md
  docs/technical-reference/running-modes.md
  docs/user-tutorials/01-10-control-plane-quick-start.md
  markdown_heading_capitalization.js
Labels: lgtm, size/L, cla: yes

#1602 feat: Add Workflow to Check API Changes in PR
  .github/workflows/check-api-compatibility.yaml
  api-version-compatibility-config.yaml
Labels: lgtm, size/M, cla: yes

#1617 chore: E2E tests to use a `*.localhost` image registry
  .github/actions/configure-hosts/action.yaml
  .github/actions/deploy-template-operator/action.yaml
  .github/actions/setup-test-clusters/action.yaml
Labels: lgtm, size/M, cla: yes

#1625 chore: Bump `cert-manager` from `1.14.5` to `1.15.0`
  .github/actions/get-configuration/action.yaml
  go.mod
  go.sum
Labels: lgtm, size/L, cla: yes

#1626 chore: Bump golang consistently to 1.22.4
  Dockerfile
  api/go.mod
  go.mod
Labels: lgtm, size/XS, cla: yes

#1627 chore: Update protecode config to use version 1.0.0
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1635 feat: Plutono configuration for displaying Enabled Modules in KCP
  config/grafana/status.json
Labels: lgtm, size/M, cla: yes, confirm/helm-update

#1637 feat: Add warden mandatory modules dashboard to plutono
  config/grafana/mandatory-modules.json
Labels: lgtm, size/L, cla: yes

#1644 chore: Add mandatory-modules dashboard to kustomize
  config/grafana/kustomization.yaml
Labels: lgtm, size/XS, cla: yes, confirm/helm-update

#1645 chore: Add mandatory-modules dashboard grafana patch
  config/control-plane/kustomization.yaml
  config/grafana/mandatory-modules.json
Labels: lgtm, size/S, cla: yes, confirm/helm-update
