Repository kyma-project/lifecycle-manager, pull requests merged in 2024-12, with the labels that each got.

#2078 fix: Handle Race Condition for Istio Gateway Secret
  .golangci.yaml
  cmd/main.go
  config/rbac/namespace_bindings/watcher_certmanager_role.yaml
  pkg/gatewaysecret/certmanagerclient.go
  pkg/gatewaysecret/handler.go
  pkg/gatewaysecret/handler_test.go
  tests/e2e/rbac_privileges_test.go
  unit-test-coverage.yaml
Labels: lgtm, size/L, cla: yes

#2086 chore: Bump google grpc indirect dependency due to CVE-2024-11407 in …
  go.mod
  go.sum
Labels: lgtm, size/XS, cla: yes

#2041 chore: Remove ModuleTemplate webhook
  api/go.mod
  api/go.sum
  api/v1beta1/moduletemplate_types.go
  api/v1beta2/error.go
  api/v1beta2/moduletemplate_types.go
  api/v1beta2/moduletemplate_webhook.go
  cmd/main.go
  config/control-plane/kustomization.yaml
  config/control-plane/patches/webhook_configuration_cainjection.yaml
  config/default/kustomization.yaml
  config/default/webhookcainjection_patch.yaml
  config/istio/ap.yaml
  config/webhook/kustomization.yaml
  config/webhook/manifests.yaml
  internal/descriptor/cache/cache.go
  internal/descriptor/cache/cache_test.go
  internal/descriptor/provider/provider.go
  internal/descriptor/provider/provider_test.go
  internal/descriptor/types/descriptor.go
  internal/manifest/skr_client_lookup.go
  internal/tests/api/moduletemplate_webhook_test.go
  pkg/templatelookup/regular.go
  pkg/templatelookup/regular_test.go
  pkg/testutils/builder/moduletemplate.go
  tests/integration/apiwebhook/moduletemplate_crd_validation_test.go
  tests/integration/apiwebhook/suite_test.go
  tests/integration/controller/kyma/manifest_test.go
Labels: size/XXL, cla: yes

#2074 chore: Make set manifest state more understandable
  go.sum
  internal/declarative/v2/reconciler.go
  internal/manifest/status/condition.go
  internal/manifest/status/condition_test.go
  internal/manifest/status/state.go
  internal/manifest/status/state_test.go
  tests/integration/controller/manifest/manifest_controller_test.go
Labels: size/L, cla: yes

#2072 fix: Manual Dispatch of E2E Worklfow
  .github/actions/get-configuration/action.yml
  .github/workflows/test-e2e-with-modulereleasemeta.yml
  .github/workflows/test-e2e.yml
Labels: size/M, cla: yes

#2094 chore: Bump go ver and CVE alerted pkg
  Dockerfile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: lgtm, size/S, cla: yes

#2098 fix: Add the possibility to launch KLM locally with runtime watcher
  .run/Install Watcher Resources For Local KLM.run.xml
  .run/Launch KLM locally.run.xml
Labels: lgtm, size/S, cla: yes

#2103 refactor: Remove old FQDN
  internal/manifest/img/parse_test.go
  internal/manifest/img/pathextractor_test.go
  tests/integration/moduletemplate/v1beta2_kcp-module-cred-label.yaml
Labels: lgtm, size/S, cla: yes

#2093 fix: Modules should be in error state when SKR cluster is deleted
  .github/actions/deploy-template-operator-with-modulereleasemeta/action.yml
  .github/workflows/test-e2e-with-modulereleasemeta.yml
  internal/controller/kyma/controller.go
  pkg/module/sync/runner.go
  pkg/util/error.go
  tests/e2e/Makefile
  tests/e2e/skr_connection_lost_test.go
Labels: lgtm, size/L, cla: yes

#2061 feat: Add Scripts to Automate Tasks in KLM
  .run/Delete Test Clusters.run.xml
  .run/Deploy KLM from registry.run.xml
  .run/Deploy KLM from sources.run.xml
  .run/Deploy kyma.run.xml
  .run/E2E Tests.run.xml
  .run/Install CRDs.run.xml
  .run/Un-Deploy kyma.run.xml
  .vscode/tasks.json
  scripts/tests/README.md
  scripts/tests/clusters_cleanup.sh
  scripts/tests/create_test_clusters.sh
  scripts/tests/deploy_klm_from_registry.sh
  scripts/tests/deploy_klm_from_sources.sh
  scripts/tests/deploy_kyma.sh
  scripts/tests/e2e.sh
  scripts/tests/install_crds.sh
  scripts/tests/undeploy_kyma.sh
  scripts/tests/version.sh
Labels: lgtm, size/L, cla: yes

#2097 feat: Support `internal` and `beta` flags in new module metadata
  .vscode/tasks.json
  api/v1beta2/modulereleasemeta_types.go
  api/v1beta2/moduletemplate_types.go
  cmd/main.go
  config/crd/bases/operator.kyma-project.io_modulereleasemetas.yaml
  internal/controller/kyma/controller.go
  internal/remote/remote_catalog.go
  internal/remote/remote_catalog_test.go
  pkg/testutils/modulereleasemeta.go
  pkg/testutils/moduletemplate.go
  tests/e2e/modulereleasemeta_sync_test.go
  tests/integration/controller/kcp/suite_test.go
  tests/integration/controller/withwatcher/suite_test.go
  unit-test-coverage.yaml
Labels: size/XL, cla: yes

#2117 feat: Make install_crds and e2e test scripts executable
  scripts/tests/e2e.sh
  scripts/tests/install_crds.sh
Labels: lgtm, size/XS, cla: yes

#2118 chore: Move module metadata deployment scripts to `scripts/tests`
  .github/actions/deploy-template-operator-with-modulereleasemeta/action.yml
  scripts/tests/deploy_modulereleasemeta.sh
  scripts/tests/deploy_moduletemplate.sh
Labels: lgtm, size/XS, cla: yes

#2104 chore: Align GH-Actions internal Repo with KLM Repo
  .github/actions/deploy-cert-manager/action.yml
  .github/actions/install-cmctl/action.yml
  .github/actions/install-istioctl/action.yml
  .github/actions/install-k3d/action.yml
  .github/actions/install-modulectl/action.yml
  .github/actions/setup-tools/action.yml
Labels: size/M, cla: yes

#2111 feat: Prevent unallowed internal/beta module installation
  .github/actions/deploy-template-operator-with-modulereleasemeta/action.yml
  .github/workflows/test-e2e-with-modulereleasemeta.yml
  .vscode/tasks.json
  internal/remote/remote_catalog.go
  internal/remote/remote_catalog_test.go
  pkg/templatelookup/regular.go
  pkg/templatelookup/regular_test.go
  pkg/testutils/builder/kyma.go
  pkg/testutils/builder/modulereleasemeta.go
  pkg/testutils/moduletemplate.go
  tests/e2e/Makefile
  tests/e2e/modulereleasemeta_not_allowed_installation_test.go
  tests/integration/controller/kcp/module_installation_test.go
Labels: lgtm, size/XL, cla: yes

#2095 feat: Istio gateway secret controller
  .golangci.yaml
  .mockery.yaml
  api/shared/istio.go
  cmd/main.go
  go.mod
  internal/controller/istiogatewaysecret/controller.go
  internal/controller/istiogatewaysecret/controller_test.go
  internal/controller/istiogatewaysecret/setup.go
  internal/gatewaysecret/client/client.go
  internal/gatewaysecret/handler.go
  internal/gatewaysecret/handler_test.go
  internal/gatewaysecret/mock_Client_test.go
  pkg/gatewaysecret/certmanagerclient.go
  pkg/gatewaysecret/handler.go
  pkg/gatewaysecret/handler_test.go
  pkg/testutils/watcher.go
  pkg/watcher/certificate_manager.go
  pkg/watcher/skr_webhook_manifest_manager.go
  scripts/tests/create_test_clusters.sh
  tests/e2e/istio_gateway_secret_rotation_test.go
  tests/integration/controller/withwatcher/watcher_controller_helper_test.go
  unit-test-coverage.yaml
Labels: lgtm, size/XXL, cla: yes

#2121 chore: Use standard error lib in module_installation_test
  tests/integration/controller/kcp/module_installation_test.go
Labels: size/XS, cla: yes

#2124 chore: Bump runtime-watcher to 1.1.8
  config/watcher/kustomization.yaml
Labels: lgtm, size/XS, cla: yes

#2125 chore: Bump sec-scanners-config to 1.2.5
  sec-scanners-config.yaml
Labels: size/XS, cla: yes

#2126 chore: No reconcile on Delete and Generic events
  internal/controller/istiogatewaysecret/setup.go
  unit-test-coverage.yaml
Labels: lgtm, size/XS, cla: yes

#2119 chore: Use `create_test_clusters.sh` script in E2E test setup
  .github/actions/create-k3d-cluster/action.yml
  .github/actions/deploy-cert-manager/action.yml
  .github/actions/deploy-istio/action.yml
  .github/actions/setup-test-clusters/action.yml
  .run/Create New Test Clusters.run.xml
  .run/Ensure Test Clusters.run.xml
  .vscode/tasks.json
  scripts/tests/README.md
  scripts/tests/create_test_clusters.sh
Labels: lgtm, do-not-merge/hold, size/L, cla: yes

#2129 fix: Flaky remote_sync_test
  pkg/testutils/moduletemplate.go
  tests/integration/controller/kcp/remote_sync_test.go
Labels: size/M, cla: yes

#2134 docs: Move `beta`/`internal` description from ModuleTemplate to ModuleReleaseMeta
  docs/contributor/resources/03-moduletemplate.md
  docs/contributor/resources/05-modulereleasemeta.md
Labels: lgtm, size/S, cla: yes

#2139 feat(Maintenance Windows): Add skipMaintenanceWindows to Kyma Spec
  api/v1beta1/kyma_types.go
  api/v1beta2/kyma_types.go
  config/crd/bases/operator.kyma-project.io_kymas.yaml
  docs/contributor/resources/01-kyma.md
Labels: lgtm, size/S, cla: yes

#2132 feat: Add `spec.requiresDowntime`
  api/v1beta1/moduletemplate_types.go
  api/v1beta2/moduletemplate_types.go
  config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
  docs/contributor/resources/03-moduletemplate.md
Labels: lgtm, size/S, cla: yes

#2148 chore: Bump sec-scanners-config to 1.2.6
  sec-scanners-config.yaml
Labels: size/XS, cla: yes

#2146 fix: Configure short leader election intervals for local testing
  cmd/main.go
  config/watcher_local_test/kustomization.yaml
  internal/pkg/flags/flags.go
  internal/pkg/flags/flags_test.go
Labels: size/S, cla: yes

#2151 chore: Update ocm to 0.19.0
  go.mod
  go.sum
Labels: lgtm, size/L, cla: yes

#2153 chore: Add immediate requeues to MRM sync test
  pkg/testutils/kyma.go
  tests/e2e/modulereleasemeta_sync_test.go
Labels: lgtm, size/M, cla: yes

#2145 refactor: Use Shared Rate Limiter Code
  cmd/main.go
  internal/rate_limiter.go
  tests/integration/controller/kyma/suite_test.go
  tests/integration/controller/manifest/custom_resource_check/suite_test.go
  tests/integration/controller/manifest/suite_test.go
Labels: lgtm, size/M, cla: yes
