Repository kyma-project/lifecycle-manager, pull requests merged in 2024-09, with the labels that each got.

#1820 chore: Remove drop-stored-version flag
  internal/pkg/flags/flags.go
  internal/pkg/flags/flags_test.go
Labels: lgtm, size/XS, cla: yes

#1717 feat: Unmanage module
  .github/actions/deploy-template-operator/action.yaml
  .github/workflows/test-e2e.yaml
  Dockerfile
  api/shared/operator_annotations.go
  api/shared/operator_labels.go
  api/shared/state.go
  api/v1beta2/kyma_types.go
  api/v1beta2/manifest_types.go
  config/crd/bases/operator.kyma-project.io_kymas.yaml
  config/crd/bases/operator.kyma-project.io_manifests.yaml
  config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
  config/crd/bases/operator.kyma-project.io_watchers.yaml
  internal/controller/kyma/controller.go
  internal/controller/watcher/controller.go
  internal/declarative/v2/reconciler.go
  internal/manifest/parser/template_to_module.go
  internal/pkg/metrics/manifest.go
  internal/remote/skr_context_test.go
  pkg/module/common/module.go
  pkg/module/common/module_test.go
  pkg/module/sync/runner.go
  pkg/module/sync/runner_test.go
  pkg/queue/requeue_intervals.go
  pkg/status/kyma_helper.go
  pkg/testutils/kyma.go
  pkg/testutils/utils.go
  tests/e2e/Makefile
  tests/e2e/ca_certificate_rotation_test.go
  tests/e2e/deprovision_test.go
  tests/e2e/kyma_metrics_test.go
  tests/e2e/mandatory_module_test.go
  tests/e2e/mandatory_modules_metrics_test.go
  tests/e2e/manifest_reconciliation_test.go
  tests/e2e/misconfigured_kyma_secret_test.go
  tests/e2e/module_consistency_test.go
  tests/e2e/module_deletion_test.go
  tests/e2e/module_deletion_upgrade_test.go
  tests/e2e/module_status_decoupling_test.go
  tests/e2e/module_unmanage_test.go
  tests/e2e/module_upgrade_channel_switch_test.go
  tests/e2e/module_upgrade_new_version_test.go
  tests/e2e/no_default_cr_test.go
  tests/e2e/ocm_compatible_module_template_test.go
  tests/e2e/purge_controller_test.go
  tests/e2e/purge_metrics_test.go
  tests/e2e/rbac_privileges_test.go
  tests/e2e/self_signed_certificate_rotation_test.go
  tests/e2e/suite_test.go
  tests/e2e/utils_test.go
  tests/e2e/watcher_test.go
  tests/integration/controller/kcp/remote_sync_test.go
  tests/integration/controller/kyma/kyma_module_channel_test.go
  tests/integration/controller/kyma/kyma_test.go
Labels: lgtm, size/XXL, cla: yes

#1825 docs: Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: lgtm, size/XS, cla: yes

#1798 feat: Add Jitter to Manifest Reconciliation
  cmd/main.go
  internal/pkg/flags/flags.go
  pkg/queue/requeue_intervals.go
  pkg/queue/requeue_intervals_test.go
Labels: lgtm, size/L, cla: yes

#1826 docs: Add code of conduct and update README.md
  CODE_OF_CONDUCT.md
  LICENSE
  README.md
Labels: lgtm, size/S, cla: yes

#1829 chore: Remove requeue on invalid cr state
  internal/controller/kyma/controller.go
  internal/controller/watcher/controller.go
Labels: lgtm, size/S, cla: yes

#1807 fix: Fix faulty manifest state determination
  internal/controller/manifest/controller.go
  internal/declarative/README.md
  internal/declarative/v2/options.go
  internal/declarative/v2/reconciler.go
  internal/declarative/v2/state_check.go
  internal/manifest/README.md
  internal/manifest/deployment_ready_check.go
  internal/manifest/deployment_ready_check_test.go
  internal/manifest/ready_check.go
  internal/manifest/statecheck/deployment_state_check.go
  internal/manifest/statecheck/deployment_state_check_test.go
  internal/manifest/statecheck/state_check.go
  internal/manifest/statecheck/state_check_test.go
  internal/manifest/statecheck/statefulset_state_check.go
  internal/manifest/statecheck/statefulset_state_check_test.go
  internal/manifest/statefulset_ready_check.go
  internal/manifest/statefulset_ready_check_test.go
  tests/integration/controller/manifest/custom_resource_check/manifest_test.go
  tests/integration/controller/manifest/custom_resource_check/suite_test.go
  tests/integration/controller/manifest/ready_check_test.go
  tests/integration/controller/manifest/suite_test.go
  unit-test-coverage.yaml
Labels: lgtm, size/XXL, cla: yes

#1827 chore: Make spec_resolver.go testable
  internal/controller/manifest/controller.go
  internal/manifest/keychain_provider.go
  internal/manifest/parse.go
  internal/manifest/spec_resolver.go
  internal/manifest/spec_resolver_test.go
  tests/integration/controller/manifest/custom_resource_check/suite_test.go
  tests/integration/controller/manifest/suite_test.go
  unit-test-coverage.yaml
Labels: lgtm, size/L, area/quality, cla: yes

#1834 chore: Prevent E2E tests from failing fast
  .github/workflows/test-e2e.yaml
Labels: lgtm, size/XS, cla: yes

#1833 fix: Set manifest to deleting state; Raise errors on unexpected manager conditions
  internal/declarative/v2/reconciler.go
  internal/manifest/statecheck/state_check.go
  internal/manifest/statecheck/state_check_test.go
Labels: lgtm, size/M, cla: yes

#1837 feat: Remove kyma.spec.modules[].version from api
  api/v1beta2/kyma_types.go
  config/crd/bases/operator.kyma-project.io_kymas.yaml
  tests/e2e/module_install_by_version_test.go
  tests/integration/controller/kyma/kyma_module_enable_test.go
  tests/integration/controller/kyma/kyma_module_version_test.go
Labels: lgtm, size/S, cla: yes

#1853 fix: Default no module manager found to state Ready
  internal/manifest/statecheck/state_check.go
  internal/manifest/statecheck/state_check_test.go
Labels: lgtm, size/XS, cla: yes

#1835 fix: Use github action create release
  .github/scripts/release/create_changelog.sh
  .github/scripts/release/draft_release.sh
  .github/scripts/release/get_release_by_tag.sh
  .github/scripts/release/publish_release.sh
  .github/scripts/release/validate_release_tag.sh
  .github/scripts/release/wait_for_image.sh
  .github/workflows/build-image.yml
  .github/workflows/create-release.yaml
  .github/workflows/test-e2e.yaml
  .github/workflows/test-smoke.yml
  scripts/release/get_last_release.sh
Labels: lgtm, size/L, cla: yes

#1855 fix: Make e2e test working with build image
  .github/workflows/test-e2e.yaml
  .github/workflows/test-smoke.yml
Labels: lgtm, size/L, cla: yes

#1861 fix: Remove redundant event filter predicates
  internal/controller/kyma/setup.go
Labels: lgtm, size/XS, cla: yes

#1860 fix: Test check pipeline
  .github/workflows/check-test-changes.yaml
Labels: lgtm, size/S, cla: yes

#1873 feat: Add new Panel to display Modules in Error State
  config/grafana/status.json
Labels: lgtm, size/M, cla: yes

#1878 chore: Bump lifecycle manager version in security scanners config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1868 chore: Align runtime-watcher registry and make configurable
  cmd/main.go
  config/watcher/kustomization.yaml
  internal/pkg/flags/flags.go
  internal/pkg/flags/flags_test.go
Labels: size/L, cla: yes

#1884 chore: Align runtime-watcher registry and make configurable (#1868)
  cmd/main.go
  config/watcher/kustomization.yaml
  internal/pkg/flags/flags.go
  internal/pkg/flags/flags_test.go
Labels: lgtm, size/L, cla: yes

#1885 chore: Bump istio.io client-go and api to 1.23.2
  go.mod
  go.sum
Labels: lgtm, size/S, cla: yes

#1877 chore: Change `watched-by` label value from `lifecycle-manager` to `kyma`
  api/shared/operator_labels.go
  config/watcher/operator_v1beta2_watcher.yaml
  internal/declarative/v2/default_transforms.go
  internal/remote/skr_context.go
  tests/integration/controller/kcp/helper_test.go
Labels: lgtm, size/S, cla: yes

#1896 transparent Managedby label
  api/shared/operator_labels.go
  api/v1beta2/kyma_types.go
  internal/declarative/v2/default_transforms.go
  internal/declarative/v2/default_transforms_test.go
  internal/remote/skr_context.go
  pkg/module/common/module.go
  pkg/module/common/module_test.go
  pkg/testutils/builder/watcher.go
  pkg/testutils/utils.go
  pkg/watch/mandatory_template_change.go
  pkg/watcher/certificate_manager.go
  tests/integration/controller/mandatorymodule/deletion/controller_test.go
  tests/integration/controller/mandatorymodule/installation/controller_test.go
  tests/integration/controller/withwatcher/watcher_controller_helper_test.go
Labels: size/M

#1892 feat: Module catalogue improvements
  .github/actions/deploy-template-operator/action.yaml
  .github/workflows/test-e2e.yaml
  api-version-compatibility-config.yaml
  api/shared/channel.go
  api/v1beta2/kyma_types.go
  api/v1beta2/moduletemplate_types.go
  api/v1beta2/moduletemplate_types_test.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
  internal/controller/kyma/controller.go
  internal/descriptor/cache/key.go
  internal/descriptor/provider/provider_test.go
  internal/manifest/parser/template_to_module.go
  internal/pkg/metrics/kyma.go
  internal/remote/skr_context.go
  internal/remote/skr_context_test.go
  pkg/module/sync/errors.go
  pkg/templatelookup/availableModules.go
  pkg/templatelookup/availableModules_test.go
  pkg/templatelookup/regular.go
  pkg/templatelookup/regular_test.go
  pkg/testutils/builder/moduletemplate.go
  pkg/testutils/moduletemplate.go
  pkg/testutils/utils.go
  tests/e2e/Makefile
  tests/e2e/module_install_by_version_test.go
  tests/e2e/module_status_decoupling_test.go
  tests/integration/apiwebhook/moduletemplate_crd_validation_test.go
  tests/integration/apiwebhook/ocm_test.go
  tests/integration/controller/kcp/helper_test.go
  tests/integration/controller/kcp/remote_sync_test.go
  tests/integration/controller/kyma/helper_test.go
  tests/integration/controller/kyma/kyma_module_channel_test.go
  tests/integration/controller/kyma/kyma_module_enable_test.go
  tests/integration/controller/kyma/kyma_module_version_test.go
  tests/integration/controller/kyma/kyma_test.go
  tests/integration/controller/kyma/manifest_test.go
  tests/integration/controller/kyma/moduletemplate_install_test.go
  tests/integration/controller/kyma/moduletemplate_test.go
  tests/integration/controller/mandatorymodule/deletion/controller_test.go
  tests/integration/controller/mandatorymodule/installation/controller_test.go
  tests/integration/controller/moduletemplate/moduletemplate_test.go
  tests/integration/controller/moduletemplate/suite_test.go
  tests/moduletemplates/moduletemplate_template_operator_v2_direct_version.yaml
  unit-test-coverage.yaml
Labels: lgtm, size/XXL, cla: yes

#1898 chore: Add VSCode tasks and launch config for local setup
  .gitignore
  .vscode/launch.json
  .vscode/tasks.json
  scripts/tests/create_test_clusters.sh
  scripts/tests/deploy_kyma.sh
Labels: lgtm, size/L, cla: yes

#1901 chore: Allow dependabot monitor github actions
  .github/dependabot.yml
Labels: lgtm, size/XS, cla: yes
