Repository kyma-project/lifecycle-manager, pull requests merged in 2024-11, with the labels that each got.

#2002 chore: Refactor ModuleTemplate catalog sync code
  internal/controller/kyma/controller.go
  internal/remote/moduletemplate_syncer.go
  internal/remote/moduletemplate_syncer_test.go
  internal/remote/moduletemplate_syncworker.go
  internal/remote/prepareforssa_test.go
  internal/remote/remote_catalog.go
  internal/util/collections/diffcalc.go
  internal/util/collections/diffcalc_test.go
  internal/util/collections/filter.go
  internal/util/collections/filter_test.go
  unit-test-coverage.yaml
Labels: size/XXL, cla: yes

#2005 fix: Build image event name
  .github/workflows/build-image.yml
Labels: lgtm, size/XS, cla: yes

#2008 chore: Log cluster creation command to console
  .github/actions/create-k3d-cluster/action.yml
Labels: lgtm, size/XS, cla: yes

#1988 feat: Provide condition for Manifests stuck in Deleting due to DefaultCR Warning
  .golangci.yaml
  api/v1beta2/manifest_types.go
  cmd/main.go
  internal/controller/manifest/controller.go
  internal/controller/manifest/setup.go
  internal/declarative/v2/client.go
  internal/declarative/v2/reconciler.go
  internal/declarative/v2/reconciler_test.go
  internal/manifest/finalizer/handler.go
  internal/manifest/finalizer/handler_test.go
  internal/manifest/manifestclient/manifest_client.go
  internal/manifest/modulecr/client.go
  internal/manifest/modulecr/client_test.go
  internal/manifest/skrresources/resource_converter.go
  internal/manifest/skrresources/ssa.go
  internal/manifest/skrresources/ssa_test.go
  internal/manifest/skrresources/sync.go
  internal/manifest/skrresources/sync_test.go
  internal/manifest/status/condition.go
  internal/manifest/status/init.go
  internal/pkg/metrics/kyma.go
  internal/pkg/metrics/manifest.go
  internal/pkg/metrics/module.go
  pkg/testutils/manifest.go
  pkg/testutils/metrics.go
  pkg/testutils/modulecr.go
  pkg/testutils/utils.go
  tests/e2e/mandatory_module_test.go
  tests/e2e/mandatory_modules_metrics_test.go
  tests/e2e/module_deletion_test.go
  tests/e2e/module_deletion_upgrade_test.go
  tests/e2e/module_status_decoupling_test.go
  tests/integration/controller/manifest/custom_resource_check/suite_test.go
  tests/integration/controller/manifest/suite_test.go
  tests/integration/controller/moduletemplate/moduletemplate_test.go
  unit-test-coverage.yaml
Labels: size/XL, cla: yes

#2013 chore: Use separate ModuleConfig files for the E2E tests
  .github/actions/deploy-template-operator-with-modulereleasemeta/action.yml
  .github/actions/deploy-template-operator/action.yml
Labels: lgtm, size/M, cla: yes

#2014 feat: Modulereleasemeta catalog sync
  internal/controller/kyma/controller.go
  internal/remote/crd_upgrade.go
  internal/remote/modulereleasemeta_syncer.go
  internal/remote/modulereleasemeta_syncer_test.go
  internal/remote/modulereleasemeta_syncworker.go
  internal/remote/moduletemplate_syncer.go
  internal/remote/moduletemplate_syncer_test.go
  internal/remote/moduletemplate_syncworker.go
  internal/remote/prepareforssa_test.go
  internal/remote/remote_catalog.go
  internal/util/collections/filter.go
  internal/util/collections/filter_test.go
  pkg/testutils/builder/modulereleasemeta.go
  pkg/testutils/moduletemplate.go
  tests/e2e/module_deletion_test.go
  tests/e2e/module_upgrade_new_version_test.go
  tests/e2e/modulereleasemeta_sync_test.go
  tests/integration/controller/kcp/helper_test.go
  tests/integration/controller/kcp/remote_sync_test.go
  tests/integration/controller/kyma/kyma_test.go
  tests/integration/controller/kyma/manifest_test.go
  unit-test-coverage.yaml
Labels: lgtm, size/XXL, cla: yes

#2018 fix: Remove pattern and min length validation from ModuleTemplate spec.channel
  api/v1beta1/moduletemplate_types.go
  api/v1beta2/moduletemplate_types.go
  config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
Labels: lgtm, size/S, cla: yes

#2023 feat: Add Kyma Manifest in Error state for plutono dashboard
  config/grafana/status.json
Labels: lgtm, size/M, cla: yes

#2016 feat: Introduce module Warning metrics
  .github/actions/deploy-lifecycle-manager-e2e/action.yml
  .run/Deploy KLM from sources.run.xml
  .vscode/tasks.json
  api/v1beta2/error.go
  api/v1beta2/kyma_types.go
  cmd/main.go
  internal/controller/kyma/controller.go
  internal/declarative/v2/reconciler.go
  internal/pkg/metrics/module.go
  pkg/module/sync/runner.go
  pkg/module/sync/runner_test.go
  pkg/testutils/metrics.go
  scripts/tests/create_test_clusters.sh
  tests/e2e/module_status_decoupling_test.go
  tests/integration/controller/eventfilters/suite_test.go
  tests/integration/controller/kcp/suite_test.go
  tests/integration/controller/kyma/suite_test.go
  tests/integration/controller/withwatcher/suite_test.go
Labels: size/L, cla: yes

#2017 feat: Bump modulectl version in E2E tests
  .github/actions/deploy-template-operator-with-modulereleasemeta/action.yml
  .github/actions/deploy-template-operator/action.yml
  .github/actions/get-configuration/action.yml
  .github/actions/install-modulectl/action.yml
  .github/actions/setup-https-server/action.yml
  docs/contributor/04-local-test-setup.md
  scripts/tests/https_server.go
  scripts/tests/setup_https_server.sh
Labels: lgtm, size/L, cla: yes

#2025 feat: Update module catalog related docs
  docs/contributor/01-architecture.md
  docs/contributor/assets/kyma-operator-architecture.svg
  docs/contributor/assets/lifecycle-manager-architecture.svg
  docs/contributor/resources/01-kyma.md
  docs/contributor/resources/README.md
Labels: lgtm, size/S, area/documentation, cla: yes

#2028 chore: Move dashboard config maps from Kyma-system namespace
  config/control-plane/kustomization.yaml
Labels: lgtm, size/M, cla: yes

#2031 chore: Bump lifecycle manager version in security scanners config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#2033 feat: Add mandatory-module label to mandatory ModuleTemplate
  internal/controller/kyma/controller.go
  pkg/templatelookup/mandatory.go
  pkg/testutils/moduletemplate.go
  tests/e2e/mandatory_module_test.go
  tests/integration/controller/mandatorymodule/deletion/controller_test.go
  tests/integration/controller/mandatorymodule/installation/controller_test.go
  unit-test-coverage.yaml
Labels: size/L, cla: yes

#2052 deps: Bump controller-runtime to v0.19.2
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: size/S, cla: yes

#2065 chore: Bump 'ocm.software/ocm' to 'v0.18.0'
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: size/L, cla: yes

#2004 feat: Introduce Dedicated Istio Gateway Secret
  .github/actions/deploy-lifecycle-manager-e2e/action.yml
  .github/workflows/test-e2e-with-modulereleasemeta.yml
  .github/workflows/test-e2e.yml
  cmd/main.go
  config/rbac/namespace_bindings/watcher_certmanager_role.yaml
  config/watcher/gateway.yaml
  internal/pkg/flags/flags.go
  internal/pkg/flags/flags_test.go
  pkg/gatewaysecret/handler.go
  pkg/gatewaysecret/handler_test.go
  pkg/testutils/namespace.go
  pkg/testutils/watcher.go
  pkg/watcher/ca_certificate_cache.go
  pkg/watcher/certificate_manager.go
  pkg/watcher/certificate_manager_test.go
  pkg/watcher/skr_webhook_manifest_manager.go
  tests/e2e/Makefile
  tests/e2e/ca_certificate_rotation_test.go
  tests/e2e/istio_gateway_secret_rotation_test.go
  tests/e2e/rbac_privileges_test.go
  tests/integration/controller/withwatcher/controller_test.go
  tests/integration/controller/withwatcher/suite_test.go
  tests/integration/controller/withwatcher/watcher_certificate_test.go
  tests/integration/controller/withwatcher/watcher_controller_helper_test.go
  tests/integration/watcher/certificate_test.go
  unit-test-coverage.yaml
Labels: lgtm, size/XL, cla: yes

#2069 feat: Add fields in security scanner config for checkmarxOne
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes
