Repository kyma-project/lifecycle-manager, pull requests merged in 2024-07, with the labels that each got.

#1652 feat: Introduce `managed` flag to KymaCR `.spec.modules`
  api/v1beta2/kyma_types.go
  config/crd/bases/operator.kyma-project.io_kymas.yaml
  docs/technical-reference/api/kyma-cr.md
Labels: lgtm, size/M, cla: yes, confirm/helm-update

#1659 chore: Fix broken Prometheus Quick Start link
  docs/user-tutorials/01-10-control-plane-quick-start.md
Labels: lgtm, size/XS, cla: yes

#1658 chore: Revert "feat: Introduce `managed` flag to KymaCR `.spec.modules` (#1652)"
  api/v1beta2/kyma_types.go
  config/crd/bases/operator.kyma-project.io_kymas.yaml
  docs/technical-reference/api/kyma-cr.md
Labels: lgtm, size/M, cla: yes, confirm/helm-update

#1663 chore: Add `feat/**` as branch for PR-based Github Actions
  .github/workflows/check-api-compatibility.yaml
  .github/workflows/check-manifest-diffs.yaml
  .github/workflows/lint-golangci.yml
  .github/workflows/test-e2e.yaml
  .github/workflows/test-smoke.yml
  .github/workflows/test-unit.yml
  .github/workflows/verify-unit-test-coverage.yml
Labels: lgtm, size/S, cla: yes

#1661 feat: Re-add `.spec.modules[].managed` to KymaCR
  api/v1beta2/kyma_types.go
  config/crd/bases/operator.kyma-project.io_kymas.yaml
  docs/technical-reference/api/kyma-cr.md
Labels: lgtm, size/M, cla: yes, confirm/helm-update

#1665 chore: Bump k8s version for e2e to 1.29.6
  .github/actions/get-configuration/action.yaml
  .github/workflows/test-e2e.yaml
  .github/workflows/test-smoke.yml
Labels: lgtm, size/XS, cla: yes

#1620 feat: Avoid Redundant SSA for Manifest Patching
  config/samples/component-integration-installed/operator_v1beta2_moduletemplate_kcp-module_updated.yaml
  docs/technical-reference/api/manifest-cr.md
  pkg/module/sync/runner.go
  pkg/module/sync/runner_test.go
  pkg/testutils/builder/moduletemplate.go
  tests/integration/controller/kyma/manifest_test.go
Labels: lgtm, size/L, cla: yes

#1656 feat: Add AssociatedResources field to Manifest Spec
  api/v1beta2/manifest_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_manifests.yaml
  docs/technical-reference/api/manifest-cr.md
Labels: lgtm, size/M, cla: yes, confirm/helm-update

#1660 chore: Create ModuleTemplate with new ocm format for e2e
  tests/moduletemplates/moduletemplate_template_operator_regular_new_ocm.yaml
Labels: lgtm, size/M, cla: yes, confirm/helm-update

#1674 chore: Remove diff manifest diff checker
  .github/workflows/check-manifest-diffs.yaml
Labels: lgtm, size/M, cla: yes

#1676 refactor: Simplify declarative reconciler
  api/v1beta2/manifest_types.go
  internal/controller/manifest/controller.go
  internal/declarative/v2/inmemory_rendered.go
  internal/declarative/v2/moduleCR_deletion_check.go
  internal/declarative/v2/options.go
  internal/declarative/v2/reconciler.go
  internal/declarative/v2/spec.go
  internal/manifest/cr_deletion_check.go
  internal/manifest/custom_resource.go
  internal/manifest/spec_resolver.go
  tests/integration/controller/manifest/custom_resource_check/suite_test.go
  tests/integration/controller/manifest/suite_test.go
Labels: lgtm, size/XL, cla: yes

#1678 chore: Merge main into deletion modes feature
  .github/actions/get-configuration/action.yaml
  .github/workflows/check-manifest-diffs.yaml
  .github/workflows/test-e2e.yaml
  .github/workflows/test-smoke.yml
  Dockerfile
  api/v1beta2/manifest_types.go
  config/samples/component-integration-installed/operator_v1beta2_moduletemplate_kcp-module_updated.yaml
  docs/technical-reference/api/manifest-cr.md
  go.mod
  go.sum
  internal/controller/manifest/controller.go
  internal/declarative/v2/inmemory_rendered.go
  internal/declarative/v2/moduleCR_deletion_check.go
  internal/declarative/v2/options.go
  internal/declarative/v2/reconciler.go
  internal/declarative/v2/spec.go
  internal/manifest/cr_deletion_check.go
  internal/manifest/custom_resource.go
  internal/manifest/spec_resolver.go
  pkg/module/sync/runner.go
  pkg/module/sync/runner_test.go
  pkg/testutils/builder/moduletemplate.go
  tests/integration/controller/kyma/manifest_test.go
  tests/integration/controller/manifest/custom_resource_check/suite_test.go
  tests/integration/controller/manifest/suite_test.go
Labels: lgtm, size/XXL, cla: yes

#1683 chore: Update Protecode
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1689 chore: Remove associatedResources field from Manifest CR
  api/v1beta2/manifest_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_manifests.yaml
  docs/technical-reference/api/manifest-cr.md
Labels: lgtm, size/M, cla: yes

#1695 chore: Refactor NewCachedDescriptorProvider
  .golangci.yaml
  cmd/main.go
  docs/user-tutorials/01-10-control-plane-quick-start.md
  internal/descriptor/provider/provider.go
  internal/descriptor/provider/provider_test.go
  pkg/testutils/kyma.go
  pkg/testutils/moduletemplate.go
  tests/integration/apiwebhook/moduletemplate_crd_validation_test.go
  tests/integration/controller/eventfilters/suite_test.go
  tests/integration/controller/kcp/remote_sync_test.go
  tests/integration/controller/kcp/suite_test.go
  tests/integration/controller/kyma/suite_test.go
  tests/integration/controller/mandatorymodule/deletion/suite_test.go
  tests/integration/controller/mandatorymodule/installation/suite_test.go
  tests/integration/controller/withwatcher/suite_test.go
  unit-test-coverage.yaml
Labels: lgtm, size/M, cla: yes

#1700 chore: Refactor NewCachedDescriptorProvider (#1695)
  .golangci.yaml
  cmd/main.go
  docs/user-tutorials/01-10-control-plane-quick-start.md
  internal/descriptor/provider/provider.go
  internal/descriptor/provider/provider_test.go
  pkg/testutils/kyma.go
  pkg/testutils/moduletemplate.go
  tests/integration/apiwebhook/moduletemplate_crd_validation_test.go
  tests/integration/controller/eventfilters/suite_test.go
  tests/integration/controller/kcp/remote_sync_test.go
  tests/integration/controller/kcp/suite_test.go
  tests/integration/controller/kyma/suite_test.go
  tests/integration/controller/mandatorymodule/deletion/suite_test.go
  tests/integration/controller/mandatorymodule/installation/suite_test.go
  tests/integration/controller/withwatcher/suite_test.go
  unit-test-coverage.yaml
Labels: lgtm, size/M, cla: yes

#1680 docs: Update KLM Local Test Setup Guide
  docs/developer-tutorials/local-test-setup.md
Labels: lgtm, size/M, cla: yes

#1672 feat: Drop multiple ways to reference modules in Kyma CR
  api/v1beta2/kyma_types.go
  config/crd/bases/operator.kyma-project.io_kymas.yaml
  docs/technical-reference/api/kyma-cr.md
  pkg/templatelookup/regular.go
  tests/integration/controller/kyma/manifest_test.go
Labels: lgtm, size/L, cla: yes

#1690 chore: Configure different requeue intervals for Manifest reconciliation
  cmd/main.go
  internal/declarative/v2/reconciler.go
  internal/pkg/flags/flags.go
  internal/pkg/flags/flags_test.go
  pkg/queue/requeue_intervals.go
  tests/integration/controller/manifest/custom_resource_check/suite_test.go
  tests/integration/controller/manifest/suite_test.go
Labels: lgtm, size/M, cla: yes

#1703 chore: Bump k8s deps
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: lgtm, size/M, cla: yes

#1702 fix: Manifest CR should update by moduletemplate generation changes
  internal/descriptor/cache/key.go
  internal/descriptor/cache/key_test.go
  pkg/module/sync/runner.go
  pkg/module/sync/runner_test.go
  pkg/templatelookup/regular.go
  pkg/templatelookup/regular_test.go
  pkg/testutils/builder/kyma.go
  pkg/testutils/builder/moduletemplate.go
  unit-test-coverage.yaml
Labels: lgtm, size/XL, cla: yes

#1718 chore: Sync main to feature branch
  api/go.mod
  api/go.sum
  api/v1beta2/kyma_types.go
  cmd/main.go
  config/crd/bases/operator.kyma-project.io_kymas.yaml
  docs/developer-tutorials/local-test-setup.md
  docs/technical-reference/api/kyma-cr.md
  go.mod
  go.sum
  internal/declarative/v2/reconciler.go
  internal/descriptor/cache/key.go
  internal/descriptor/cache/key_test.go
  internal/pkg/flags/flags.go
  internal/pkg/flags/flags_test.go
  pkg/module/sync/runner.go
  pkg/module/sync/runner_test.go
  pkg/queue/requeue_intervals.go
  pkg/templatelookup/regular.go
  pkg/templatelookup/regular_test.go
  pkg/testutils/builder/kyma.go
  pkg/testutils/builder/moduletemplate.go
  tests/integration/controller/kyma/manifest_test.go
  tests/integration/controller/manifest/custom_resource_check/suite_test.go
  tests/integration/controller/manifest/suite_test.go
  unit-test-coverage.yaml
Labels: lgtm, size/XXL, cla: yes

#1720 chore: Sync deletion mode feature branch
  .golangci.yaml
  api/go.mod
  api/go.sum
  api/v1beta2/kyma_types.go
  cmd/main.go
  config/crd/bases/operator.kyma-project.io_kymas.yaml
  docs/developer-tutorials/local-test-setup.md
  docs/technical-reference/api/kyma-cr.md
  docs/user-tutorials/01-10-control-plane-quick-start.md
  go.mod
  go.sum
  internal/declarative/v2/reconciler.go
  internal/descriptor/cache/key.go
  internal/descriptor/cache/key_test.go
  internal/descriptor/provider/provider.go
  internal/descriptor/provider/provider_test.go
  internal/pkg/flags/flags.go
  internal/pkg/flags/flags_test.go
  pkg/module/sync/runner.go
  pkg/module/sync/runner_test.go
  pkg/queue/requeue_intervals.go
  pkg/templatelookup/regular.go
  pkg/templatelookup/regular_test.go
  pkg/testutils/builder/kyma.go
  pkg/testutils/builder/moduletemplate.go
  pkg/testutils/kyma.go
  pkg/testutils/moduletemplate.go
  sec-scanners-config.yaml
  tests/integration/apiwebhook/moduletemplate_crd_validation_test.go
  tests/integration/controller/eventfilters/suite_test.go
  tests/integration/controller/kcp/remote_sync_test.go
  tests/integration/controller/kcp/suite_test.go
  tests/integration/controller/kyma/manifest_test.go
  tests/integration/controller/kyma/suite_test.go
  tests/integration/controller/mandatorymodule/deletion/suite_test.go
  tests/integration/controller/mandatorymodule/installation/suite_test.go
  tests/integration/controller/manifest/custom_resource_check/suite_test.go
  tests/integration/controller/manifest/suite_test.go
  tests/integration/controller/withwatcher/suite_test.go
  unit-test-coverage.yaml
Labels: lgtm, size/XXL, cla: yes

#1713 feat: Support StatefulSet Module Resource in Ready Check
  .github/actions/deploy-template-operator/action.yaml
  .github/workflows/test-e2e.yaml
  internal/controller/manifest/controller.go
  internal/declarative/v2/reconciler.go
  internal/manifest/deployment_ready_check.go
  internal/manifest/deployment_ready_check_test.go
  internal/manifest/ready_check.go
  internal/manifest/ready_check_test.go
  internal/manifest/statefulset_ready_check.go
  internal/manifest/statefulset_ready_check_test.go
  pkg/testutils/modulecr.go
  pkg/testutils/statefulset.go
  tests/e2e/Makefile
  tests/e2e/manifest_reconciliation_test.go
  tests/e2e/module_consistency_test.go
  tests/e2e/module_deletion_test.go
  tests/e2e/module_status_decoupling_test.go
  tests/e2e/module_status_decoupling_with_deployment_test.go
  tests/e2e/module_status_decoupling_with_statefulset_test.go
  tests/integration/controller/manifest/custom_resource_check/suite_test.go
  tests/integration/controller/manifest/ready_check_test.go
Labels: lgtm, size/XL, cla: yes

#1694 feat: Add Version to Kyma.Spec.Modules
  api/shared/channel.go
  api/v1beta2/kyma_types.go
  api/v1beta2/kyma_types_test.go
  api/v1beta2/moduletemplate_types.go
  config/crd/bases/operator.kyma-project.io_kymas.yaml
  config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
  internal/controller/kyma/controller.go
  internal/descriptor/cache/key.go
  internal/descriptor/provider/provider_test.go
  pkg/module/parse/template_to_module.go
  pkg/module/sync/errors.go
  pkg/templatelookup/regular.go
  pkg/templatelookup/regular_test.go
  pkg/testutils/utils.go
  tests/e2e/module_status_decoupling_test.go
  tests/integration/controller/kyma/helper_test.go
  tests/integration/controller/kyma/kyma_module_channel_test.go
  tests/integration/controller/kyma/kyma_module_enable_test.go
  tests/integration/controller/kyma/kyma_module_version_test.go
  tests/integration/controller/kyma/manifest_test.go
  unit-test-coverage.yaml
Labels: lgtm, size/XL, cla: yes

#1708 chore: Add deprecation notes to customStateCheck
  api-version-compatibility-config.yaml
  api/v1beta2/moduletemplate_types.go
  config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
  docs/technical-reference/api/moduleTemplate-cr.md
Labels: lgtm, size/XS, cla: yes
