Repository kyma-project/lifecycle-manager, pull requests merged in 2024-03, with the labels that each got.

#1350 test: Add E2E test for ModuleTemplate deletion
  pkg/testutils/moduletemplate.go
  tests/e2e/module_deletion_test.go
  tests/integration/controller/controlplane/kyma_remote_sync_test.go
Labels: lgtm, size/M, cla: yes

#1346 chore: Bump golangci-lint make and action
  .github/workflows/lint-golangci.yml
  .golangci.yaml
  Makefile
  cmd/main.go
  internal/controller/kyma_controller.go
  internal/controller/mandatory_modules_installation_controller.go
  internal/declarative/v2/reconciler.go
  internal/declarative/v2/ssa.go
  internal/pkg/metrics/kyma.go
  pkg/img/parse.go
  pkg/remote/kyma_synchronization_context.go
  pkg/remote/remote_catalog.go
  pkg/testutils/klm.go
  pkg/testutils/manifest.go
  pkg/watcher/skr_webhook_resources.go
  tests/e2e/ca_certificate_rotation_test.go
  tests/integration/controller/mandatorymodule/deletion/mandatory_modules_deletion_controller_test.go
  tests/integration/controller/withwatcher/watcher_controller_helper_test.go
  tests/integration/declarative/declarative_test.go
  tests/integration/declarative/helper_test.go
Labels: lgtm, size/M, cla: yes

#1321 feat: Add Manifest Reconcile Duration Metric
  internal/declarative/v2/reconciler.go
  internal/pkg/metrics/manifest.go
  pkg/testutils/metrics.go
  tests/e2e/kyma_metrics_test.go
Labels: lgtm, size/M, cla: yes

#1337 chore: Remove v1beta1 resources
  README.md
  api/scheme.go
  api/v1beta1/kyma_conversion.go
  api/v1beta1/manifest_conversion.go
  api/v1beta1/moduletemplate_conversion.go
  api/v1beta1/watcher_conversion.go
  api/v1beta2/kyma_webhook.go
  api/v1beta2/manifest_webhook.go
  api/v1beta2/watcher_webhook.go
  cmd/main.go
  config/crd/kustomization.yaml
  config/crd/patches/webhook_in_kymas.yaml
  config/crd/patches/webhook_in_manifests.yaml
  config/crd/patches/webhook_in_moduletemplates.yaml
  config/crd/patches/webhook_in_watchers.yaml
  docs/developer-tutorials/local-test-setup.md
  docs/modularization.md
  docs/technical-reference/api/kyma-cr.md
  internal/manifest/README.md
  tests/integration/apiwebhook/webhook_suite_test.go
Labels: lgtm, size/L, cla: yes

#1359 fix: Revert "feat: Add Manifest Reconcile Duration Metric (#1321)"
  internal/declarative/v2/reconciler.go
  internal/pkg/metrics/manifest.go
  pkg/testutils/metrics.go
  tests/e2e/kyma_metrics_test.go
Labels: lgtm, size/M, cla: yes

#1361 fix: Remove ModuleTemplate conversion webhook
  api/v1beta2/kyma_conversion.go
  api/v1beta2/manifest_conversion.go
  api/v1beta2/moduletemplate_conversion.go
  api/v1beta2/watcher_conversion.go
  config/crd/kustomization.yaml
  config/crd/patches/webhook_in_moduletemplates.yaml
Labels: lgtm, size/M, cla: yes

#1349 feat: Set `OwnerReference` for `VirtualService`
  internal/controller/setup.go
  internal/controller/watcher_controller.go
  internal/istio/errors.go
  internal/istio/httproute_test.go
  internal/istio/virtualservice.go
  internal/istio/virtualservice_test.go
  pkg/testutils/builder/crds.go
  pkg/testutils/builder/kyma.go
  pkg/testutils/builder/moduletemplate.go
  pkg/testutils/builder/watcher.go
  pkg/testutils/manifest.go
  pkg/testutils/random/random.go
  pkg/testutils/utils.go
  tests/integration/controller/withwatcher/watcher_controller_helper_test.go
  tests/integration/controller/withwatcher/watcher_controller_test.go
  unit-test-coverage.yaml
Labels: lgtm, size/L, cla: yes

#1358 chore: Verify diff in manifests
  .github/workflows/check-manifest-diffs.yaml
Labels: lgtm, size/M, cla: yes

#1372 chore: Remove `r.WatcherVSNamespace` from `WatcherReconciler`
  cmd/main.go
  internal/controller/watcher_controller.go
  tests/integration/controller/withwatcher/suite_with_watcher_test.go
Labels: lgtm, size/S, cla: yes

#1374 feat: Manifest duration metrics
  internal/declarative/v2/reconciler.go
  internal/pkg/metrics/manifest.go
  internal/pkg/metrics/metrics_test.go
Labels: lgtm, size/M, cla: yes

#1336 fix: Split resource deletion
  .golangci.yaml
  go.mod
  go.sum
  internal/declarative/v2/cleanup.go
  internal/declarative/v2/reconciler.go
  internal/manifest/custom_resource.go
  internal/pkg/resources/cleanup.go
  internal/pkg/resources/cleanup_test.go
  pkg/testutils/builder/modulecr.go
  pkg/testutils/klm.go
  pkg/testutils/kyma.go
  pkg/testutils/manifest.go
  pkg/testutils/metrics.go
  pkg/testutils/modulecr.go
  pkg/testutils/unstructured.go
  tests/e2e/ca_certificate_rotation_test.go
  tests/e2e/deletion_test.go
  tests/e2e/kyma_metrics_test.go
  tests/e2e/mandatory_module_test.go
  tests/e2e/manifest_reconciliation_test.go
  tests/e2e/module_consistency_test.go
  tests/e2e/module_deletion_test.go
  tests/e2e/module_deletion_upgrade_test.go
  tests/e2e/module_upgrade_channel_switch_test.go
  tests/e2e/module_upgrade_new_version_test.go
  tests/e2e/no_default_cr_test.go
  tests/e2e/purge_controller_test.go
  tests/e2e/purge_metrics_test.go
  tests/e2e/self_signed_certificate_rotation_test.go
  tests/e2e/utils_test.go
  tests/e2e/warning_status_propagation_test.go
  tests/e2e/watcher_test.go
  tests/integration/controller/controlplane/kyma_remote_sync_test.go
  tests/integration/controller/kyma/kyma_test.go
  tests/integration/controller/manifest/custom_resource_check/manifest_test.go
  tests/integration/declarative/api.go
  tests/integration/declarative/declarative_test.go
  tests/integration/declarative/helper_test.go
  tests/integration/declarative/suite_test.go
  tests/integration/declarative/zz_generated.deepcopy.go
  tests/moduletemplates/moduletemplate_template_operator_v1_regular.yaml
  tests/moduletemplates/moduletemplate_template_operator_v2_fast.yaml
  tests/moduletemplates/moduletemplate_template_operator_v2_regular_new_version.yaml
  unit-test-coverage.yaml
Labels: lgtm, size/XXL, cla: yes

#1388 fix: Manifest got deleted log
  internal/declarative/v2/reconciler.go
Labels: lgtm, size/S, cla: yes

#1385 feat: Allow different drop storage versions based on crd kind
  cmd/main.go
  internal/crd/storage_version_dropper.go
  internal/crd/storage_version_dropper_test.go
  internal/pkg/flags/flags.go
  internal/pkg/flags/flags_test.go
  unit-test-coverage.yaml
Labels: lgtm, size/L, cla: yes

#1392 chore: Refactor and increase purge controller monitoring
  internal/controller/purge_controller.go
  internal/pkg/metrics/purge.go
Labels: lgtm, size/L, cla: yes

#1403 fix: Add wait for cache sync for the storage version dropper
  cmd/main.go
Labels: lgtm, size/XS, cla: yes

#1420 fix: Correct inaccurate log message in purge cleanup
  internal/controller/purge_controller.go
Labels: lgtm, size/XS, cla: yes

#1421 docs: IN cluster instead of ON
  docs/developer-tutorials/local-test-setup.md
  docs/modularization.md
Labels: lgtm, size/XS, area/documentation, cla: yes

#1363 fix: Cache Invalidation for DNS Lookup Errors
  .github/workflows/test-e2e.yml
  internal/declarative/v2/reconciler.go
  internal/declarative/v2/resource_converter.go
  pkg/util/error.go
  tests/e2e/Makefile
  tests/e2e/deprovision_test.go
  tests/e2e/kyma_deprovision_background_test.go
  tests/e2e/kyma_deprovision_foreground_test.go
  tests/e2e/misconfigured_kyma_secret_test.go
  tests/e2e/utils_test.go
Labels: lgtm, size/L, cla: yes

#1408 fix: Avoid unnecessary ssa for the manifest
  internal/declarative/v2/reconciler.go
  internal/declarative/v2/reconciler_test.go
  pkg/testutils/manifest.go
  tests/e2e/manifest_reconciliation_test.go
Labels: lgtm, size/L, cla: yes

#1419 fix: Filter controller-runtime metrics panels by our controllers
  config/grafana/overview.json
Labels: lgtm, size/XS, cla: yes, confirm/helm-update

#1413 feat: Add SyncResource CRD
  PROJECT
  api/shared/cr_kind.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/syncresource_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/operator.kyma-project.io_syncresources.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_syncresources.yaml
  config/rbac/role.yaml
  config/samples/component-integration-installed/operator_v1alpha1_syncresource.yaml
  config/samples/component-integration-installed/operator_v1beta1_kyma.yaml
  internal/controller/setup.go
  internal/controller/syncresource_controller.go
Labels: lgtm, size/XL, cla: yes, confirm/helm-update

#1432 chore: Remove inapplicable `kubebuiler:subresource:status` markers
  api/v1beta2/kyma_types.go
  api/v1beta2/watcher_types.go
Labels: lgtm, size/XS, cla: yes

#1429 chore: Remove editor and viewer roles files
  config/rbac/kyma_editor_role.yaml
  config/rbac/kyma_viewer_role.yaml
  config/rbac/manifest_editor_role.yaml
  config/rbac/manifest_viewer_role.yaml
  config/rbac/moduletemplate_editor_role.yaml
  config/rbac/moduletemplate_viewer_role.yaml
  config/rbac/watcher_editor_role.yaml
  config/rbac/watcher_viewer_role.yaml
Labels: lgtm, size/L, cla: yes

#1434 chore: Remove sync resource
  api/shared/cr_kind.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/syncresource_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/operator.kyma-project.io_syncresources.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_syncresources.yaml
  config/rbac/role.yaml
  config/samples/component-integration-installed/operator_v1alpha1_syncresource.yaml
  internal/controller/setup.go
  internal/controller/syncresource_controller.go
Labels: lgtm, size/XL, cla: yes, confirm/helm-update
