Repository kyma-project/lifecycle-manager, pull requests merged in 2024-10, with the labels that each got.

#1894 chore: Make managed-by label value transparent
  api/shared/operator_labels.go
  api/v1beta2/kyma_types.go
  api/v1beta2/moduletemplate_types.go
  internal/controller/manifest/setup.go
  internal/declarative/v2/default_transforms.go
  internal/declarative/v2/default_transforms_test.go
  internal/declarative/v2/options.go
  internal/manifest/custom_resource.go
  internal/remote/crd_upgrade.go
  internal/remote/remote_catalog.go
  internal/remote/skr_context.go
  internal/util/collections/collections.go
  internal/util/collections/collections_test.go
  pkg/watcher/skr_webhook_manifest_manager.go
  pkg/watcher/skr_webhook_resources.go
  tests/e2e/manifest_reconciliation_test.go
  tests/e2e/utils_test.go
  tests/integration/controller/mandatorymodule/deletion/controller_test.go
  unit-test-coverage.yaml
Labels: lgtm, size/L, cla: yes

#1905 docs: Create a new folder structure
  README.md
  docs/README.md
  docs/contributor/01-architecture.md
  docs/contributor/02-controllers.md
  docs/contributor/03-config-private-registry.md
  docs/contributor/04-local-test-setup.md
  docs/contributor/05-api-changelog.md
  docs/contributor/assets/kyma-module-template-structure.svg
  docs/contributor/assets/kyma-operator-architecture.svg
  docs/contributor/assets/lifecycle-manager-architecture.svg
  docs/contributor/resources/01-kyma.md
  docs/contributor/resources/02-manifest.md
  docs/contributor/resources/03-moduletemplate.md
  docs/contributor/resources/04-watcher.md
  docs/contributor/resources/README.md
  docs/developer-tutorials/README.md
  docs/developer-tutorials/prepare-gcr-registry.md
  docs/developer-tutorials/provision-cluster-and-registry.md
  docs/developer-tutorials/starting-operator-with-webhooks.md
  docs/modularization.md
  docs/technical-reference/running-modes.md
  docs/user-tutorials/01-10-control-plane-quick-start.md
  docs/user-tutorials/02-10-manage-module-with-custom-resource-policy.md
  docs/user/01-10-kyma-crd.md
  docs/user/README.md
  internal/declarative/README.md
Labels: lgtm, size/XL, cla: yes

#1907 feat: Introduce Modulereleasemeta CRD
  api/v1beta2/modulereleasemeta_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_modulereleasemetas.yaml
  config/crd/kustomization.yaml
  docs/contributor/resources/05-modulereleasemeta.md
Labels: lgtm, size/L, cla: yes

#1912 chore: Bump golang to 1.23.2
  Dockerfile
  go.mod
Labels: lgtm, size/XS, cla: yes

#1916 chore: Bump missing go setup action
  .github/actions/setup-tools/action.yaml
Labels: lgtm, size/XS, cla: yes

#1910 feat: Add Resources as optional to ModuleTemplate
  api-version-compatibility-config.yaml
  api/v1beta2/moduletemplate_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
  docs/contributor/resources/03-moduletemplate.md
Labels: lgtm, size/M, cla: yes

#1927 chore: Revert "feat: Add new Panel to display Modules in Error State (#1873)"
  config/grafana/status.json
Labels: lgtm, size/M, cla: yes

#1923 feat: Add AssociatedResources to ModuleTemplate spec
  api-version-compatibility-config.yaml
  api/v1beta2/moduletemplate_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
  docs/contributor/resources/03-moduletemplate.md
Labels: lgtm, size/M, cla: yes

#1929 chore: Bump to latest runtime-watcher release 1.1.5 to be used in KLM…
  config/watcher/kustomization.yaml
  skr-webhook/resources.yaml
Labels: lgtm, size/XS, cla: yes

#1928 feat: Introduce ModuleTemplate Info
  .github/actions/get-configuration/action.yaml
  Makefile
  api-version-compatibility-config.yaml
  api/v1beta2/moduletemplate_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
  docs/contributor/resources/03-moduletemplate.md
Labels: size/L, cla: yes

#1939 fix: Filter kube_deployment_status_replicas_unavailable metric by value
  config/grafana/watcher.json
Labels: lgtm, size/S, cla: yes

#1941 fix: Rename github action file from .yaml to .yml
  .github/actions/create-k3d-cluster/action.yml
  .github/actions/deploy-cert-manager/action.yml
  .github/actions/deploy-istio/action.yml
  .github/actions/deploy-lifecycle-manager-e2e/action.yml
  .github/actions/deploy-lifecycle-manager/action.yml
  .github/actions/deploy-template-operator/action.yml
  .github/actions/export-kubeconfigs/action.yml
  .github/actions/get-configuration/action.yml
  .github/actions/install-cmctl/action.yml
  .github/actions/install-istioctl/action.yml
  .github/actions/install-k3d/action.yml
  .github/actions/install-kubectl/action.yml
  .github/actions/install-kyma-cli/action.yml
  .github/actions/patch-skr-hostname-in-kcp/action.yml
  .github/actions/setup-test-clusters/action.yml
  .github/actions/setup-tools/action.yml
  .github/actions/switch-kubectl-context/action.yml
  .github/actions/wait-for-image-build/action.yml
  .github/workflows/check-api-compatibility.yml
  .github/workflows/check-test-changes.yml
  .github/workflows/create-release.yml
  .github/workflows/test-e2e.yml
Labels: lgtm, size/XS, cla: yes

#1936 docs: Add docs for unmanaging modules
  docs/contributor/resources/01-kyma.md
  docs/user/01-10-kyma-crd.md
Labels: lgtm, size/S, cla: yes

#1938 chore: Use markdown-link-check@v1.0.15
  .github/workflows/lint-markdown-links.yml
  api/README.md
  docs/contributor/01-architecture.md
  docs/contributor/02-controllers.md
  docs/contributor/04-local-test-setup.md
  docs/contributor/05-api-changelog.md
  docs/contributor/resources/02-manifest.md
  docs/contributor/resources/README.md
  internal/controller/README.md
  internal/manifest/README.md
  tests/e2e/README.md
Labels: lgtm, size/M, cla: yes

#1945 chore: Remove watched-by label from manifest resources
  internal/declarative/v2/default_transforms.go
  internal/declarative/v2/default_transforms_test.go
  internal/declarative/v2/options.go
Labels: lgtm, size/S, cla: yes

#1932 chore: Deprecate .spec.channel field in ModuleTemplate API
  api/v1beta1/moduletemplate_types.go
  api/v1beta2/moduletemplate_types.go
  config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
  docs/contributor/resources/03-moduletemplate.md
Labels: lgtm, size/S, cla: yes

#1950 chore: Decouple build image job from e2e
  .github/workflows/build-image.yml
  .github/workflows/create-release.yml
  .github/workflows/test-e2e.yml
Labels: size/M, cla: yes

#1953 chore: Rename ocm package
  .golangci.yaml
  api/go.mod
  api/go.sum
  api/v1beta2/moduletemplate_types.go
  api/v1beta2/moduletemplate_webhook.go
  cmd/main.go
  go.mod
  go.sum
  internal/descriptor/cache/cache_test.go
  internal/descriptor/provider/provider.go
  internal/descriptor/provider/provider_test.go
  internal/manifest/img/parse.go
  pkg/templatelookup/regular_test.go
  pkg/testutils/builder/moduletemplate.go
  tests/integration/apiwebhook/moduletemplate_crd_validation_test.go
  tests/integration/apiwebhook/ocm_test.go
  tests/integration/apiwebhook/suite_test.go
  tests/integration/controller/eventfilters/suite_test.go
  tests/integration/controller/kcp/helper_test.go
  tests/integration/controller/kcp/remote_sync_test.go
  tests/integration/controller/kcp/suite_test.go
  tests/integration/controller/kyma/helper_test.go
  tests/integration/controller/kyma/kyma_module_channel_test.go
  tests/integration/controller/kyma/kyma_test.go
  tests/integration/controller/kyma/manifest_test.go
  tests/integration/controller/kyma/moduletemplate_install_test.go
  tests/integration/controller/kyma/suite_test.go
  tests/integration/controller/mandatorymodule/deletion/controller_test.go
  tests/integration/controller/mandatorymodule/installation/controller_test.go
  tests/integration/controller/manifest/manifest_controller_test.go
  tests/integration/controller/moduletemplate/moduletemplate_test.go
  tests/integration/controller/moduletemplate/suite_test.go
Labels: lgtm, size/XL, cla: yes

#1913 feat: Remove managed-by label when module is unmanaged
  cmd/main.go
  internal/controller/manifest/controller.go
  internal/controller/manifest/setup.go
  internal/declarative/v2/reconciler.go
  internal/declarative/v2/reconciler_test.go
  internal/manifest/labelsremoval/labels_removal.go
  internal/manifest/labelsremoval/labels_removal_test.go
  internal/manifest/manifestclient/manifest_client.go
  internal/manifest/manifestclient/manifest_client_test.go
  internal/pkg/metrics/manifest.go
  pkg/testutils/builder/manifest.go
  pkg/testutils/unstructured.go
  tests/e2e/manifest_reconciliation_test.go
  tests/e2e/module_unmanage_test.go
  tests/e2e/utils_test.go
  tests/integration/controller/manifest/custom_resource_check/suite_test.go
  tests/integration/controller/manifest/suite_test.go
  unit-test-coverage.yaml
Labels: size/XL, cla: yes

#1954 feat: Add Priority Class to SKR Webhook Pod
  skr-webhook/resources.yaml
Labels: lgtm, size/XS, cla: yes

#1947 feat: Use ModuleReleaseMeta in Kyma reconciliation loop instead of moduletemplate.channel
  .github/actions/deploy-template-operator-with-modulereleasemeta/action.yml
  .github/workflows/test-e2e-with-modulereleasemeta.yml
  api/shared/cr_kind.go
  config/rbac/common/role.yaml
  docs/contributor/02-controllers.md
  internal/cache_options.go
  internal/controller/kyma/controller.go
  pkg/templatelookup/modulereleasemeta.go
  pkg/templatelookup/modulereleasemeta_test.go
  pkg/templatelookup/regular.go
  pkg/templatelookup/regular_test.go
  pkg/testutils/builder/modulereleasemeta.go
  pkg/testutils/kyma.go
  pkg/testutils/modulereleasemeta.go
  pkg/testutils/moduletemplate.go
  tests/e2e/Makefile
  tests/e2e/module_deletion_upgrade_test.go
  tests/e2e/module_upgrade_new_version_test.go
  tests/e2e/modulereleasemeta_with_obsolete_moduletemplate_test.go
  tests/e2e/rbac_privileges_test.go
Labels: size/XXL, cla: yes

#1958 feat: Add spec.manager
  api-version-compatibility-config.yaml
  api/v1beta2/moduletemplate_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
  docs/contributor/resources/03-moduletemplate.md
Labels: lgtm, size/M, cla: yes

#1967 chore: Refactor manifest reconciler
  internal/controller/kyma/controller.go
  internal/controller/manifest/controller.go
  internal/declarative/v2/options.go
  internal/declarative/v2/reconciler.go
  internal/manifest/README.md
  internal/manifest/client.go
  internal/manifest/custom_resource.go
  internal/manifest/finalizer/handler.go
  internal/manifest/modulecr/client.go
  internal/manifest/modulecr/client_test.go
  internal/manifest/status/condition.go
  internal/manifest/status/init.go
  internal/manifest/status/state.go
  internal/remote/skr_context_provider.go
  pkg/common/error.go
  tests/integration/controller/manifest/custom_resource_check/suite_test.go
  tests/integration/controller/manifest/suite_test.go
Labels: lgtm, size/XL, cla: yes

#1970 chore: Fix Build Image tags
  .github/workflows/build-image.yml
Labels: lgtm, size/M, cla: yes

#1969 chore: Update protecode
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#1972 chore: Update watcher image
  config/watcher/kustomization.yaml
  internal/pkg/flags/flags.go
  skr-webhook/resources.yaml
Labels: lgtm, size/XS, cla: yes

#1974 chore: Add runConfigurations for local setup in Goland
  .gitignore
  .run/Create New Test Clusters.run.xml
  .run/Delete Test Clusters.run.xml
  .run/Deploy KLM from registry.run.xml
  .run/Deploy KLM from sources.run.xml
  .run/Deploy kyma.run.xml
  .run/Deploy template-operator.run.xml
  .run/E2E Tests.run.xml
  .run/Ensure Test Clusters.run.xml
  .run/Install CRDs.run.xml
  .run/Launch KLM locally.run.xml
  .run/Un-Deploy kyma.run.xml
  scripts/tests/create_test_clusters.sh
  scripts/tests/deploy_klm_from_registry.sh
Labels: lgtm, size/L, cla: yes

#1966 chore: Replace Kyma CLI with modulectl in e2e
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/actions/deploy-template-operator-with-modulereleasemeta/action.yml
  .github/actions/deploy-template-operator/action.yml
  .github/actions/get-configuration/action.yml
  .github/actions/install-kyma-cli/action.yml
  .github/actions/install-modulectl/action.yml
  .github/actions/setup-tools/action.yml
  .github/workflows/test-e2e-with-modulereleasemeta.yml
  .github/workflows/test-e2e.yml
  docs/contributor/03-config-private-registry.md
  docs/contributor/04-local-test-setup.md
  docs/contributor/resources/03-moduletemplate.md
Labels: lgtm, size/M, cla: yes

#1980 test: Add ModuleReleaseMeta Sync test
  .github/actions/deploy-template-operator-with-modulereleasemeta/action.yml
  .github/workflows/test-e2e-with-modulereleasemeta.yml
  pkg/testutils/modulereleasemeta.go
  tests/e2e/Makefile
  tests/e2e/modulereleasemeta_sync_test.go
Labels: lgtm, size/L, cla: yes

#1968 feat: Module release meta watch
  .github/actions/deploy-lifecycle-manager-e2e/action.yml
  .github/actions/deploy-template-operator-with-modulereleasemeta/action.yml
  .github/workflows/test-e2e-with-modulereleasemeta.yml
  config/rbac/common/role.yaml
  docs/contributor/02-controllers.md
  docs/contributor/04-local-test-setup.md
  internal/controller/kyma/controller.go
  internal/controller/kyma/setup.go
  internal/controller/mandatorymodule/setup.go
  internal/watch/change_handler_client.go
  internal/watch/mandatory_template_change.go
  internal/watch/modulereleasemeta_change.go
  internal/watch/modulereleasemeta_change_test.go
  internal/watch/template_change.go
  pkg/testutils/logs.go
  pkg/testutils/modulereleasemeta.go
  tests/e2e/Makefile
  tests/e2e/ca_certificate_rotation_test.go
  tests/e2e/kyma_metrics_test.go
  tests/e2e/modulereleasemeta_watch_trigger_test.go
  tests/e2e/rbac_privileges_test.go
  tests/e2e/utils_test.go
  tests/e2e/watcher_test.go
Labels: lgtm, size/XL, cla: yes

#1999 chore: Configure the linting for the api module
  .github/workflows/lint-golangci.yml
  Makefile
  api/v1beta2/kyma_types.go
  api/v1beta2/moduletemplate_types.go
  api/v1beta2/moduletemplate_types_test.go
  api/v1beta2/moduletemplate_webhook.go
  config/crd/bases/operator.kyma-project.io_kymas.yaml
  config/crd/bases/operator.kyma-project.io_moduletemplates.yaml
Labels: lgtm, size/M, do-not-merge/work-in-progress, cla: yes
