Repository kyma-project/lifecycle-manager, pull requests merged in 2025-03, with the labels that each got.

#2286 chore: Limit GH workflow permissions
  .github/workflows/build-image.yml
  .github/workflows/check-api-compatibility.yml
  .github/workflows/check-manifests-changes.yml
  .github/workflows/check-pipeline-changes.yml
  .github/workflows/check-test-changes.yml
  .github/workflows/create-release.yml
  .github/workflows/lint-conventional-prs.yml
  .github/workflows/lint-golangci.yml
  .github/workflows/lint-markdown-links.yml
  .github/workflows/lint-yaml.yml
  .github/workflows/report-acceptance-criteria.yml
  .github/workflows/report-package-metrics.yml
  .github/workflows/report-sprint-commits.yml
  .github/workflows/test-e2e-with-modulereleasemeta.yml
  .github/workflows/test-e2e.yml
  .github/workflows/test-unit.yml
  .github/workflows/verify-unit-test-coverage.yml
Labels: lgtm, size/M, cla: yes, pipeline-changed

#2287 chore: Update security scanners config for checkmarx one migration
  sec-scanners-config.yaml
Labels: size/S, cla: yes

#2250 chore: Add KLM prefix to Metric Name
  config/grafana/overview.json
  internal/pkg/metrics/maintance_window.go
  internal/pkg/metrics/maintance_window_test.go
  internal/pkg/metrics/metrics_test.go
  internal/pkg/metrics/watcher.go
  tests/e2e/commontestutils/metrics.go
  tests/e2e/self_signed_certificate_rotation_test.go
Labels: lgtm, size/M, cla: yes

#2305 chore: Add id-token WRITE to Create Release workflow
  .github/workflows/create-release.yml
Labels: lgtm, size/XS

#2306 chore: Bump watcher version and scanner version to latest image
  .run/Launch KLM locally.run.xml
  config/watcher/kustomization.yaml
  sec-scanners-config.yaml
Labels: size/XS

#2308 fix: Fix unit and integration tests GitHub action
  .github/workflows/test-unit.yml
Labels: lgtm, size/XS

#2246 chore: Add maintenancewindows to dependabot gomod
  .github/dependabot.yml
Labels: size/XS, cla: yes

#2319 chore: Remove the `operator.kyma-project.io/sync` label
  api/shared/operator_labels.go
  api/v1beta2/kyma_types.go
  api/v1beta2/moduletemplate_types.go
  docs/contributor/resources/01-kyma.md
  docs/contributor/resources/03-moduletemplate.md
  internal/controller/kyma/controller.go
  internal/remote/remote_catalog.go
  internal/remote/remote_catalog_test.go
  internal/tests/api/label_annotations_test.go
  internal/tests/api/modulesync_test.go
  pkg/status/conditions_test.go
  pkg/testutils/kyma.go
  scripts/tests/deploy_kyma.sh
  tests/e2e/deprovision_test.go
  tests/e2e/kyma_metrics_test.go
  tests/e2e/labelling_test.go
  tests/e2e/legacy_istio_gateway_secret_rotation_test.go
  tests/e2e/maintenance_windows_initial_installation_test.go
  tests/e2e/maintenance_windows_skip_test.go
  tests/e2e/maintenance_windows_wait_test.go
  tests/e2e/mandatory_module_test.go
  tests/e2e/mandatory_module_with_old_naming_pattern_test.go
  tests/e2e/mandatory_modules_metrics_test.go
  tests/e2e/mandatory_modules_with_old_naming_pattern_metrics_test.go
  tests/e2e/manifest_reconciliation_test.go
  tests/e2e/misconfigured_kyma_secret_test.go
  tests/e2e/module_consistency_test.go
  tests/e2e/module_deletion_test.go
  tests/e2e/module_deletion_upgrade_test.go
  tests/e2e/module_install_by_version_test.go
  tests/e2e/module_status_decoupling_test.go
  tests/e2e/module_unmanage_test.go
  tests/e2e/module_upgrade_channel_switch_test.go
  tests/e2e/module_upgrade_new_version_test.go
  tests/e2e/modulereleasemeta_module_deletion_upgrade_test.go
  tests/e2e/modulereleasemeta_module_upgrade_new_version_test.go
  tests/e2e/modulereleasemeta_not_allowed_installation_test.go
  tests/e2e/modulereleasemeta_sync_test.go
  tests/e2e/modulereleasemeta_watch_trigger_test.go
  tests/e2e/modulereleasemeta_with_obsolete_moduletemplate_test.go
  tests/e2e/no_default_cr_test.go
  tests/e2e/ocm_compatible_module_template_test.go
  tests/e2e/purge_controller_test.go
  tests/e2e/purge_metrics_test.go
  tests/e2e/self_signed_certificate_rotation_test.go
  tests/e2e/skr_connection_lost_test.go
  tests/e2e/watcher_test.go
  tests/e2e/watcher_zero_downtime_test.go
  tests/integration/controller/kcp/controller_test.go
  tests/integration/controller/kcp/manifest_test.go
Labels: kind/cleanup, size/L, pipeline-changed

#2330 chore: Bump kustomize version
  versions.yaml
Labels: pipeline-changed

#2324 chore: Migrate all Integration Tests from SingleCluster to DualCluster Mode
  pkg/testutils/kyma.go
  tests/integration/commontestutils/skrcontextimpl/dual_cluster.go
  tests/integration/controller/eventfilters/helper_test.go
  tests/integration/controller/eventfilters/suite_test.go
  tests/integration/controller/kcp/eventfilter_test.go
  tests/integration/controller/kcp/helper_test.go
  tests/integration/controller/kcp/remote_sync_test.go
  tests/integration/controller/kcp/suite_test.go
  tests/integration/controller/kyma/kyma_module_channel_test.go
  tests/integration/controller/kyma/kyma_module_enable_test.go
  tests/integration/controller/kyma/kyma_moduleinfo_test.go
  tests/integration/controller/kyma/kyma_test.go
  tests/integration/controller/kyma/manifest_test.go
  tests/integration/controller/kyma/moduletemplate_install_test.go
  tests/integration/controller/kyma/moduletemplate_test.go
  tests/integration/controller/kyma/suite_test.go
  tests/integration/controller/purge/controller_test.go
  tests/integration/controller/purge/suite_test.go
  tests/integration/controller/withwatcher/suite_test.go
Labels: size/XXL, area/tests

#2369 feat: Propagate Global Account and SubAccount Labels
  api/shared/operator_labels.go
  internal/remote/skr_context.go
  internal/remote/skr_context_test.go
  tests/e2e/labelling_test.go
Labels: kind/feature, size/M, cla: yes

#2370 feat: Add `--cert-management` Flag
  internal/pkg/flags/flags.go
  internal/pkg/flags/flags_test.go
Labels: kind/feature, size/S, cla: yes
