Repository kyma-project/lifecycle-manager, pull requests merged in 2025-09, with the labels that each got.

#2654 chore: Fix --oci-registry-host Flag for E2E
  .github/actions/deploy-lifecycle-manager-e2e/action.yml
  config/watcher_local_test/kustomization.yaml
  config/watcher_local_test_gcm/kustomization.yaml
Labels: pipeline-changed

#2737 feat: Configure Cert Duration and RenewBefore
  .github/workflows/test-e2e-with-gcm.yml
  config/certmanager/certificate_watcher.yaml
  config/gardener-certmanager/certificate_watcher.yaml
  internal/pkg/flags/flags.go
  internal/pkg/flags/flags_test.go
  internal/repository/watcher/certificate/gcm/certificate/certificate_repo.go
  internal/repository/watcher/certificate/gcm/certificate/certificate_repo_create_test.go
  tests/e2e/commontestutils/watcher.go
  versions.yaml
Labels: pipeline-changed, manifests-diff

#2753 chore: Use binary install for golangci-lint
  .github/workflows/lint-golangci.yml
  Makefile
Labels: goal/automation

#2772 fix: Rate Limiting in Kyma Processing State
  api/shared/zz_generated.deepcopy.go
  api/v1beta1/kyma_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta2/kyma_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_kymas.yaml
  config/crd/bases/operator.kyma-project.io_manifests.yaml
  internal/controller/kyma/controller.go
Labels: manifests-diff

#2765 chore: Remove module-name label support for ModuleTemplate
  api/v1beta2/kyma_types.go
  api/v1beta2/moduletemplate_types.go
  api/v1beta2/moduletemplate_types_test.go
  docs/contributor/resources/03-moduletemplate.md
  internal/maintenancewindows/maintenance_window.go
  internal/manifest/parser/template_to_module.go
  pkg/templatelookup/moduletemplateinfolookup/common.go
  pkg/templatelookup/moduletemplateinfolookup/common_test.go
  pkg/templatelookup/regular_test.go
  pkg/testutils/builder/moduletemplate.go
  pkg/testutils/moduletemplate.go
  tests/e2e/moduletemplate/moduletemplate_template_operator_transferred.yaml
  tests/integration/controller/kcp/helper_test.go
  tests/integration/controller/kcp/remote_sync_test.go
  tests/integration/controller/kyma/helper_test.go
  tests/integration/controller/kyma/kyma_module_channel_test.go
  tests/integration/controller/kyma/kyma_test.go
  tests/integration/controller/kyma/manifest_test.go
  tests/integration/controller/kyma/moduletemplate_install_test.go
  tests/integration/controller/mandatorymodule/deletion/controller_test.go
  tests/integration/controller/mandatorymodule/installation/controller_test.go
  tests/integration/moduletemplate/v1beta2_template_operator_current_ocm.yaml
  tests/integration/moduletemplate/v1beta2_template_operator_new_ocm.yaml
Labels: manifests-diff
