Repository kyma-project/lifecycle-manager, pull requests merged in 2025-04, with the labels that each got.

#2380 chore: Bump golang from 1.24.1 to 1.24.2
  Dockerfile
  api/go.mod
  go.mod
  maintenancewindows/go.mod
  versions.yaml
Labels: pipeline-changed

#2371 chore: Update watcher certificate manifest
  config/watcher/certificate.yaml
Labels: size/XS, kind/chore, cla: yes

#2394 docs: ADR 000 - Decisions are documented as ADRs
  docs/contributor/adr/000-document-decisions-as-adrs.md
Labels: goal/architecture

#2403 feat: Add New Script to Setup Test Clusters with GCM
  scripts/tests/apply_cm_certificate_management.sh
  scripts/tests/apply_gcm_certificate_management.sh
  scripts/tests/create_test_clusters.sh
  versions.yaml
Labels: pipeline-changed

#2420 feat: E2E Tests with GCM
  .github/actions/deploy-lifecycle-manager-e2e/action.yml
  .github/actions/deploy-lifecycle-manager/action.yml
  .github/actions/get-configuration/action.yml
  .github/actions/setup-test-clusters-gcm/action.yml
  .github/workflows/test-e2e-with-gcm.yml
  cmd/main.go
  config/watcher_local_test_gcm/kustomization.yaml
  scripts/tests/apply_gcm_certificate_management.sh
Labels: pipeline-changed

#2433 feat: Add GetValidity implementation for Gardener certificate
  .github/actions/deploy-lifecycle-manager/action.yml
  .github/workflows/test-e2e-with-gcm.yml
  config/watcher_local_test_gcm/kustomization.yaml
  internal/pkg/flags/flags.go
  internal/pkg/flags/flags_test.go
  internal/setup/certificate.go
  pkg/watcher/certificate/gardener/certificate.go
  pkg/watcher/certificate/gardener/certificate_test.go
  unit-test-coverage.yaml
Labels: pipeline-changed

#2407 docs: ADR 001 - Consumer-Defined Interfaces
  docs/contributor/adr/001-consumer-defined-interfaces.md
Labels: goal/architecture
