Repository kyma-project/lifecycle-manager, pull requests merged in 2025-02, with the labels that each got.

#2218 feat: Add grouping to `dependabot` PRs
  .github/dependabot.yml
Labels: size/S, cla: yes

#2233 fix: Nil pointer when unmanaging module with `Ignore` CustomResourcePolicy
  internal/declarative/v2/reconciler.go
  internal/manifest/finalizer/handler.go
  internal/manifest/labelsremoval/labels_removal.go
  internal/manifest/labelsremoval/labels_removal_test.go
  internal/manifest/modulecr/client.go
  pkg/testutils/builder/manifest.go
  tests/e2e/module_unmanage_test.go
  unit-test-coverage.yaml
Labels: lgtm, size/L, cla: yes

#2238 feat: Maintenance window metric
  .github/actions/deploy-lifecycle-manager-e2e/action.yml
  cmd/main.go
  go.mod
  internal/maintenancewindows/maintenance_window.go
  internal/maintenancewindows/maintenance_window_test.go
  internal/pkg/metrics/maintance_window.go
  internal/pkg/metrics/maintance_window_test.go
  tests/e2e/commontestutils/metrics.go
  tests/e2e/maintenance_windows_initial_installation_test.go
Labels: lgtm, size/L, cla: yes

#2240 chore: Use flag for min maintwindow size
  .github/actions/deploy-lifecycle-manager-e2e/action.yml
  cmd/main.go
  config/watcher_local_test/kustomization.yaml
  internal/maintenancewindows/maintenance_window.go
  internal/maintenancewindows/maintenance_window_test.go
  internal/pkg/flags/flags.go
  internal/pkg/flags/flags_test.go
Labels: lgtm, size/M, cla: yes

#2252 chore: Bump sec-scanners config and rt-watcher version
  config/watcher/kustomization.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#2247 feat: Add Maintenance Window Config Read Status to Monitoring Dashboard
  config/grafana/overview.json
Labels: lgtm, size/L, cla: yes

#2259 feat: Transform Kyma.Status before syncing to SKR
  internal/remote/skr_context.go
  internal/remote/skr_context_test.go
Labels: size/L, cla: yes

#2257 chore: Split Kyma sync into Status and Metadata sync
  internal/controller/kyma/controller.go
  internal/declarative/v2/default_transforms.go
  internal/manifest/modulecr/client.go
  internal/remote/crd_upgrade.go
  internal/remote/modulereleasemeta_syncworker.go
  internal/remote/moduletemplate_syncworker.go
  internal/remote/skr_context.go
  internal/remote/skr_context_test.go
  internal/util/collections/collections.go
  internal/util/collections/collections_test.go
  pkg/testutils/builder/kyma.go
  pkg/watcher/skr_webhook_manifest_manager.go
  pkg/watcher/skr_webhook_resources.go
  unit-test-coverage.yaml
Labels: lgtm, size/XL, cla: yes

#2264 chore: Remove plan mapping TODO
  api/shared/operator_labels.go
  api/v1beta2/kyma_types.go
Labels: lgtm, size/XS, cla: yes

#2251 feat: Unexepected field managers reporting
  internal/manifest/skrresources/collector.go
  internal/manifest/skrresources/collector_test.go
  internal/manifest/skrresources/manifestcollector.go
  internal/manifest/skrresources/ssa.go
  internal/manifest/skrresources/ssa_test.go
  internal/manifest/skrresources/sync.go
Labels: lgtm, size/L, cla: yes

#2226 feat: Istio Gateway Secret CA Cert Bundling
  .github/actions/deploy-lifecycle-manager-e2e/action.yml
  .github/actions/deploy-template-operator-with-modulereleasemeta/action.yml
  .github/workflows/test-e2e-with-modulereleasemeta.yml
  .github/workflows/test-e2e.yml
  .golangci.yaml
  .vscode/tasks.json
  internal/controller/istiogatewaysecret/controller.go
  internal/controller/istiogatewaysecret/controller_test.go
  internal/controller/istiogatewaysecret/setup.go
  internal/gatewaysecret/cabundle/handler.go
  internal/gatewaysecret/cabundle/handler_test.go
  internal/gatewaysecret/handler.go
  internal/gatewaysecret/legacy/handler.go
  internal/gatewaysecret/legacy/handler_test.go
  internal/gatewaysecret/testutils/mock_Client.go
  internal/pkg/flags/flags.go
  internal/pkg/flags/flags_test.go
  pkg/testutils/kyma.go
  pkg/testutils/utils.go
  scripts/tests/create_test_clusters.sh
  tests/e2e/Makefile
  tests/e2e/ca_certificate_rotation_test.go
  tests/e2e/commontestutils/metrics.go
  tests/e2e/legacy_istio_gateway_secret_rotation_test.go
  tests/e2e/maintenance_windows_initial_installation_test.go
  tests/e2e/maintenance_windows_skip_test.go
  tests/e2e/maintenance_windows_wait_test.go
  tests/e2e/module_deletion_test.go
  tests/e2e/module_upgrade_channel_switch_test.go
  tests/e2e/watcher_test.go
  tests/e2e/watcher_zero_downtime_test.go
  tests/integration/controller/kyma/kyma_module_channel_test.go
  unit-test-coverage.yaml
Labels: lgtm, size/XXL, cla: yes, pipeline-changed

#2273 test: Increase moduletemplateinfolookup testcoverage
  pkg/templatelookup/moduletemplateinfolookup/by_channel_strategy_test.go
  pkg/templatelookup/moduletemplateinfolookup/by_module_release_meta_strategy_test.go
  pkg/templatelookup/moduletemplateinfolookup/by_version_strategy_test.go
  pkg/templatelookup/moduletemplateinfolookup/common_test.go
  unit-test-coverage.yaml
Labels: lgtm, size/L, cla: yes

#2207 chore: RBAC cleanup
  .run/Launch KLM locally.run.xml
  PROJECT
  config/certmanager/kustomization.yaml
  config/control-plane/kustomization.yaml
  config/control-plane/patches/deployment_resources.yaml
  config/control-plane/patches/secured_manager_auth_proxy.yaml
  config/control-plane/patches/unique_certificate_name.yaml
  config/control-plane/patches/unique_deployment_webhook_patch.yaml
  config/crd/kustomizeconfig.yaml
  config/default/kustomization.yaml
  config/default/namespace.yaml
  config/default/patches/deployment_webhook.yaml
  config/istio/commonlabels_override.yaml
  config/istio/endpoints_authorization_policy.yaml
  config/istio/kustomization.yaml
  config/istio/patches/deployment_exclude_webhook_port.yaml
  config/istio/patches/deployment_istio_inject.yaml
  config/maintenance_windows/kustomization.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/certmanager_role.yaml
  config/rbac/certmanager_role_binding.yaml
  config/rbac/cluster_bindings/clusterrole_binding.yaml
  config/rbac/cluster_bindings/kustomization.yaml
  config/rbac/cluster_bindings/metrics_clusterrole_binding.yaml
  config/rbac/common/crd_clusterrole.yaml
  config/rbac/common/kustomization.yaml
  config/rbac/common/leader_election_role.yaml
  config/rbac/common/role.yaml
  config/rbac/crd_cluster_role.yaml
  config/rbac/crd_cluster_role_binding.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/manager_role.yaml
  config/rbac/manager_role_binding.yaml
  config/rbac/namespace_bindings/istio_namespace_role.yaml
  config/rbac/namespace_bindings/kustomization.yaml
  config/rbac/namespace_bindings/remote_namespace_role.yaml
  config/rbac/namespace_bindings/role_binding.yaml
  config/rbac/namespace_bindings/watcher_certmanager_role_binding.yaml
  config/rbac/service_account.yaml
  config/watcher/certificate.yaml
  config/watcher/gateway.yaml
  config/watcher/kustomization.yaml
  config/watcher/kyma_watcher.yaml
  config/watcher_local_test/kustomization.yaml
  config/watcher_local_test/namespace.yaml
  config/watcher_local_test/patches/deployment_resources.yaml
  config/watcher_local_test/patches/namespace_create.yaml
  config/webhook/kustomization.yaml
  internal/controller/kyma/controller.go
  internal/controller/manifest/controller.go
  internal/controller/watcher/controller.go
  tests/e2e/commontestutils/rbac.go
  tests/e2e/rbac_privileges_test.go
  versions.yaml
Labels: lgtm, size/XXL, cla: yes

#2284 chore: Add yamllint pipeline
  .github/DISCUSSION_TEMPLATE/q-a.yml
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/actions/deploy-lifecycle-manager-e2e/action.yml
  .github/actions/deploy-template-operator-with-modulereleasemeta/action.yml
  .github/actions/deploy-template-operator/action.yml
  .github/actions/get-configuration/action.yml
  .github/actions/install-k3d/action.yml
  .github/actions/install-kubectl/action.yml
  .github/actions/install-yq/action.yml
  .github/actions/setup-tools/action.yml
  .github/actions/wait-for-image-build/action.yml
  .github/workflows/check-api-compatibility.yml
  .github/workflows/check-manifests-changes.yml
  .github/workflows/check-pipeline-changes.yml
  .github/workflows/create-release.yml
  .github/workflows/lint-golangci.yml
  .github/workflows/lint-yaml.yml
  .github/workflows/test-e2e-with-modulereleasemeta.yml
  .golangci.yaml
  .markdownlint.yaml
  .yamllint.yml
  Makefile
  config/certmanager/certificate.yaml
  config/certmanager/kustomizeconfig.yaml
  config/control-plane/kustomization.yaml
  config/control-plane/patches/unique_deployment_webhook_patch.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/default/patches/deployment_webhook.yaml
  config/istio/commonlabels_override.yaml
  config/istio/endpoints_authorization_policy.yaml
  config/manager/manager.yaml
  config/manager/metrics_service.yaml
  config/rbac/certmanager_role.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/samples/component-integration-installed/crd/operator.kyma-project.io_kcpmodules.yaml
  config/samples/component-integration-installed/operator_v1beta2_kyma.yaml
  config/samples/component-integration-installed/v1_secret_remote_cluster_access.yaml
  config/watcher/certificate.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/service.yaml
  maintenancewindows/resolver/testdata/ruleset-3.yaml
  pkg/test_samples/oci/btp-operator-manifest.yaml
  pkg/test_samples/oci/invalid-yaml.yaml
  pkg/test_samples/oci/manifest-contains-duplicate-resources.yaml
  pkg/test_samples/oci/rendered.yaml
  pkg/test_samples/oci/template-operator-manifest.yaml
  pkg/test_samples/raw-manifest.yaml
  skr-webhook/resources.yaml
  tests/e2e/moduletemplate/mandatory_moduletemplate_template_operator_v1.yaml
  tests/e2e/moduletemplate/mandatory_moduletemplate_template_operator_v2.yaml
  tests/e2e/moduletemplate/moduletemplate_template_operator_regular_new_ocm.yaml
  tests/e2e/moduletemplate/moduletemplate_template_operator_v1_regular.yaml
  tests/e2e/moduletemplate/moduletemplate_template_operator_v2_fast.yaml
  tests/integration/moduletemplate/v1beta2_kcp-module-cred-label.yaml
Labels: lgtm, size/XXL, cla: yes, pipeline-changed
