Repository kyma-project/lifecycle-manager, pull requests merged in 2025-01, with the labels that each got.

#2155 feat: Maintenance Windows resolver module
  .github/workflows/lint-golangci.yml
  Makefile
  maintenancewindows/README.md
  maintenancewindows/go.mod
  maintenancewindows/go.sum
  maintenancewindows/resolver/maintwindow.go
  maintenancewindows/resolver/maintwindow_test.go
  maintenancewindows/resolver/resolver.go
  maintenancewindows/resolver/resolver_test.go
  maintenancewindows/resolver/testdata/ruleset-1.json
  maintenancewindows/resolver/testdata/ruleset-2.json
  maintenancewindows/resolver/testdata/ruleset-3.yaml
Labels: lgtm, size/XL, cla: yes

#2160 chore: Add VSCode launch config for tests
  .vscode/launch.json
Labels: lgtm, size/M, cla: yes

#2161 chore(deps): Bump golang.org/x/net to v0.33.0
  api/go.mod
  api/go.sum
Labels: lgtm, size/S, cla: yes

#2158 test: Labelling SKR resources
  .github/actions/deploy-template-operator-with-modulereleasemeta/action.yml
  .github/actions/deploy-template-operator/action.yml
  .github/workflows/test-e2e-with-modulereleasemeta.yml
  .github/workflows/test-e2e.yml
  .vscode/tasks.json
  tests/e2e/Makefile
  tests/e2e/labelling_test.go
  tests/e2e/manifest_reconciliation_test.go
  tests/e2e/utils_test.go
Labels: size/L, cla: yes

#2162 fix: Cleanup certificates when kyma with skip-reconciliation gets deleted after the label removal
  internal/controller/kyma/controller.go
  pkg/testutils/watcher.go
  pkg/watcher/certificate_manager.go
  pkg/watcher/skr_webhook_manifest_manager.go
  tests/e2e/deprovision_test.go
  tests/e2e/watcher_test.go
Labels: lgtm, size/L, cla: yes

#2169 chore: Replace namespace istio injection with pod injection label
  config/istio/kustomization.yaml
  config/istio/patches/istio_deployment_labels.yaml
  config/istio/patches/istio_namespace_labels.yaml
Labels: lgtm, size/S, cla: yes

#2170 chore: Bump sec-scanners-config to 1.2.7 and use runtime-watcher 1.1.10
  config/watcher/kustomization.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#2176 chore: Re-Add 'latest' tag to sec-scanners-config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#2172 chore: Introduce `versions.yaml` file
  .github/actions/get-configuration/action.yml
  .github/actions/install-k3d/action.yml
  .github/actions/install-yq/action.yml
  .github/workflows/lint-golangci.yml
  .vscode/extensions.json
  .vscode/tasks.json
  Makefile
  docs/contributor/04-local-test-setup.md
  scripts/tests/README.md
  scripts/tests/version.sh
  versions.yaml
Labels: lgtm, size/L, cla: yes

#2171 feat: Read Maintenance Window Policies
  .github/workflows/test-e2e-with-modulereleasemeta.yml
  Dockerfile
  cmd/main.go
  config/maintenance_windows/kustomization.yaml
  config/maintenance_windows/patches/volume_mount.yaml
  config/maintenance_windows/policy.json
  config/watcher_local_test/kustomization.yaml
  go.mod
  internal/maintenancewindows/maintenance_policy_handler.go
  internal/maintenancewindows/maintenance_policy_handler_test.go
  internal/maintenancewindows/testdata/invalid-policy.json
  internal/maintenancewindows/testdata/policy.json
  unit-test-coverage.yaml
Labels: lgtm, size/L, cla: yes

#2187 test: Add Concept for Maintenance Window with Module Downtime E2E Test
  .github/actions/deploy-lifecycle-manager-e2e/action.yml
  .github/actions/deploy-template-operator-with-modulereleasemeta/action.yml
  .github/workflows/test-e2e-with-modulereleasemeta.yml
  scripts/tests/deploy_moduletemplate.sh
  tests/e2e/Makefile
  tests/e2e/modulereleasemeta_maintenance_window_module_downtime_test.go
  versions.yaml
Labels: lgtm, size/L, cla: yes

#2188 chore: Drop module condition metrics
  cmd/main.go
  internal/controller/kyma/controller.go
  internal/controller/manifest/controller.go
  internal/controller/manifest/setup.go
  internal/declarative/v2/reconciler.go
  internal/manifest/modulecr/client.go
  internal/manifest/modulecr/client_test.go
  internal/manifest/status/condition.go
  internal/manifest/status/init.go
  internal/pkg/metrics/module.go
  pkg/module/sync/runner.go
  pkg/module/sync/runner_test.go
  tests/e2e/commontestutils/metrics.go
  tests/e2e/module_status_decoupling_test.go
  tests/integration/controller/eventfilters/suite_test.go
  tests/integration/controller/kcp/suite_test.go
  tests/integration/controller/kyma/suite_test.go
  tests/integration/controller/manifest/custom_resource_check/suite_test.go
  tests/integration/controller/manifest/suite_test.go
  tests/integration/controller/withwatcher/suite_test.go
  unit-test-coverage.yaml
Labels: lgtm, size/L, cla: yes

#2197 docs: Reference Mandatory Modules Controller in Architecture Docs
  docs/contributor/01-architecture.md
Labels: lgtm, size/XS, cla: yes

#2196 feat: Implement MaintenanceWindow determination logic
  cmd/main.go
  internal/controller/kyma/controller.go
  internal/maintenancewindows/maintenance_policy_handler.go
  internal/maintenancewindows/maintenance_policy_handler_test.go
  internal/maintenancewindows/maintenance_window.go
  internal/maintenancewindows/maintenance_window_test.go
  pkg/templatelookup/regular.go
  pkg/templatelookup/regular_test.go
  pkg/testutils/builder/kyma.go
  pkg/testutils/builder/moduletemplate.go
  pkg/testutils/moduletemplate.go
  tests/integration/controller/kcp/suite_test.go
  tests/integration/controller/kyma/suite_test.go
Labels: lgtm, size/XL, cla: yes

#2199 fix: Fix the syncing of ModuleReleaseMeta Beta and Internal values when edited on the SKR Cluster
  api/v1beta2/modulereleasemeta_types.go
  pkg/testutils/modulereleasemeta.go
  tests/e2e/modulereleasemeta_sync_test.go
Labels: lgtm, size/M, cla: yes

#2178 docs: Update local-test-setup.md to use scripts
  docs/contributor/04-local-test-setup.md
  scripts/tests/version.sh
  versions.yaml
Labels: lgtm, size/L, cla: yes

#2201 chore: Add version and name helpers to ModuleTemplate
  api/v1beta2/moduletemplate_types.go
  api/v1beta2/moduletemplate_types_test.go
  internal/descriptor/cache/key.go
  internal/maintenancewindows/maintenance_window.go
Labels: lgtm, size/L, cla: yes

#2198 feat: Removed skr permission and cache config for remote kyma & ModuleTemp…
  cmd/main.go
  config/rbac/namespace_bindings/kustomization.yaml
  config/rbac/namespace_bindings/skr_role.yaml
  config/rbac/namespace_bindings/skr_role_binding.yaml
  internal/cache_options.go
  tests/e2e/rbac_privileges_test.go
  tests/integration/controller/eventfilters/suite_test.go
  tests/integration/controller/kcp/suite_test.go
  tests/integration/controller/kyma/suite_test.go
  tests/integration/controller/mandatorymodule/deletion/suite_test.go
  tests/integration/controller/mandatorymodule/installation/suite_test.go
  tests/integration/controller/manifest/custom_resource_check/suite_test.go
  tests/integration/controller/manifest/suite_test.go
  tests/integration/controller/moduletemplate/suite_test.go
  tests/integration/controller/purge/suite_test.go
  tests/integration/controller/withwatcher/suite_test.go
Labels: lgtm, size/L, cla: yes

#2200 feat: Refactor template lookup to use strategy pattern
  cmd/main.go
  pkg/module/sync/runner.go
  pkg/templatelookup/moduletemplateinfolookup/by_channel_strategy.go
  pkg/templatelookup/moduletemplateinfolookup/by_channel_strategy_test.go
  pkg/templatelookup/moduletemplateinfolookup/by_module_release_meta_strategy.go
  pkg/templatelookup/moduletemplateinfolookup/by_module_release_meta_strategy_test.go
  pkg/templatelookup/moduletemplateinfolookup/by_version_strategy.go
  pkg/templatelookup/moduletemplateinfolookup/by_version_strategy_test.go
  pkg/templatelookup/moduletemplateinfolookup/common.go
  pkg/templatelookup/moduletemplateinfolookup/strategies.go
  pkg/templatelookup/moduletemplateinfolookup/strategies_test.go
  pkg/templatelookup/regular.go
  pkg/templatelookup/regular_test.go
  pkg/testutils/moduletemplate.go
  tests/e2e/module_deletion_test.go
  tests/e2e/module_upgrade_new_version_test.go
  tests/e2e/modulereleasemeta_maintenance_window_module_downtime_test.go
  tests/e2e/modulereleasemeta_module_upgrade_new_version_test.go
  tests/e2e/modulereleasemeta_not_allowed_installation_test.go
  tests/e2e/modulereleasemeta_sync_test.go
  tests/integration/controller/kcp/helper_test.go
  tests/integration/controller/kcp/remote_sync_test.go
  tests/integration/controller/kcp/suite_test.go
  tests/integration/controller/kyma/helper_test.go
  tests/integration/controller/kyma/kyma_test.go
  tests/integration/controller/kyma/manifest_test.go
  tests/integration/controller/kyma/suite_test.go
  unit-test-coverage.yaml
Labels: lgtm, size/XXL, cla: yes

#2206 feat: Skip module updates requiring maintenance windows when not active
  .github/actions/deploy-lifecycle-manager-e2e/action.yml
  .github/actions/deploy-template-operator-with-modulereleasemeta/action.yml
  .github/workflows/test-e2e-with-modulereleasemeta.yml
  .vscode/launch.json
  .vscode/tasks.json
  cmd/main.go
  internal/maintenancewindows/maintenance_window.go
  internal/maintenancewindows/maintenance_window_test.go
  pkg/module/sync/runner.go
  pkg/templatelookup/moduletemplateinfolookup/with_maintenance_window_decorator.go
  pkg/templatelookup/moduletemplateinfolookup/with_maintenance_window_decorator_test.go
  pkg/templatelookup/regular.go
  tests/e2e/Makefile
  tests/e2e/maintenance_windows_initial_installation_test.go
  tests/e2e/maintenance_windows_skip_test.go
  tests/e2e/maintenance_windows_wait_test.go
Labels: lgtm, size/XL, cla: yes

#2211 chore: Bump lifecycle manager to 1.2.8 in security scanners config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#2215 chore: Bump golang runtime version
  Dockerfile
  api/go.mod
  go.mod
  maintenancewindows/go.mod
  versions.yaml
Labels: lgtm, size/S, cla: yes

#2216 fix: Memory Leak in transport.tlsTransportCache
  internal/declarative/v2/factory.go
  internal/remote/skr_context_provider.go
Labels: lgtm, size/XS, cla: yes

#2203 docs: Provide Monitoring docs
  docs/operator/operations.md
Labels: lgtm, size/L, cla: yes

#2220 fix(deploy_kyma.sh): Enable Sync by Default
  scripts/tests/deploy_kyma.sh
Labels: lgtm, size/XS, cla: yes

#2227 chore: Bump modulectl version to 1.1.6
  versions.yaml
Labels: lgtm, size/XS, cla: yes
