Repository kyma-project/lifecycle-manager, pull requests merged in 2025-08, with the labels that each got.

#2639 chore: bump go to 1.24.5
  api/go.mod
  go.mod
  maintenancewindows/go.mod
  versions.yaml
Labels: pipeline-changed

#2633 feat: Separate Cert Renewal Services
  .github/workflows/test-unit.yml
  .github/workflows/verify-unit-test-coverage.yml
  .golangci.yaml
  cmd/composition/service/skrwebhook/skr_webhook_manager.go
  internal/repository/watcher/certificate/gcm/renewal/certificate_repo.go
  internal/repository/watcher/certificate/gcm/renewal/certificate_repo_test.go
  internal/service/watcher/certificate/certificate_service.go
  internal/service/watcher/certificate/certificate_service_test.go
  internal/service/watcher/certificate/renewal/certmanager/renewal_service.go
  internal/service/watcher/certificate/renewal/certmanager/renewal_service_test.go
  internal/service/watcher/certificate/renewal/gcm/renewal_service.go
  internal/service/watcher/certificate/renewal/gcm/renewal_service_test.go
  tests/e2e/watcher_test.go
  tests/integration/controller/withwatcher/suite_test.go
  tests/integration/watcher/certificate_test.go
  unit-test-coverage.yaml
Labels: manifests-diff

#2647 docs: Adjust formatting for correct Help Portal rendering
  docs/README.md
  docs/contributor/02-controllers.md
  docs/contributor/09-metrics.md
Labels: area/documentation

#2650 chore: Bump golang to 1.24.6
  api/go.mod
  go.mod
  maintenancewindows/go.mod
  versions.yaml
Labels: pipeline-changed

#2642 feat: Read OCI Registry Host from Arg or Cred Secret
  .github/actions/deploy-lifecycle-manager-e2e/action.yml
  cmd/main.go
  config/watcher_local_test/kustomization.yaml
  config/watcher_local_test_gcm/kustomization.yaml
  internal/common/errors.go
  internal/pkg/flags/flags.go
  internal/pkg/flags/flags_test.go
  internal/setup/ociregistryhostprovider.go
  internal/setup/ociregistryhostprovider_test.go
Labels: pipeline-changed

#2679 feat: Add ocmComponentName to MRM
  api/v1beta2/modulereleasemeta_types.go
  config/crd/bases/operator.kyma-project.io_modulereleasemetas.yaml
  pkg/testutils/builder/modulereleasemeta.go
  scripts/tests/deploy_modulereleasemeta.sh
  tests/integration/controller/modulereleasemeta/modulereleasemeta_test.go
Labels: pipeline-changed
